### ISSUE TITLE
Cannot see state/properties

### ISSUE THREAD

**Issue by cdarken** [rangle/augury#1000]
Augury version (required): 1.2.12
Angular version (required): 2.4.9
Date: 2017-03-03
OS: Ubuntu 14.04

Description of issue:
I cannot see the State section for a component, I can see the properties on load, but then they disappear.

**Comment by stevenkampen** [comment]
@cdarken Can you describe a particular component configuration where this occurs? Or point me towards a public repo where it happens?

**Comment by cdarken** [comment]
I will try to create a simple project and see if the problem manifests itself in that project too. I will be back with details, I hope tomorrow.

**Comment by jacobjojan** [comment]
Augury version: 1.2.12
Windows 7

I have the same issue as not able to see the state/properties for my components. But I am able to see the material UI components state. All my components are inside material UI components

Sample below... 
 mycustom-side-nav have an array property of routes called `mainNav`. 
But that is not showing up under states.
```
<md-sidenav-container>
  <md-sidenav #sidenav mode="side"  opened="true">
    <md-nav-list>
      <mycustom-side-nav></mycustom-side-nav>
    </md-nav-list>
  </md-sidenav>
  <main class="main-content">
    <router-outlet></router-outlet>
  </main>
</md-sidenav-container>
```

```
@Component({
  selector: 'mycustom-side-nav',
  templateUrl: 'side-nav.component.html',
  styleUrls: ['./side-nav.component.css']
})
export class MyCustomSideNavComponent implements OnInit {
  public mainNav: Routes = [];
 constructor(private _router: Router) {
 }
 public ngOnInit() {
    // initializations happens here
  }
}
```

**Comment by cdarken** [comment]
Yes, I noticed that the properties for some elements from @angular/material that I'm using are visible, but those for my own components are not. Are there certain conditions needed? I tried to set some of them public, but still no luck. The thing is that they flash momentarily then they disappear.

**Comment by sballarati** [comment]
**+1** I cannot see it in the properties/state panel but I am able to see the object in the chrome console, see below the `groups` property:

![snip20170310_18](https://cloud.githubusercontent.com/assets/1125619/23799808/a2658042-0588-11e7-990c-35ca744f4445.png)

In the regular console, same `groups` property that was printed using console.log():
![snip20170310_17](https://cloud.githubusercontent.com/assets/1125619/23799918/0d74b650-0589-11e7-8c90-a85f4dab0085.png)

**Comment by stevenkampen** [comment]
@sballarati This looks like a separate issue. Do you mind opening a new issue with these details?

**Comment by stevenkampen** [comment]
@jacobjojan Can you provide a more concrete form of that example? I don't think I can replicate just from this code.

**Comment by sballarati** [comment]
@stevenkampen I created a new issue for that: https://github.com/rangle/augury/issues/1029

Thanks and have a great weekend!

**Comment by stevenkampen** [comment]
@jacobjojan I'm pretty sure this is fixed now in 1.5.0 (just released). If you could test it and let me know that would be great.

**Comment by stevenkampen** [comment]
@cdarken Ahh yes that issue still exists I see. For a while I thought it was gone but apparently not. I'll log it now.

**Comment by jacobjojan** [comment]
Will test and let you know.
