### ISSUE TITLE
Add analytics tracking to gain insight into usage trends

### ISSUE THREAD

**Issue by ttmarek** [rangle/augury#1005]
It'd be nice to have analytics to identify trends on how people are using Augury, and also on the types of projects people are using Augury for. This should help us prioritize issues, new features, and design updates.

I think [angulartics](https://github.com/angulartics/angulartics2) is our best bet for collecting basic analytics, with Google Analytics as the reporting tool.

**Comment by stevenkampen** [comment]
@ttmarek Does angulartics actually have something for Angular 2? That link you provided just references angular1.x. I'm on the train right now so haven't search in depth.

**Comment by ttmarek** [comment]
@stevenkampen, sorry, linked the wrong one, its https://github.com/angulartics/angulartics2

**Comment by mobinni** [comment]
@ttmarek - Couple of questions:
- Do we have any idea of what interactions we want to track. 
- Do we have an analytics ID for dev/prod?

**Comment by AbdellaToronto** [comment]
I'll be picking this story up!

**Comment by mobinni** [comment]
@AbdellaToronto There's a branch where I already set up the start of this: https://github.com/mobinni/augury/tree/feat/analytics. It purely sets up google analytics in the backend.ts (You want to communicate through messages over the bridge for tracking events).

**Comment by AbdellaToronto** [comment]
So I'm in the process of implementing this with angulartics2 - so far so good, although I think there might be some concern with integrating this with the router, I'll look into this. I think I might need access to the analytics dashboard to test and make sure everything is working.
