### ISSUE TITLE
Cannot enlarge component tree view  

### ISSUE THREAD

**Issue by samdidos** [rangle/augury#1008]
Augury version (required): 1.2.12
Angular version (required): 2
OS: Ubuntu

Description of issue:
I'm unable to enlarge the component tree view. It had shrunk after I change the view (RouterTree or NgModules) and I cannot put it back the way it was. Can you please make the line position customizable? There's also unused blank at the right side.

Here's a screenshot : 

![augury-issue-indication](https://cloud.githubusercontent.com/assets/7490081/23727002/5f2d9608-0424-11e7-9169-dc7656b2ba41.png)

Thank you

**Comment by stevenkampen** [comment]
@samdidos If you go to resize the inspector window itself, do the widths readjust?

**Comment by samdidos** [comment]
Well, I don't why but it's fixed now. Must be a glitch, I'm not able to reproduce my problem now. Thx anyway!

**Comment by rajinder-yadav** [comment]
FYI, it occasionally happens to me, I usually close down devtools and
reopen it.
