### ISSUE TITLE
Augury feature for Forms

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#1016]
We need to round up the feature set for working with Forms.

**Comment by rajinder-yadav** [comment]
I've got a demo app ready with forms for the Guide, will use it to consider ideas for Augury feature set.

**Comment by stevenkampen** [comment]
@rajinder-yadav I think we need to make a proper investigation for any 'forms' specific features. I'm not sure that it will be necessary, or worth it, so I don't just want to jump straight to trying to think of something to do. The fact is, forms are very finicky, and everything is already available through component state. Trying to apply another layer on top of that seems like a lot of continuous work for very little pay off.

**Comment by rajinder-yadav** [comment]
@stevenkampen I just plan to review if anything obvious is missing, my main objective is to complete the Forms guide and not really add more feature for Form to Augury. I agree with your comments.

**Comment by stevenkampen** [comment]
resolved by #1043
