### ISSUE TITLE
Update issues with Augury

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#1022]
Augury version (required): Build of dev branch
Angular version (required): 2.x
Date: 2017-03-15
OS: Linux

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
Use kitchen sink app or Guides Routes demo app.

Description of issue:

I've started to notice there is a lag with Augury and at times it fails to update when its initial opened. I am seeing this with Routes.

Steps to reproduce:

1. Use our Routes Guide demo app or Kitchen sink app
2. Open Augury
3. Click on the Routes Tree tab
4. Routes is blank.

Additional details:

Only reason you see routes come up when "Cities" is clicked is because this is a lazy loaded module and it causes a refresh which draws the router tree.

![routes](https://cloud.githubusercontent.com/assets/439226/23959137/b6415e42-097a-11e7-924a-1e7b2f6fafb4.gif)

**Comment by rajinder-yadav** [comment]
I've been able to reproduce it on the mac, steps:

1. open augury, click on router tree
1. close augury
1. open augury, click on router tree

![routes-render-error](https://cloud.githubusercontent.com/assets/439226/24008798/20515a16-0a49-11e7-80e9-006799615232.gif)

**Comment by stevenkampen** [comment]
@rajinder-yadav Got it!
