### ISSUE TITLE
Extra router-outlet getting displayed.

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#1035]
Augury: 1.4.0
Date: Wed, 22 Mar 2017 00:17:43 GMT
OS: Linux x86_64

Demo test application:

Using Guides Routes demo app.

Description of issue:

Seeing an extra router-outlet in Component Tree.

Angular version (required): 2.4.x

Steps to reproduce:

1. Use Routes demo app.
1. Open Augury.
1. Click on "Cities" button.

For CityComponent, two router-outlets are shown, there should only be one.

Additional details:

CityComponent uses lazy loaded routes.

![extra-router](https://cloud.githubusercontent.com/assets/439226/24176720/1ee95a5a-0e74-11e7-8a87-7106c4b259c8.png)

### city.compoent.ts

```js
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-city',
  template: `
    <h1>Cities</h1>
    <img src="https://augury.angular.io/images/camera.svg" width="20" height="20" align="center"> <a routerLink="city1" routerLinkActive="active">City 1</a>
    <a routerLink="city2" routerLinkActive="active">City 2</a>
    <a routerLink="city3" routerLinkActive="active">City 3</a>
    <router-outlet><router-outlet>
  `,
  styles: [`
    a.active {
      background-color: yellow;
    }
  `]
})
export class CityComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```

**Comment by riavalon** [comment]
Extra `router-outlet` is being rendered on page due to the `router-outlet` tag in the component template missing a proper ending tag. [PR has been opened on augury examples repo](https://github.com/rangle/augury-examples/issues/63).
