### ISSUE TITLE
Replace "Angular 2" references to just "Angular" across the tool and docs

### ISSUE THREAD

**Issue by olostan** [rangle/augury#1046]
Currently everywhere in documentation there is stated that Augury is tool "for debugging and profiling Angular 2 applications." ( https://augury.angular.io/ )

But with semantic versioning there is no sense to put "2". Also it can confuse people who are using Angular version 4 and above even if Augury will work seamlessly with them.

**Comment by igor-ka** [comment]
Hey @olostan thanks for pointing this out. I changed the description of the issue, and we will be making this change soon.
