### ISSUE TITLE
Changes to component properties don't work if the value is the same as the original.

### ISSUE THREAD

**Issue by stevenkampen** [rangle/augury#1050]
The frontend copy of the state is not updated, so any change to the component instance state only are applied if the value is different from the *original* value.

**Comment by stevenkampen** [comment]
@cdarken Actually I am not having any luck reproducing this. Any chance you have a public example lying of the issue?

**Comment by cdarken** [comment]
@stevenkampen sorry, not at the moment. btw, I've tested with angular 2.4.8, you think it might depend on the version?

**Comment by cdarken** [comment]
@stevenkampen To test I should follow the instructions [here](https://github.com/rangle/augury#building-and-installing-locally), right?
