### ISSUE TITLE
Component state not showing up

### ISSUE THREAD

**Issue by raydaim** [rangle/augury#1058]
Augury version (required): 1.5.0
Angular version (required): 4.0.0 / (also present in 4.0.1)
Date: 03/31/2017
OS: Windows 10 Build  14393.969/ Chrome Version 57.0.2987.98 (64-bit)

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
https://github.com/raydaim/AuguryIssue/

Description of issue:
-- Include (clipped) screenshot images if possible.
![000057](https://cloud.githubusercontent.com/assets/7352384/24552235/f843e92e-1625-11e7-999c-d51335d50cbd.png)
 
The component state section is not showing up in augury

**Comment by stevenkampen** [comment]
@raydaim Thanks for isolating your issue here. I'll look at it shortly.

**Comment by stevenkampen** [comment]
@raydaim It looks like this is fixed in Augury 1.6.0.

<img width="715" alt="screen shot 2017-04-05 at 11 10 13 am" src="https://cloud.githubusercontent.com/assets/898763/24698348/94783c78-19f0-11e7-943f-217d0e8df950.png">

**Comment by raydaim** [comment]
@stevenkampen yeah it is working perfectly Thank you so much !
