### ISSUE TITLE
Exception during NgModule config parsing with AoT apps

### ISSUE THREAD

**Issue by stevenkampen** [rangle/augury#1070]
@thaoula reported on #1063 that an exception occurs while initializing Augury for AoT apps.

![ddc9f05c-248a-11e7-9e09-6a177343f7f1](https://cloud.githubusercontent.com/assets/898763/25141826/0ef68e86-2465-11e7-9d49-dc5334710d1d.png)

**Comment by dansomething** [comment]
Is this possibly related to #733? I got the same error until I followed the readme to update angularCompilerOptions.debug in tsconfig.json.

**Comment by riavalon** [comment]
The error is cause because of this code in `src/backend/utils/parse-modules.ts`:

```typescript
const resolveNgModuleDecoratorConfig = (m) => {
  if (m.decorators) {
    return m.decorators.reduce((prev, curr, idx, decorators) =>
      prev ? prev : decorators[idx].type.prototype.toString() === '@NgModule' ?
        (decorators[idx].args || [])[0] : null, null);
  }

  return Reflect.getMetadata('annotations', m).find(decorator => decorator.toString() === '@NgModule');  // problem occurs on this line
};
```
When an app is compiled with AoT,  `Reflect.getMetadata(...)` will return undefined. I believe this is because the metadata files are put into `metadata.json` files when the app is compiled in AoT, though I'm not sure how we would go about grabbing that metadata in augury.

**Comment by stevenkampen** [comment]
@riavalon I made a change just yesterday to stop that undefined reference error, so at least that won't happen anymore :)

https://github.com/rangle/augury/pull/1134/files#diff-d55af29576cfd559bea03764b5c7fc9bR23

**Comment by riavalon** [comment]
Great, sounds good @stevenkampen 

We talked about this one a bit more offline: As there is no way currently for us to get access to metadata when an app is compiled in AoT, we're going to instead show an informative error message in the NgModules tab and improve the documentation around it.
