### ISSUE TITLE
"Unhandled Promise rejection: Cannot read property 'injector' of null" CONSOLE ERROR JUST AFTER AUGURY INSTALLATION

### ISSUE THREAD

**Issue by Megamind2301** [rangle/augury#1071]
Augury version (required):1.6.0
Angular version (required):4.0.1
Date:19/4/2017
OS:Ubuntu

Description of issue:
Augury is not working due to this error in console. This error comes only after I add augury to the list of extensions.

![image](https://cloud.githubusercontent.com/assets/19911101/25180451/a81f1314-252b-11e7-88cf-306bf10b2812.png)

**Comment by stevenkampen** [comment]
@Megamind2301 Is there code available that I can recreate this with? The error is a little bewildering  because I believe this means `getAllAngularRootElements()` is returning a null root, which shouldn't happen as far as I know.

**Comment by Megamind2301** [comment]
IT IS confusing. 
- Everything works fine even with this error. 
- When I uninstall augury, this error disappears. 
- Augury is not getting receiving the boot file I guess.

I need to fix this urgently. Any workaround would work just fine (if there is any).

**Comment by stevenkampen** [comment]
@Megamind2301 If you can recreate it in a simple form and publish some code I'll look at it ASAP. Otherwise I'm going to be shooting in the dark trying to make it happen.

**Comment by laserus** [comment]
I have the same error. project is angular4 with --prod and --aot (from agnular/cli). But the error comes not from Zone.js but from polyfills.js

**Comment by stevenkampen** [comment]
@Megamind2301 @laserus @cpeisert Ok, I've found an issue where if the application is calling `enableProdMode`, then Augury will still try to initialize (which it usually wouldn't, because it can't debug an application in production mode). Can you see if this is what's happening in your cases? There may be a separate AoT issue which I'm looking into now.

**Comment by laserus** [comment]
@stevenkampen for non-prod build the Augury works fine. Probably, you need some message into console that catches this exception.

**Comment by stevenkampen** [comment]
@laserus There is a message usually, but something has changed in Angular so that our logic to read that production/debug flag is now incorrect. We're chasing up a fix for it though so it should be back to normal behaviour soon.

**Comment by cpeisert** [comment]
@stevenkampen The Augury error is no longer appearing in production mode. Thank you for your help.

**Comment by stevenkampen** [comment]
Closing as fixed.
