### ISSUE TITLE
"This application is not an Angular application"

### ISSUE THREAD

**Issue by kittycatbytes** [rangle/augury#1089]
Augury version (required): 1.7.0
Angular version (required): 2.4.8
Date: 5/3/2017
OS: Windows

Description of issue:
When testing my angular app when I launch Augury I get the error "This application is not an Angular application"

Steps to reproduce:

1. Created Asp.Net empty web app
2. Scaffolded Fountain (Yeoman) into it with Angular 2 option
3. Started created various components and services
4. gulp serve, launched browser, opened Augury and the error appears

**Comment by gnibeux** [comment]
me too ,any help,thank you!!!!!!

**Comment by goatcube** [comment]
I'm having the same issue with Angular 4.1.0

**Comment by winnemucca** [comment]
If/When a fix or code issue is found that causes this please share.  I have no idea what the problem is with this.

**Comment by bheda91** [comment]
I got this error, (May be useful for you)

**Unhandled Promise rejection: Cannot read property 'injector' of null** ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'injector' of null
    at bind (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9628:14)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9658:71
    at Array.forEach (native)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9658:38
    at checkDebug (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9647:10)
    at resubscribe (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9652:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9664:94
    at t.invoke (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:9799)
    at e.run (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:5011)
    at http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:2128
    at t.invokeTask (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:10483)
    at e.runTask (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:5660)
    at a (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:667)
    at invoke (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:11501) TypeError: Cannot read property 'injector' of null
    at bind (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9628:14)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9658:71
    at Array.forEach (native)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9658:38
    at checkDebug (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9647:10)
    at resubscribe (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9652:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9664:94
    at t.invoke (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:9799)
    at e.run (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:5011)
    at http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:2128
    at t.invokeTask (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:10483)
    at e.runTask (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:5660)
    at a (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:667)
    at invoke (http://localhost:8080/popgui/home/polyfills.f8e6258404ae34860bd1.bundle.js:43:11501)

**Comment by igor-ka** [comment]
Hey @kittycatbytes would you be able to create a demo repo so that we can reproduce this problem?

**Comment by kittycatbytes** [comment]
I'm so sorry, I was able to fix it but I cannot remember exactly what I did - it was a while ago now.  Essentially you can get this error it seems if you have not set up the basics correctly.  I wish I had captured more info on this when I resolved it.  Hopefully one of the other users experiencing this issue can shed more light.

**Comment by winnemucca** [comment]
@kittycatbytes  when referencing the error do you mean the error that @bheda91 has or the error that this is not an angular application?  I am inheriting a project in the middle of an upgrade.  What basics should I go over to fix this?

**Comment by sss4r** [comment]
This began happening to me today. If you close the dev tools and reopen, the extension resumes working correctly, but it quickly breaks again. Let me know if I can provide any info that would be helpful.

**Comment by mitchellzen** [comment]
Having same issue. Just installed Augury. Does not detect an angular app.

**Comment by stevenkampen** [comment]
@mitchellzen @sss4r Any chance you have a public repo where this happens? I'll look into immediately if I can reproduce it.

**Comment by vajnorcan** [comment]
Mine detected the app for the first time, but won't recognise it after a reload.

**Comment by winnemucca** [comment]
Occasionally when I reload and try to get Augury to reload I also see this 

> Object {message: "The message port closed before a reponse was received."}message: "The message port closed before a reponse was received."__proto__: Object
(anonymous) @ content-script.js:5099


Can't help but wonder if this is part of the problem to Augury not identifying the application as Angular.

**Comment by Francute** [comment]
This is happening to me too. [Probably you don't need to download this, but i will add the oportunity] One simple way to reproduce it in [this repository](https://github.com/Francute/tour-of-heroes-augury) is: 

- Make a ng-serve (I'm using Angular Cli)
- Delete the line 28 in _src/app/modulos/principal.module.ts_ `DecimalesPipe,`
- This will fire in Angular an error because there are files which depends of the removed line. Concurrently, Augury shows **This application is not an Angular application**.
- Remove the only dependency. Line 8 in _src/app/vistas/heroe/detalles.component.html_
- Application refresh and continues working normally, but Augury never get refreshed, so it keeps the same message. 

If this is your case, probably, you are making changes in multiple files at the same time while application keep refreshing. So, in one moment between those changes, angular could fire an error, Augury shows the message, and the application make a last refresh after the last change you do. But Augury doesn't refresh again. 

And makes sense because the proposed solution of refreshing Augury works.

Augury version: 1.14.0 
Angular version: 4.3.1 (Yes, i know it's expected to work with angular 2, but i didn't know if this is your exact problem or not...)
Chrome version: 59.0.3071.115 (Build oficial) (64 bits)
OS: It says Ubuntu 16.10 but i'm using Xubuntu.

I hope this helps.

**Comment by Joshmamroud** [comment]
I was having the same issues with Chrome Canary. Updating Chrome seems to have fixed the issue. Issue was with Version 62.0.3175.2 now works on Version 62.0.3175.3

I hope this helps.

**Comment by bastienJS** [comment]
Updating to chrome dev 62.0.3175.3 did not help me on win10 64bit. Even after restart of the browser!

**Comment by fixako** [comment]
Same problem here. I use linux.

**Comment by kod88vn** [comment]
I had the same issue for a bit on my Mac. Then I killed Chrome instance and open another one. Problem solved

**Comment by sebastianslutzky** [comment]
is there any fix for this? on a Mac + Chrome 61.0.3163.100, I need to open new instances constantly. The plugin is only usable once per tab instance

**Comment by mohitook** [comment]
there could be some problems with nested modules (lazy loaded ones)... I've modified my application to lazyload the modules and now agury doesnt work...

**Comment by mikek65** [comment]
Doesn't work at all with my Angular 1 application.  I've never used Augury before so my first impression is not good.

**Comment by LosD** [comment]
@mikek65 It's not made for AngularJS (1), only for Angular (2+).

**Comment by mikek65** [comment]
I suspected as much, but I did not see anything about that in the docs anywhere.  I feel like these days many just assume that all Angular development is happening in 2+, which makes no sense to me.

**Comment by LosD** [comment]
@mikek65 It's literally in the description of the project: "Augury is a Google Chrome Dev Tools extension for debugging **Angular 2+** applications."

And again in the very next section: "Augury only works with Angular 2+ applications."

**Comment by mikek65** [comment]
That's a fair point, it's on the main page.  Which I never saw.  I went straight to the Guides, after downloading it from the Chrome store.  There is no mention of 2+ in either of those places.

**Comment by LosD** [comment]
... Which is definitely also a fair point. I tend to forget that not everyone uses Github as a primary search engine 😊

**Comment by LetHerRip** [comment]
Solution for "This application is not an Angular application"
* copy url
* open new tab in the Chrome browser
* paste url
* close tab with the error if you want
When error occur again, repeat steps above

**Comment by abalad** [comment]
@LetHerRip THX

**Comment by santiago-elustondo** [comment]
Anyone who is still having this issue: can you try using the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) ?
Does the problem persist there, or is it resolved for you?

**Comment by AllanD** [comment]
I have this issue on an angular 1.6.4 app.

**Comment by andrewthauer** [comment]
@AllanD - I'm sorry but Augury is for Angular 2+ applications only and does not work with AngularJS. There are a few similar DevTools for AngularJS you could try out instead.
