### ISSUE TITLE
Feature request: custom name for pathless componentless route

### ISSUE THREAD

**Issue by Aides359** [rangle/augury#1101]
# Feature request:

## Description
Ability to provide a custom name for pathless componentless routes.

## Motivation
It is rather common to have route definitions that contain `path: ''` and don't define a component but only child routes to group routes together and apply guards to them etc. (see https://angular.io/docs/ts/latest/guide/router.html#!#add-an-admin-feature-module)

Those routes are currently displayed as 'no-route-name' (https://github.com/rangle/augury/blob/dev/src/backend/utils/parse-router.ts#L79), however it would be nice to be able to set a custom name to be displayed.

## Implementation
This could possible be as easy as defining an additional property on the route object like
```
{
   name: 'guarded routes' (or _auguryName or something to avoid conflicts with future angular releases)
   path: '',
   canActivate: [someGuard],
   children: [ /* ... */ ],
}
```

I could probably provide a PR if this is a wanted feature.

**Comment by igor-ka** [comment]
Hello @Aides359 doing something like the above would require to make change to angular's router and not just augury. Our goal is not to have any Augury specific logic in Angular's codebase. There might be other reasons for Angular's router to have the parameter you mentioned above, in which case we will be happy to leverage that information, but this is something to ask from the angular team.

I am closing this issue for now, but let me know if I am missing something and we can take this discussion further.
