### ISSUE TITLE
Performance issues for large numbers of components

### ISSUE THREAD

**Issue by SethDavenport** [rangle/augury#113]
Steps to reproduce:

1. install batarangle
2. run the example app (`examples/todo-mvc-example`)
3. make 30 or 40 tasks
4. open batarangle

At this point the browser CPU usage goes up quite a bit and the browser becomes sluggish.

**Comment by vanessayuenn** [comment]
possible solution:
- fixing properties and name rendering issue
- check rendering on selected node

**Comment by sumitarora** [comment]
This is done and working fine with new performance optimization
* Removing mutation observer
* Deferring the rendering after updates
* Not rendering few angular directives
