### ISSUE TITLE
Feature request: Firefox support

### ISSUE THREAD

**Issue by miltador** [rangle/augury#1150]
It would be awesome to see this extension for Firefox browser. As Firefox supports [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) API, I believe it won't be difficult to make it working on Firefox. I saw React Dev Tools extension on Firefox, Angular community is now missing this one for Firefox.

**Comment by captainbrosset** [comment]
Firefox now supports a wide range of WebExtension APIs, including DevTools-related APIs. This means that without changing much of the extension's code, it should just work on Firefox.

I tried running it in Firefox and got this:

<img width="1021" alt="capture" src="https://cloud.githubusercontent.com/assets/1152698/26823321/88c16bb4-4aad-11e7-8408-83562e120336.PNG">

Not bad for a first test, at least the panel appears and has some content.
There's an error in the console though: `Augury initialization has failed <unavailable>  content-script.js:5711`.

Looking into it more, the `<unavailable>` bit is actually `Error: Could not establish connection. Receiving end does not exist.`

CC @clarkbw who has been working recently on helping other extensions like react, redux, ember, vuejs become fully Firefox compatible. Maybe he can help here too.

**Comment by clarkbw** [comment]
I'm seeing some intermittent issues here and I don't know Angular well enough to be able to traverse the code.  It seems to drop the connection at times and others it works.  I can pair with someone to get them through the Firefox parts but I'll need help with the rest.

**Comment by igor-ka** [comment]
Hey @captainbrosset and @clarkbw we will be happy with that. We are thinking of a potential refactor to support different shells easier and would appreciate help and/or input on that.

Can we chat over [Slack](https://augury-slack.herokuapp.com/)?

**Comment by clarkbw** [comment]
> Can we chat over Slack?

Sounds good!  I've joined the Slack as @clarkbw 

Lets try to chat soon, ping me when you get a chance @igor-ka

**Comment by digitarald** [comment]
Hi @igor-ka , I am taking over this effort from @clarkbw , working with @captainbrosset . To kick things off I joined Slack and will ping you.

**Comment by adityamenon** [comment]
Hello all, I do not see anything on the README or an Addon on Firefox yet. Which GitHub issue are we tracking the progress for this on?

**Comment by karlos1337** [comment]
Something about this?

**Comment by Invis1ble** [comment]
bump

**Comment by andrewthauer** [comment]
Firefox support is definitely on the roadmap. but at this point I couldn't give an exact timeline. As far as I know, there are no open PR's related to Firefox support.

There has been some encouraging initial success getting Augury running in Firefox (debug mode) so hopefully the effort is relatively small.

**Comment by santiago-elustondo** [comment]
Howdy! Please see progress on this PR: https://github.com/rangle/augury/pull/1268
We hope to be able to release as a FireFox add-on very soon.

**Comment by andrewthauer** [comment]
We will also need to ensure the following are updated / checked before publishing:

- Ensure all UI messaging (labels, etc.) are not making specific reference to Chrome
- Update the README accordingly as well
- README reference npm scripts which have changed

**Comment by callahad** [comment]
Looks like Augury is now live on AMO: https://addons.mozilla.org/en-US/firefox/addon/angular-augury/

🎉

**Comment by andrewthauer** [comment]
It is indeed. It's currently marked as experimental since it's based on the current `dev` branch. The official release should come very soon.

**Comment by andreicristianpetcu** [comment]
@callahad It is not online. I cannot see it both with your link and by searching it :(

**Comment by andrewthauer** [comment]
The add-on was available for a couple of days, but is now disabled based on some warnings encountered in an add-on review by Mozilla. These will need to be addressed before we can re-submit the add-on.

NOTE: This was just an experimental release (not official), so please be patient while we work through the submission & approval process.

**Comment by andreicristianpetcu** [comment]
If you are using my unofficial Firefox build know that it breaks up XML formatting in Firefox :(

Cheer up! I fixed it with a PR and [another unofficial build](https://github.com/andreicristianpetcu/augury/releases/download/v1.16.0.2/augury-1.16.0.2-an.fx.xpi) :)

**Comment by andrewthauer** [comment]
UPDATE: We are in the process of working through some of the issues that were flagged during the AMO review process. Unfortunately, some of these are not completely straight forward to address due to various factors. I'm hopeful we can work through them in a timely matter, but at this point I can't give an ETA on when that might be exactly.

**Comment by andreicristianpetcu** [comment]
@andrewthauer I know Firefox has higher security/privacy standards and publishing a Chrome extension in addons.mozilla.org takes some time. No rush.

I will keep reporting bugs, sending patches and publishing unofficial Firefox builds for whoever is interested.

**Comment by andreicristianpetcu** [comment]
I'm having some performance issues with Augury in Firefox :( I [reported the issue here](https://github.com/rangle/augury/issues/1291). I used https://perf-html.io to record a performance profile for whoever is interested.

**Comment by pickfire** [comment]
Augury is now in [firefox addons](https://addons.mozilla.org/en-US/firefox/addon/angular-augury/) but it keeps appearing in the developer panel even though the webapp is not written in angular.

**Comment by santiago-elustondo** [comment]
@pickfire, the FireFox add on is still very much in beta, and we are working through various quirks.
That said, the Augury tab should always be present in the dev tools, regardless of whether the app is Angular or not. 
The tab should display a message saying that Angular was not detected in the page. If this is not occurring, then you have identified a bug. Please create an issue with a screenshot, and we'll address it.

**Comment by andrewthauer** [comment]
Firefox extension has been available for a while now.
