### ISSUE TITLE
s

### ISSUE THREAD

**Issue by hbarpitgupta** [rangle/augury#1152]
Augury: 1.10.0
Date: Fri, 02 Jun 2017 14:29:34 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by stevenkampen** [comment]
@hbarpitgupta If this was meant to be an issue, please try again. Thanks!
