### ISSUE TITLE
Why does Augury need to inject Google Tag Manager into every NG2+ site?

### ISSUE THREAD

**Issue by MrShaneH** [rangle/augury#1168]
Augury version (required): 1.12.0
Angular version (required): 2+

More of a question than an issue. As the title asks, why is google tag manager injected into every Angular site I visit?

**Comment by charpeni** [comment]
I was also surprised to saw another Google Tag Manager injected in my app, after some search it's all described in #1005.

**Comment by JinSY** [comment]
This was an oversight on our part. Will be addressed shortly

**Comment by stevenkampen** [comment]
@MrShaneH The fix for this was just merged (in #1170) and will be released right now. You should automatically get the update within an hour.
