### ISSUE TITLE
This application is not an Angular application - need to restart developer tools

### ISSUE THREAD

**Issue by quin61** [rangle/augury#1173]
Augury version (required): 1.13.0
Angular version (required): 2.2.4
Date:
OS: Windows

When developer tools is already open when page loads I get that message. 
Everything works if I close and open developer tools. 

I am not sure if it's just me but if not - it sure would be nice to fix this or just add some refresh button.

Similar thing was already discussed here: 
https://github.com/rangle/augury/issues/856

**Comment by reflog** [comment]
Happens on every live-reload of angular-cli

**Comment by reflog** [comment]
#1212 doesn't fix this at all :(
