### ISSUE TITLE
How do you set value for variable of complex type (object)?

### ISSUE THREAD

**Issue by slavafomin** [rangle/augury#1177]
Hello!

Thank you for this great extension!

However, I have a property on the "state" pane which is set to some `Error` instance. How do I set it to e.g. `undefined`? I can change value of simple types, like strings and booleans, but I can't change value for complex types.

Thanks!

**Comment by stevenkampen** [comment]
@slavafomin At the moment this is not possible, but it does seem like something that should be possible. @igor-ka @sumitarora Thoughts?

**Comment by igor-ka** [comment]
Hey @slavafomin I think we need a bit of improvement when it comes to modifying the values of the state objects. We will need to groom this issues a bit further but I will add this to our feature backlog for now.

**Comment by slavafomin** [comment]
Thank you for your valuable work :+1:
