### ISSUE TITLE
Can not inspect the components like MdMenu of material2

### ISSUE THREAD

**Issue by e-cloud** [rangle/augury#1190]
Augury version (required): 1.13.0
Angular version (required): 4.1.0
Date: 2017-6-12
OS: Ubuntu 17.04

Demo test application:

https://plnkr.co/edit/sKibSskmvzcUB9XOEZP1?p=preview

download the code and try it

Description of issue:

You can't inspect or find overlay-related components of materail2

Additional details:
This may be caused by the implementation of **overlayed** components. Material2 places those components inside a standalone place out of application root component.

**Comment by stevenkampen** [comment]
@e-cloud Thank you for the report and demo code. We'll look at this shortly.

**Comment by riavalon** [comment]
This is indeed because Material places components (such as the dialog component) outside of the root node, nested in a few overlay divs. Unfortunately, we cannot grab those components at this point.

**Comment by andrewthauer** [comment]
Created consolidated issue #1380 to track this
