### ISSUE TITLE
Can't see state tab in properties

### ISSUE THREAD

**Issue by XardoniK** [rangle/augury#1198]
Augury: 1.14.0
Date: Tue, 13 Jun 2017 10:07:57 GMT
OS: Win10 x64

Description of issue:
I can't see State tab(with data of exist angular app) when I click AppComponent.

![image](https://user-images.githubusercontent.com/9059223/27077680-2f793dfa-5031-11e7-8ee5-7add2e85ee28.png)

Angular version (required): 4.1.3/4.2.2

**Comment by rahil051** [comment]
Why closed the issue ? Is it resolved ? Because I am having the same with release 1.14.0

**Comment by XardoniK** [comment]
I reinstalled and work again. Augury sometimes works weird but reopen developer console, reinstall plugin or reopen browser can help
