### ISSUE TITLE
Change angular version colour to "augury yellow" in dark mode for readability

### ISSUE THREAD

**Issue by janpio** [rangle/augury#1200]
Augury version (required): 1.14.0
Angular version (required): 4.1.3
OS: Windows 10

![blue-on-black](https://user-images.githubusercontent.com/183673/27136971-f05d29a0-511c-11e7-8520-7cd9b4e509c9.PNG)

Pretty unreadable.

**Comment by igor-ka** [comment]
@janpio we will change the colour to Augury Yellow for better readability. I will change the title of this issue to reflect that. Thank you for pointing this out.

**Comment by sumitarora** [comment]
@igor-ka working on that.
