### ISSUE TITLE
Augury not recognising Angular app when using ngUpgrade

### ISSUE THREAD

**Issue by kucharskimaciej** [rangle/augury#1205]
Augury version (required): 1.14.0
Angular version (required): 4.2.2 (with ngUpgrade)
Date: 18/06/17
OS: macOS Sierra

Recently upgraded my AngularJS app to Angular by following the [upgrade guide](https://angular.io/guide/upgrade). The upgrade worked well, but I can't get the extension to recognize the application as an Angular app:
![screen shot 2017-06-18 at 02 05 08](https://user-images.githubusercontent.com/9625090/27257087-ae22f064-53ca-11e7-8a5b-c7b599771e99.png)

The bootstrapping code is fairly standard:
```
// import polyfills
import './ng2polyfills';

import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {Ng2AppModule} from './app.module';

platformBrowserDynamic().bootstrapModule(Ng2AppModule);
```

I've checked the Augury code, and it seems that the `isAngular` function depends on the presence of `getAllAngularTestabilities` and `getAllAngularRootElements`. Both are undefined when I type them in the browser's console. However, I'm able to access `ng` and `ng.probe` just fine.

Did I miss something in the setup? There's not much info on the internet, most of googling shows old issues with Angular rc versions.

**Comment by igor-ka** [comment]
We are already investigating this case under a duplicate issue #680
