### ISSUE TITLE
Cannot see contents of Map Collection Types

### ISSUE THREAD

**Issue by AlDrag** [rangle/augury#1218]
Augury version (required): 1.14.0
Angular version (required): 4.2.5
Date: 10 - July - 2017
OS: OSX 10.12.5

In a component, create a class variable of type Map and you are unable to view its contents with Augury in State Properties tab.

In the screenshot below, you can see the contents of the Map 'virtuallySelectedRows'

![screen shot 2017-07-10 at 3 21 52 pm](https://user-images.githubusercontent.com/5018493/28001866-4adcfe2a-6584-11e7-960c-56659631c95e.png)

**Comment by andrewthauer** [comment]
This seems to be fixed.

![image](https://user-images.githubusercontent.com/6507159/48105755-b807cc00-e206-11e8-88c3-ad7c06891f67.png)
