### ISSUE TITLE
Ionic3 Angular4

### ISSUE THREAD

**Issue by 111rohittiwari** [rangle/augury#1220]
Augury: 1.14.0
Date: Thu, 13 Jul 2017 17:41:08 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by sumitarora** [comment]
Closing as no description provided. Please reopen the issue with detailed description.
