### ISSUE TITLE
e333

### ISSUE THREAD

**Issue by lionmof** [rangle/augury#1221]
Augury: 1.14.0
Date: Sat, 15 Jul 2017 20:04:09 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by e-cloud** [comment]
@lionmof , hey man, rubbish issue is really annoying for someone watching this repo. How could you post such an issue!!!
