### ISSUE TITLE
iCanyon

### ISSUE THREAD

**Issue by irontroter** [rangle/augury#1222]
Augury: 1.14.0
Date: Mon, 24 Jul 2017 07:55:29 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by arafeek** [comment]
Closing this as it has no relevant information on an actual issue or steps to reproduce.
