### ISSUE TITLE
When json data is relatively big modal with debug data breaks

### ISSUE THREAD

**Issue by rodusa** [rangle/augury#1224]
Augury version (1.14.0):
Angular version (4.0):
Date:08-01-2017
OS:Mac

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot 
<img width="1396" alt="screen shot 2017-08-01 at 6 34 27 pm" src="https://user-images.githubusercontent.com/1469472/28848134-3e689b0c-76e8-11e7-9ba2-b85d94d8e06e.png">
images if possible.

Steps to reproduce:

1. insert debugger on json variable
2. the modal size height is shortened and is not possible to view anything
3.

Additional details:

**Comment by arafeek** [comment]
Closing as this doesn't appear to actually be an augury issue but rather one with the chrome debugger itself.
