### ISSUE TITLE
Feature request/debate: Graphical dependency tree

### ISSUE THREAD

**Issue by kyr0** [rangle/augury#1225]
Augury version (required): 1.14.0
Angular version (required): 4.3.1
Date: 02.08.2017
OS: Mac OS X El Capitan 10.11.6

Description of issue:

Augury already features a very nice "NgModules" dependency analyzer based on a list-UI. 

While refactoring a large Angular 2 codebase I realized that I would profit alot from a chart view like http://angularjs-graph.org/.

I would like to discuss this idea together with you. What is your opinion on that? Is there anything already planned? Would you like to see community members implementing something like that? And if so -- what charting library would you like to see being used in such an implementation?

Thanks and best,
Aron

**Comment by andrewthauer** [comment]
Recommend looking at [Compodoc](https://compodoc.github.io/) for this sort of thing.
