### ISSUE TITLE
how to debug the errors by using the angury

### ISSUE THREAD

**Issue by Narayanaswamyv3650** [rangle/augury#1226]
Augury: 1.14.0
Date: Thu, 03 Aug 2017 11:13:44 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by e-cloud** [comment]
@sumitarora do you guys recently get on someone's nerves? There is are not just a few pointless issue created. It's annoying and meaningless.

**Comment by arafeek** [comment]
Closing this as it has no relevant information on an actual issue or steps to reproduce.
