### ISSUE TITLE
Some websites not loading when augury is installed on chrome.

### ISSUE THREAD

**Issue by jasekiw** [rangle/augury#1229]
Augury version (required): 1.14.0
Angular version (required): Not applicable
Date: 08/18/2017
OS: Windows 10

At first I thought the DNS was not resolving but I realized that the entire tab froze up. This has happened on a few of the sites that I have visited but I only have the one recorded below. After I remove augury the problem goes away. 

I tested this on my home computer and my office computer with the same result. I also uninstalled the extension completely, tested it, reinstalled it, and tested it again restarting chrome between each step. The same result. I hope that others can reproduce this issue. 

Steps to reproduce:

1. Go to https://www.ius.edu/
2. Open the Chrome Developer Console and click the network tab
3. Make sure cache is turned off and do a hard reload at least 5 times. For some reason one hard reload does not work.
4. The website tab will freeze up.  You cannot do anything but open up task manager to kill the tab.
5. If you disable augury this does not happen. Try again with augury uninstalled and the issue will dissappear

If I run into other sites I will post them here to figure out what it the common denominator.

**Comment by andrewthauer** [comment]
@jasekiw - Are you still experiencing this issue with the latest version of augury?

**Comment by jasekiw** [comment]
@andrewthauer The issue seems to have gone away! What was the fix if you don't mind me asking?

**Comment by andrewthauer** [comment]
@jasekiw - I'm glad this issue is now resolved. I couldn't say specifically what fixed this issue, but we've fixed some previously hard to reproduce issues recently (3rd party library conflicts, etc), so I figured I'd see if this was also resolved. Apparently it was.
