### ISSUE TITLE
Augury says 'No component selected'  in Angular project.

### ISSUE THREAD

**Issue by vugar005** [rangle/augury#1236]
Hi.I have been using Augury in many different Angular projects and Augury worked well. But in this project Augury states 'No component selected'. It seems Augury cannot identify my components. Please help me to resolve this problem. I attached project file here. To run this project on browser paste this link:
localhost:4200/#/?token=e0781f79719644bd8639b0e4e2fe4c0bd30646fb038a429f866886f727b3ef04

Download link for project: https://1drv.ms/u/s!AgQasXqSLzgklwRpr1zSQyzMO135

I updated angular-cli and Augury but problem keeps as it is. I see my components in Router Tree but not in Component Tree.

**Comment by arafeek** [comment]
Thanks for your feedback @vugar005. Would you be able to link to some hosted example code that displays the issue (eg. on www.plunkr.co). Please understand that I am just a bit weary of downloading and executing unknown zip files. Thanks.

**Comment by vugar005** [comment]
OK @arafeek . I would try to upload the project soon . It would took time because projects consists of many components.

**Comment by GNSSYSTEMS-tg** [comment]
I've got the same issue. Is this fixed by now? Unfortunately, I'm unable to open up the source code on our project...

**Comment by mcelotti** [comment]
same here, I'm using augury 1.14.0, angular 5.0.3, Ubuntu 16.04.3

**Comment by vugar005** [comment]
The problem is solved but I am not sure how. After I run project in internet explorer ,there were some errors caught, After fixing them and running in chrome ,the augury start to work as expected. Seems that augury also caught problems but not showing. Not sure it is because of it.

**Comment by vugar005** [comment]
@mcelotti @GNSSYSTEMS-tg  . I remember also a change I made in project. 
In index.html please change` <base href="/">` to
`<base href="./">`
Then restart chrome and let me know whether the problem is solved.

**Comment by mcelotti** [comment]
@vugar005 I think my problem was related to a full chrome restart. Today, without changes, it works as expected.
I did not try the "<base href" since it's working without that tag.
Thank you.

**Comment by andrewthauer** [comment]
@vugar005 - Please try the latest version of Augury.

**Comment by vugar005** [comment]
@andrewthauer . it was latest version. Probably because of either chrome issue or base href.
Thanks

**Comment by andrewthauer** [comment]
@vugar005 - I believe @santiago-elustondo just released a [canary build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en-US) that addresses some of the state issues we have been seeing. Do you mind installing that version and checking again?

**Comment by vugar005** [comment]
@andrewthauer . it was actually long before and I fixed it somehow. Probably it was because of chrome version or augury.

**Comment by andrewthauer** [comment]
Please reopen if this is still occurring.
