### ISSUE TITLE
Feature request: Visual Change Detection Tree

### ISSUE THREAD

**Issue by AlDrag** [rangle/augury#1237]
Augury version (required): 1.14.0
Angular version (required): 4.3.0
Date: 30/08/2017
OS: Mac OSX Sierra

Description of issue:

It would be really cool if we could have some sort visual tree that shows Change Detection happening in real time. This would allow you to see frequency of change detection throughout your app and what is causing it. Is this even possible?

Thanks

**Comment by alan-bio** [comment]
@arafeek It could be cool to possibly be able to visually see your components as a tree (sort of like you can in Augury right now) but visually show change detection. Maybe you could step through the state/history of it so you can see what triggers change detection and/or see what change detection touches based on your OnPush components etc.

Maybe this idea is ultimately less 'useful' and more just visually appealing as I can obviously go through the call stack to find out what is triggering change detection.

**Comment by AlDrag** [comment]
@arafeek It could be cool to possibly be able to visually see your components as a tree (sort of like you can in Augury right now) but visually show change detection. Maybe you could step through the state/history of it so you can see what triggers change detection and/or see what change detection touches based on your OnPush components etc.

Maybe this idea is ultimately less 'useful' and more just visually appealing as I can obviously go through the call stack to find out what is triggering change detection.

**Comment by andrewthauer** [comment]
This sort of feature(s) is covered by https://github.com/rangle/augury-labs.
