### ISSUE TITLE
State is not shown for lazy routed components.

### ISSUE THREAD

**Issue by MazherUddin** [rangle/augury#1239]
Augury version (required):latest
Angular version (required):4.3.6
Date:Sep 9, 2017
OS:Windows 10

Description of issue:
State is not shown for lazy routed components. I can only view or modify properties of the components that are not routed.

Steps to reproduce:

1. Route to any component with some properties.
2. Click the component in angury.
3. The state of the properties are not displayed.

**Comment by santiago-elustondo** [comment]
Canary merged with master as official 1.18 release. 
Please reopen if this issue persists.
