### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by LinetTorrico** [rangle/augury#1241]
Augury: 1.14.0
Date: Tue, 12 Sep 2017 01:11:34 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by arafeek** [comment]
closing as irrelevant
