### ISSUE TITLE
App doesn't respond

### ISSUE THREAD

**Issue by akshaybabloo** [rangle/augury#1242]
Augury version (required): 1.14
Date: 19/09/2017
OS: Windows 10

The app doesn't seem to respond, no error message nothing. Just stuck.

**Comment by JasonGoemaat** [comment]
Ditto here 16 days later.  Locks up my chrome dev tools and I have to close them and re-open them to access other tabs.

**Comment by aGoncharuks** [comment]
I confirm there is a bug. To reproduce it you should open your Chrome on external monitor and Augury is stuck. In order to get working you should drag Chrome to you main PC monitor and refresh the page. Very annoying, hope you will be able to fix this one.

**Comment by Matmo10** [comment]
When I was reading this thread I thought "there's no way this will fix it", but sure enough, dragging the chrome window to my MBP Retina's screen instead of my external monitor and refreshing solved the issue.

**Comment by akshaybabloo** [comment]
Also, I guess there seems to be a video drivers issue in Windows. Scaling between different screen size is causing problems with chrome widgets.

**Comment by andrewthauer** [comment]
Please verify this is still an issue with the latest release.

**Comment by akshaybabloo** [comment]
@andrewthauer All good. Thanks.
