### ISSUE TITLE
Can Augury be used outside Chrome?

### ISSUE THREAD

**Issue by mi5ha** [rangle/augury#1244]
Hi there,

We are writing some Angular tools, and wondering if Augury capabilities could be used outside Chrome?

For example if we could get Component tree or Routes tree for a given project from a command line?

Cheers,
Misha

**Comment by arafeek** [comment]
Hi @mi5ha. Currently Augury exists only as a chrome extension as its [Architecture](https://augury.angular.io/pages/guides/architecture.html) relies heavily on this fact.

**Comment by andrewthauer** [comment]
The [Augury Labs](https://github.com/rangle/augury-labs/) project runs outside chrome.
