### ISSUE TITLE
not identifying dynamically added elements

### ISSUE THREAD

**Issue by praveens96** [rangle/augury#1248]
Augury: 1.14.0
Date: Sun, 15 Oct 2017 08:41:03 GMT
OS: MacIntel

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
- trying to see the properties of the virtual keyboard at https://ngx-material-keyboard.github.io/demo/. its not showing the keyboard properties in anguary.
<img width="1440" alt="screen shot 2017-10-15 at 2 12 20 pm" src="https://user-images.githubusercontent.com/8864727/31583165-ec57f9b0-b1b2-11e7-9c55-335931efd361.png">

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by e-schultz** [comment]
* clone: https://github.com/ngx-material-keyboard/core
* npm install
* npm run start:demo  

Augury does not display the keyboard, wondering if it is related to how the CdkPortal from Material2 attaches things to the application

**Comment by andrewthauer** [comment]
Created consolidated issue #1380 to track this
