### ISSUE TITLE
addEventListener causes my browser fronzen

### ISSUE THREAD

**Issue by SteveZheng-BSFT** [rangle/augury#1249]
Augury: 1.14.0
Date: Mon, 23 Oct 2017 18:16:54 GMT
OS: MacIntel

code:
private createMessageHandler(validOrigin) {
        this.messageHandler = event => {
            if (event.origin === validOrigin) {
                this.receiveResponse(event.data);
            } else {
                log.warn(this, `Message from unknown domain (${event}) has been ignored`);
            }
        };
    }

    private addEventFrameListener(validOrigin) {
        if (!this.messageHandler) {
            this.createMessageHandler(validOrigin);
            window.addEventListener('message', this.messageHandler, false);
        }
    }

Description of issue:
-- background: I have above code work with iframe to retrieve some status, and recently our backend stop working so this code always goes to 'else' clause. 
-- problem: with Augury enabled, this code is logging this warning message forever, but works fine once i disable Augury
<img width="1116" alt="screen shot 2017-10-23 at 2 04 18 pm" src="https://user-images.githubusercontent.com/23032993/31906521-4acd5a88-b7ff-11e7-8eba-7d4b848253dc.png">

Angular version (required): 4.3.5

Steps to reproduce:

1. once i created the listener
2.
3.

Additional details:

**Comment by andrewthauer** [comment]
@SteveZheng-BSFT - Please check if this is still occurring with the latest version of Augury. If otherwise, please re-open with some additional details.
