### ISSUE TITLE
It does not show the properties of injected services on a component.

### ISSUE THREAD

**Issue by kepoddx** [rangle/augury#1251]
Augury: 1.14.0
Date: Sun, 19 Nov 2017 23:23:41 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by sumitarora** [comment]
Please add more details and reopen the issue.
