### ISSUE TITLE
This application is running in production mode and therefore cannot be inspected using Augury. If this is an Angular application, please rebuild your application in debug mode or remove the call to enableProdMode().

### ISSUE THREAD

**Issue by Zettle** [rangle/augury#1252]
Augury: 1.14.0
Date: Tue, 21 Nov 2017 04:39:39 GMT
OS: Win32

Angular version (required): 4.2.4

Steps to reproduce:
1.use angular/cli to build a project
2.run `ng server` and open 'http://localhost:4200/'
3.use Chrome and press F12 - Augury，but show info :
`This application is running in production mode and therefore cannot be inspected using Augury.
If this is an Angular application, please rebuild your application in debug mode or remove the call to enableProdMode()`

but I am sure and console show `Angular is running in the development mode. Call enableProdMode() to enable the production mode.`

**Comment by gentoo90** [comment]
I had the same problem, but is was gone when I added
```json
  "angularCompilerOptions": {
    "debug": true
  }
```
to my `tsconfog.json`. This is mentioned in README, but it should probably be added to the error message itself.

**Comment by combine13** [comment]
As @gentoo90 said - add this in the tsconfig.json
`"angularCompilerOptions": {   
     "debug": true
   }`

But also put comment on  enableProdMode(); in main.ts file so that it is:
`// enableProdMode();
`

Rebuild the app and go to Augury in the console - you should now be able to use it.

Cheers

**Comment by andrewthauer** [comment]
This issue was occurring for some people but was reported as fixed in Augury 1.16.0.

**Comment by Maryannah** [comment]
@andrewthauer how is that fixed ? I'm facing this issue on a project I have created this morning. 

Do you mean it's fixed like "it will never happen again", or fixed like "we documented it in our guides" ?

**Comment by racouster** [comment]
if (environment.production) {
  enableProdMode();
}

This breaks Augury...

**Comment by YuryHalamaka** [comment]
Have the same problem, tried all the solutions, suggested above, but nothing helped
