### ISSUE TITLE
Angular 5 does not work

### ISSUE THREAD

**Issue by splincode** [rangle/augury#1255]
Angular Version: 5.0.5

I open Augury and everything hangs and breaks:

```
zone.js:196 Uncaught TypeError: Cannot read property 'filter' of undefined
    at backend.js:9153
    at Array.map (<anonymous>)
    at getDependencies (backend.js:9152)
    at Object.exports.transform (backend.js:9073)
    at backend.js:9080
    at Array.forEach (<anonymous>)
    at transformChildren (backend.js:9079)
    at Object.exports.transform (backend.js:9095)
    at backend.js:9080
    at Array.forEach (<anonymous>)
```

Augury version (required): last
Angular version (required): last
OS: windows 7

**Comment by jgill248** [comment]
I get the same error.

**Comment by idanb11** [comment]
:+1:

**Comment by santiago-elustondo** [comment]
Can you link to an example repository where this issue occurs?

**Comment by zoharyosef** [comment]
I presume it happens on very large projects.
Ill try to make a plunkr or something

**Comment by chami007** [comment]
same issue here. any updates ?

**Comment by splincode** [comment]
yes it stayed the same

**Comment by Tsuki** [comment]
It is from chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:sourcemap
Which is Angury

**Comment by etherwizard** [comment]
This happens immediately after Augury gets two levels deep in analyzing the app component structure.

**Comment by zoharyosef** [comment]
I've tried 1.15 on my app (pretty big one)
and it still doesn't work :sob:

**Comment by alonstar** [comment]
I have the same error, too.  
angular v 5.2.1
chrome 64bit 64.0.3282.119

	zone.js:192 Uncaught TypeError: Cannot read property 'filter' of undefined
		at backend.js:9584
		at Array.map (<anonymous>)
		at getDependencies (backend.js:9583)
		at Object.exports.transform (backend.js:9504)
		at backend.js:9511
		at Array.forEach (<anonymous>)
		at transformChildren (backend.js:9510)
		at Object.exports.transform (backend.js:9526)
		at backend.js:9511
		at Array.forEach (<anonymous>)

**Comment by tinki007** [comment]
The problem occurs also on small applications (2 views. less than 10 components). Error description is the same as described above.

**Comment by gameboyzone** [comment]
Angular 5 support provided in version 1.15.0. Just update the extension or uninstall/reinstall the extension. I did a small check on my SPA with 1 views and 2 components and it worked fine so not sure about production level apps on Angular 5 as of now. Hope this update helps!

-- New in version 1.15.0
* Support for Angular 5

**Comment by zoharyosef** [comment]
@gameboyzone as i said, i tried V15 and it still didn't work.

**Comment by andrewthauer** [comment]
@zoharyosef: Are you getting the same error as @splincode initially indicated? If not, would you mind posting any errors along with other relevant information to help diagnosis the problem?

**Comment by santiago-elustondo** [comment]
Currently building out some diagnostic tools that will allow us to see where Augury is failing for you, as we are not able to replicate a lot of these issues.
We hope to be able to resolve these and other bugs very soon.
You may follow the development of this feature here: https://github.com/rangle/augury/pull/1272

**Comment by santiago-elustondo** [comment]
Anyone who is still having this issue: can you try using the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) ?
Does the problem persist there, or is it resolved for you?

**Comment by zoharyosef** [comment]
Will try and update...
Thanks!

**Comment by zoharyosef** [comment]
Still the same problem,
the state tab doesn't show any component variables or anything...
let it be noted that i'm using it in an internal network, no access to the internet.
is it possible that some initialization that depends on an internet resource prevents Augury from functioning properly?

**Comment by m-przybylski** [comment]
I spend some time to debug the issue by myself. I don't know how to fix it so I'm not able to provide PR. It happens when you use combination of @Inject decorator and forwardRef in constructor. It happens to me when I use Menu component from PrimeNG library [link](https://github.com/primefaces/primeng/blob/1988b877bf9cb6b9cec73817e3eda4b387d0fb0d/src/app/components/menu/menu.ts#L27:25).

**Comment by splincode** [comment]
@santiago-elustondo Yes, I only see problems with Primeng

**Comment by santiago-elustondo** [comment]
@m-przybylski, thanks a lot your insight. None of our example apps used `forwardRed()`. Ive added PrimeNG, specifically the `Menu` component to our demo testing app.
@m-przybylski, @splincode, can you update your [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) and check the problem has gone away for you?

**Comment by m-przybylski** [comment]
Thank you @santiago-elustondo for an update. I have spotted also one more problem. When you mix optional parameter and not optional it also breaks. An example is [growl](https://github.com/primefaces/primeng/blob/master/src/app/components/growl/growl.ts) component from PrimeNg. It works fine if there is only one dependency with optional decorator provided however if there are multiple `@optional()` decorators it breaks. I know that there are a lot of edge cases to cover.

**Comment by santiago-elustondo** [comment]
@m-przybylski, thanks again for your help. Much appreciated. 

I've added [PrimeNG's Growl](https://github.com/primefaces/primeng/blob/master/src/app/components/growl/growl.ts) to our testing repo and published another version of the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) (version 1.15.5).

Please let us know if you come across other such cases.

We're in the process of refactoring and standardizing Augury's data extraction services. Hopefully once we have coverage over these edge cases, they will not be a problem again in future releases of Angular.

**Comment by m-przybylski** [comment]
@santiago-elustondo UR my hero. Thank you for your help. Everything works just fine for me.

**Comment by splincode** [comment]
Problem resolved

**Comment by santiago-elustondo** [comment]
Beauty.
