### ISSUE TITLE
Is Vivaldi supported?

### ISSUE THREAD

**Issue by lski** [rangle/augury#1256]
Augury version (required): 1.14.0
Angular version (required): 4.4.0
Date: 08/12/2017
OS: Win 10

Description of issue:
Is there any reason the extension would not work on Vivaldi? The Augury tab simply doesnt appear. I installed it via the chrome store, Vivaldi supports most chrome extensions.

I am sorry I havent made a chrome extension before (just an FF one) so dont know how to check it.

**Comment by santiago-elustondo** [comment]
Hey, sorry about the delay.
It sounds like Vivaldi supports installation of `.crx` files. If this is the case, it should work just by installing the `augury.crx` file available in the Chrome Store. (https://help.vivaldi.com/article/extensions/)
