### ISSUE TITLE
Augury app isn't working

### ISSUE THREAD

**Issue by rajeshbattula631** [rangle/augury#1264]
Augury version (required): 5.0.0
Angular version (required): 5.0.0
Date: 05-01-2018
OS: Windows

Description of issue:
-- Include (clipped) screenshot images if possible.
Augury app is not working when i am debugging. Please help me in this. Thanks in advance.

**Comment by santiago-elustondo** [comment]
Hello, please provide more detail. 
Does the developer tools tab load?
Are you seeing any error messages? Can you take some screenshots?
Is there a repository that we can test against to replicate the issue?

**Comment by dizid** [comment]
Same problem here.
Just installed Augury on Lubuntu / Chrome / Angular 5
The extension loads, no errors but it doesn't show anything, no component tree no nothing.
The only thing it says "No component selected", so when i try selecting anything on the webpage the Angular app is loaded (http://localhost:4200/) it still shows nothing.

**Comment by sumitarora** [comment]
@dizid Do you have a sample repo where you can replicate the issue?

**Comment by dizid** [comment]
Hi Sumitarora, 
I managed to upload this learning Angualr-project to github here:
https://github.com/dizid/recipes.git

**Comment by dizid** [comment]
I have another issue now. While the Angular app (same as above on github) is loaded in the browser, Augury says: "This application is not an Angular application.
This application cannot be inspected using Augury."

While i am pretty sure i am not developing in C+ :)

**Comment by laudeam** [comment]
_Angular Version 5.2.1
Chrome Version 63.0.3239.132
Built with ng-cli 1.6.5
OS Windows 10_

Augury seems badly broken on the default app created with ng-cli : buttons NgModules, RouterTree, InjectorGraph do not respond.

**Comment by santiago-elustondo** [comment]
Thanks for the example repo, @dizid. It seems to be missing some important files like `package.json`, that prevent me from being able to install and run.

Hey @laudeam, thanks for reporting this issue. It works fine on my end, using ng-cli 1.6.6. I will keep you posted as we try out some diagnostic tools.

**Comment by andrewthauer** [comment]
@dizid, @laudeam - Can you please try the latest release (1.16.0)?

**Comment by laudeam** [comment]
@andrewthauer I tested 1.16.0 with the default angular app with the same config as above and it's working fine. Thanks for the fix !

I also did some quick tests on other projects and didn't notice any problem. I can inspect my components, see the router tree and the module list.

**Comment by Webbrother** [comment]
The same issue. It just shows nothing.

**Comment by yallen011** [comment]
Hi @Webbrother this issue was closed in will not be reopened since it deals with an Augury later then the current. If you would like your particular issue looked at, please open a new issue and add details based on the questions asked in the new issue you create.

Thanks
