### ISSUE TITLE
Augury with Angular 5 Service Worker

### ISSUE THREAD

**Issue by philanz** [rangle/augury#1265]
Augury version (required): 1.14.0
Angular version (required): 5.0.0
Date: 11/1/2018
OS: Ubuntu 16.04 LTS

Demo test application:
Angular CLI  - 1.6.3 Generated Code

Steps to reproduce:

1. Get chrome and install augury
2. create an angular 5 service worker app (ng new angularpwa --service-worker)
3. ng build --prod
4. run http-server on dist folder
5.Refresh app few times and see the app crash

Uninstalled Augury and app is working fine.

**Comment by santiago-elustondo** [comment]
Hi @philanz, thanks a lot for contributing, and providing clear instructions to replicate the issue.

I have followed your instructions, and have not been able to replicate. The app functions normally on my end after refreshing numerous times.
I am running Mac OSX (High Sierra) and Augury 1.14

Augury should not start up if the application is running in production mode. The Angular service worker configured to only run in production mode by default. 

Here's what i see:
<img width="1353" alt="screen shot 2018-01-12 at 1 50 36 pm" src="https://user-images.githubusercontent.com/10526720/34890505-2e21a304-f7a0-11e7-85df-1737ab232275.png">

Even if i set the service worker to run in debug mode, I still see no issues. The app as well as augury both run for me as expected after refreshing numerous times.

<img width="1346" alt="screen shot 2018-01-12 at 2 28 01 pm" src="https://user-images.githubusercontent.com/10526720/34891784-dc8c7654-f7a4-11e7-9a3a-fec65f03ea5c.png">
<img width="509" alt="screen shot 2018-01-12 at 2 28 10 pm" src="https://user-images.githubusercontent.com/10526720/34891789-e01aed28-f7a4-11e7-9849-6a2b4b267e48.png">

Are you configuring your service worker to run in development mode as well?
Are any errors visible in your console?
Does the Augury tab show the same message for you (as in my first screenshot)?

Again, thanks a lot for the report. We'll be looking into it further.
