### ISSUE TITLE
NgModules tab shows "None" for all headings

### ISSUE THREAD

**Issue by dochsu** [rangle/augury#1266]
Augury: 1.14.0
Date: Sun, 14 Jan 2018 22:10:24 GMT
OS: Win32

Description of issue:

Augury shows no modules under NgModules when debugging an Angular 5 application in Chrome:

![image](https://user-images.githubusercontent.com/2533219/34921330-78b6deca-f94e-11e7-8324-bfd5d58e8d3b.png)

Angular version (required): 5.0.0.0

Steps to reproduce:

1) Install Augury in the latest version of Chrome (63.0.3239.132).
2) Create a new angular application using latest angular/cli and run 'ng serve'. 
3) Navigate to http://localhost:4200 and bring up Augury
4) Select the NgModules tab 
5) Expect imported modules to be listed.  Instead, see 'None' for all headings.
6) This is the same in both normal and incognito modes.

Additional details:

**Comment by keneasson** [comment]
Hello Dochsu,
I'm unable to reproduce this issue with Angular 5 or 6
Angular CLI: 1.7.4
Node: 8.11.2
OS: darwin x64
Angular: 5.2.11
![devtools-augury-ngmodules](https://user-images.githubusercontent.com/5454697/43906147-90f6f208-9bc0-11e8-9f4c-276873ba9106.png)

I'm using Chrome Version 67 with very few other extensions active. 
Would you mind trying again and let us know if the problem has cleared up? If not, please create a new Issue.

Thank you
Ken
