### ISSUE TITLE
Invalid color code: undefined

### ISSUE THREAD

**Issue by fatihemre** [rangle/augury#1269]
Augury: 1.15.0
Date: Tue, 30 Jan 2018 05:53:30 GMT
OS: Windows 10 Pro

Description of issue:
-- After opening any web page, augury returns two alert box. Boxes contains same messages, eg "Invalid color code: undefined"

Angular version (required): The web page not contains an angular script.

If i disable Augury, alert box is not opening

**Comment by andrewthauer** [comment]
@fatihemre - Can you try the latest release?

**Comment by andrewthauer** [comment]
Closing with the assumption this may be fixed. If it is still occurring, please re-open with some additional details.

**Comment by fatihemre** [comment]
Hi,

I re-install Augury and try this but there is no solution here.

![image](https://user-images.githubusercontent.com/10179566/40900061-77ee41e8-67d2-11e8-8987-e35e7fd07bcc.png)

This is my screenshot, if webpage contains any angular code, augury is crashing website. If you want details, please ask what do you want

**Comment by santiago-elustondo** [comment]
Hey @fatihemre,
What version of chrome are you running?
It seems to not supports `Set()` ?

**Comment by fatihemre** [comment]
@santiago-elustondo 
My chrome version is 67.0.3396.87 (Official Build) (64-bit)
My Augury version is 1.19.1

If the website contains angular 1.x, augury is crashing website. If angular 2.x or higher, there is no problem.

**Comment by NaveenDA** [comment]
We are facing the same issue.
After we debugging the code, we found one of our third-party files is overriding the `Set` method.
@fatihemre, please place this code in the source file, so that you can find where it was called
```js
window.alert = function() { debugger; };
```
![Screenshot](https://user-images.githubusercontent.com/20555082/74217434-641f4900-4ccd-11ea-90a2-2059c720ffc1.png)
