### ISSUE TITLE
Inability to debug Factory Components such as Mat Dialogs

### ISSUE THREAD

**Issue by gangsthub** [rangle/augury#1271]
Augury: 1.15.0
Date: Mon, 12 Feb 2018 11:20:38 GMT
OS: Win32

Demo test application:
-- https://angular-czrxrm.stackblitz.io/
-- https://stackblitz.com/edit/angular-czrxrm?file=app%2Fdialog-overview-example.ts

Description of issue:
-- Entry components are not added to the component graph. Neither you can search them by using the search field

Angular version (required): Tested in 5.2

Steps to reproduce:

1. See Components Tree. Mat Dialog is not present
2. Open Mat Dialog (then component is rendered-created-added)
3. Components Tree is not updated

Additional details:
_MatDialog instantiates components at run-time._ (https://material.angular.io/components/dialog/overview)

**Comment by sheariley** [comment]
I'm having the same issue.  Would be really nice to have this fixed.

**Comment by sebastianslutzky** [comment]
+1. I create complex components as pop ups and would need to debug them

**Comment by andrewthauer** [comment]
Created consolidated issue #1380 to track this
