### ISSUE TITLE
getter value is not reflected in state section

### ISSUE THREAD

**Issue by Adam-Michalski** [rangle/augury#1276]
Augury version (required):
4.6
OS:
Windows 10
Demo test application:
https://angular-wt79u6.stackblitz.io/

Description of issue:
getters value is not reflected in state section of Augury.
with below implementation only _name value is visible 
otherName is not recognized.

I think _name, name, otherName should be reflected in State section for component cause every application has:
1. private fields without getters like services.
2. private fields with getters like _name
3. getters without fields like otherName

`export class AppComponent  {
  _name = 'Angular 5';

  get name(){
    return this._name;
  }

  get otherName(){
    return this._name !== 'Angular 5'
  }
}`

Steps to reproduce:

1. Open demo App link
2. Open Chrome console 
3. Open Augury
4. Select AppComponent
5. check State there is only _name (private field)

**Comment by santiago-elustondo** [comment]
Thank you for this feature suggestion. Adding to backlog.

**Comment by andrewthauer** [comment]
Seems related to #1223

**Comment by wtho** [comment]
They can be identified manually by walking up the prototype chain using `Object.getOwnPropertyDescriptors(componentInstance)` or `Object.getOwnPropertyNames(componentInstance)` on each level (should be just one level in basic Angular Components)

**Comment by andrewthauer** [comment]
Closing since this is most likely related to #1223
