### ISSUE TITLE
How to use Augury to profile Angular app performance?

### ISSUE THREAD

**Issue by rance** [rangle/augury#1279]
Augury version (required): 1.15.0
Angular version (required): 4.0
Date:
OS: MacOS

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Hi, the Augury official guide does not provide anything related how to use Augury to profile Angular app performance...
Do I mistakenly think Augury can be used to do that?
Thanks!

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by andrewthauer** [comment]
@rance - What specifically are you trying to profile? Have you tried using the the Chrome / Firefox builtin performance profiling? We are definitely open to new ideas that are specific to help with Angular development. However, it doesn't make sense (imo) to build performance profiling tools in Augury that may already be available in the standard DevTools provided by the browsers.

**Comment by fr0** [comment]
I often find that performance problems related to Angular bindings being slow (because they are being called too much, for example) are difficult to debug using the browser's built-in performance profiling tools. The profiler indicates that a lot of the time is spent in script, but the functions at the top of the list are all in Angular code and zone.js, and it's very difficult to make sense of them.

It would be nice to be able to see

a) Why is change detection running? What event or call triggered it?
b) What bindings are running, and how often? Which ones are slow?

**Comment by andrewthauer** [comment]
@fr0 - Thanks for the input. We have been discussing something similar to what you describe. The issues #1237, #998, #1245 are somewhat related to this sort of thinking. We will definitely consider this moving forward.

**Comment by simeyla** [comment]
There must be tonnes of things that could be done

- Some kind of proxy layer over an observable to detect if you have forgotten to unsubscribe. There must be tonnes of people (cough cough) who are new to Angular that have so many other things to learn that they neglect to keep track of subscriptions properly
- Some simple numeric metrics would help immensely. How many of these are even possible I have no clue - but I'm sure something can be wrangled. It may be hard to get this confined to user code too. hmm. Here's some things theoretically I'd love to see:

     - Count of number of total subscriptions made
     - Count of number of total unsubscriptions made. 
     - Delta between the two. Then I can click around my app and see if I'm leaking or not.
     - Times change detection ran
     - Instantiation counts of certain directives / components

**Comment by andrewthauer** [comment]
Hi @simeyla - Thanks for the great ideas! We agree there are potentially lots of things that could be done to track performance better in Angular. We have been experimenting with tracking some additional information (currently around change detection). This is all completely experimental at this point, but seems inline with what your thinking. Will definitely factor in your suggestions moving forward.
