### ISSUE TITLE
[Feature] Dynamic browser toolbar icon 

### ISSUE THREAD

**Issue by inunotaisho26** [rangle/augury#1280]
Augury version (required): 1.15.0
Angular version (required): 4.3.6
Date: 03/29/18
OS: macOS High Sierra

Description of issue:
Would appreciate if augury coloring is neutral when not on an angular website. Its a similar feature to what React DevTools do

Additional details:

React DevTools when on a React site:
<img width="86" alt="screen shot 2018-03-29 at 9 09 17 pm" src="https://user-images.githubusercontent.com/19748234/38120328-0c0ce09e-3396-11e8-9db7-8540126e3858.png">

React DevTools when not on a React site:
<img width="84" alt="screen shot 2018-03-29 at 9 06 52 pm" src="https://user-images.githubusercontent.com/19748234/38120341-26773ed4-3396-11e8-9c75-9d1e3c58fccb.png">

**Comment by andrewthauer** [comment]
Fixed in PR #1358

**Comment by inunotaisho26** [comment]
@andrewthauer Thanks a bunch!!
