### ISSUE TITLE
augury doesnt detect angular or displays no data

### ISSUE THREAD

**Issue by JonasNo** [rangle/augury#1281]
Augury: 1.15.0
Date: Fri, 30 Mar 2018 12:45:02 GMT
OS: Win32

Description of issue:
Extension gives the following message:
"This application is not an Angular application.
This application cannot be inspected using Augury."

or

it will sometimes not display the message but display empty.

Angular version (required): 1.3.9

Steps to reproduce:
1. Goto https://www.systembolaget.se/sok-dryck/
2. Inspect it.

**Comment by santiago-elustondo** [comment]
Hey @JonasNo, thanks for checking out Augury!
AngularJS (pre-Angular 2) is not inspectable by Augury.
