### ISSUE TITLE
Components state is not visible if Router is injected in component

### ISSUE THREAD

**Issue by Hojou** [rangle/augury#1283]
Augury: 1.15.5
Date: Fri, 06 Apr 2018 09:46:59 GMT
OS: Win32

Angular version (required): 5.0.1

Steps to reproduce:
1. Create an app with a component that has a service as a dependency. Observe the components state and modify the service properties, events etc.
2. Add Router as a dependency to the component. The components State is disabled in the Augury plugin. You can no longer inspect the service from previous step

Additional details:
Whenever a component is dependant on Router or on another service that has a dependency to Router, the State tab is disabled for that component in Augury.
I know this is an old bug from a previous version of Augury *and* previous version of Angular:[https://github.com/rangle/augury/issues/699](https://github.com/rangle/augury/issues/699)

With Router injected:
![image](https://user-images.githubusercontent.com/514426/38415137-d1c7aca6-3990-11e8-9fec-5f486951c0d1.png)
Without Router injected:
![image](https://user-images.githubusercontent.com/514426/38415186-f6353086-3990-11e8-9e7a-34eaea4197df.png)

**Comment by santiago-elustondo** [comment]
Thanks a lot. Will investigate.

**Comment by santiago-elustondo** [comment]
Thanks. Will investigate.

**Comment by nstohler** [comment]
Same problem for me if when I inject HttpClient:

`constructor(private http: HttpClient) {}`

**Comment by santiago-elustondo** [comment]
The router injection issue is confirmed. I see the state disappearing when Router is injected.
However, It works fine for me when I inject HttpClient.
@nstohler, are you injecting anything else into that component?

**Comment by nstohler** [comment]
@santiago-elustondo I've set up a new Angular CLI v6 project, and as soon as I inject any service (HttpClient or even an empty service I've created with `ng g s empty`), I get no more component state. 

With the Canary Build, it all works.

**Comment by santiago-elustondo** [comment]
Version 1.16.2 released, which brings the official FireFox and Chrome versions up-to-date with the Canary Build.

**Comment by santiago-elustondo** [comment]
Please reopen if the issue persists.

**Comment by tinyweasel** [comment]
Still happening me on 1.21.0

**Comment by ChrisBrownie55** [comment]
@santiago-elustondo or @Hojou can someone reopen this. I'm still having this issue on `v1.22.0`. Also, if someone could git bisect to find where the issue was reintroduced that might help.
