### ISSUE TITLE
error TS1240: Unable to resolve signature of property decorator when called as an expression

### ISSUE THREAD

**Issue by VICHE89** [rangle/augury#1287]
Augury: 1.16.0
Date: Sat, 14 Apr 2018 23:05:30 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by andrewthauer** [comment]
Closing due to insufficient details of issue. Feel free to re-open if you have additional relevant information that will help determine the problem.
