### ISSUE TITLE
Augury breaks Firefox XML viewer

### ISSUE THREAD

**Issue by andreicristianpetcu** [rangle/augury#1289]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version 1.16.0:
Angular version any:
Date: 18th of April 2018
OS: GNU/Linux

Description of issue:
-- When I install Augury I cannot see XML files highlighted in Firefox.

Steps to reproduce:

1. Visit any XML page with Firefox without Augury installed for example http://search.maven.org/remotecontent?filepath=com/jenmaarai/sidekick/2.5/sidekick-2.5.pom and you will see a pretty XML.
![screenshot from 2018-04-18 18-48-46](https://user-images.githubusercontent.com/922368/38947760-0c7746ac-433e-11e8-885f-e686a8321845.png)

2. Install Augury and visit the same page and you will get no XML formatting.
![screenshot from 2018-04-18 18-48-52](https://user-images.githubusercontent.com/922368/38947783-17e93c0c-433e-11e8-89a8-c41bce9711f9.png)

**Comment by santiago-elustondo** [comment]
Thanks @andreicristianpetcu. Please see PR comments.

**Comment by santiago-elustondo** [comment]
merged
