### ISSUE TITLE
Augury makes Firefox really slow

### ISSUE THREAD

**Issue by andreicristianpetcu** [rangle/augury#1291]
Augury version: 1.16 ([my own build](https://github.com/andreicristianpetcu/augury/releases/download/v1.16.0.2/augury-1.16.0.2-an.fx.xpi) since it does not have a Firefox port yet)
Angular version (required): 5.2.9
Date: 23 April 2018
OS: Ubuntu 16.04

Demo test application:
 - I tried to reproduce the issue with an open source app but I failed. It only reproduces with the proprietary app I'm working on :(

Description of issue:
![screenshot from 2018-04-23 11-06-58](https://user-images.githubusercontent.com/922368/39114157-a9a5a8c8-46e6-11e8-8a94-f572c903e425.png)

Steps to reproduce:

Open dev tools, jump to Augury tab and navigate the component tree.
The app slows down really badly.

Additional details:

Here is the performance snapshot https://perf-html.io/public/99abd0e033222a20fb85d5d6a0cc9ce562bef45b/calltree/?implementation=js&thread=0&threadOrder=0-2-1&v=3

**Comment by santiago-elustondo** [comment]
Can you build without uglify (like `npm run build:dev:firefox`), so we can see the function names in your performance chart?

**Comment by andreicristianpetcu** [comment]
It does not seem like it is a really big app. Maybe some other extension is messing with Augury somehow. Check out the [new profile](https://perf-html.io/public/29cd280de0ac7f4011aa0e0e491124c76e70cccf/calltree/?implementation=js&range=39.8177_47.9046&thread=0&threadOrder=0-2-1&v=3), hope it has better data. 

![screenshot from 2018-04-23 22-04-55](https://user-images.githubusercontent.com/922368/39147528-8dc03266-4742-11e8-9907-176a26699862.png)

```bash
git log
9f8148e tag version (santiago-elustondo, 11 days ago)
```

**Comment by andreicristianpetcu** [comment]
I think I found a little more info. It seems to allocate A LOT of data. My Firefox profile with one tab at about:debugging and another one at my app localhost:4200 and 41 enabled WebExtensions takes around 400-500 MB shared between 1 main process and 2 Web Content ones.

Once I enable Augury the RAM slowly goes up and up until Firefox completely freezes. At some point both the content and the main process were well above 3G!!! I tried to record the memory with the about:memory tool in Firefox and I recorded it when both main and content processes were above 1G.

Here is the important part:

![screenshot from 2018-04-23 22-54-34](https://user-images.githubusercontent.com/922368/39150038-b13794b2-4749-11e8-92d5-fa971a64e37b.png)

Here is the full image:

![screen shot 2018-04-23 at 22 54 08](https://user-images.githubusercontent.com/922368/39150054-c091f33a-4749-11e8-946f-2137fb4a7981.png)

You can load my memory report in your about:memory page.

[memory-report.json.gz](https://github.com/rangle/augury/files/1939803/memory-report.json.gz)

I hope this is useful information for you :)

**Comment by digitarald** [comment]
Just a quick analysis of the first profile (the second seems to have data missing).

The extension seems to message multiple times per frame and have a heavy computation in response to the message:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/8599/39337176-64a6bcda-4970-11e8-8a7c-17f9c8dbed1e.png">

GC is an issue, maybe caused by the many messages and adds overhead for collection while the heap still keeps growing.

**Comment by andreicristianpetcu** [comment]
Thank you for looking into this, @digitarald! Please keep in mind that I can run a build from a branch so if you make one with lots of consolo.log to confirm/infirm this hipotesys

**Comment by andreicristianpetcu** [comment]
Hmmmm.... GC? The same app really slows down debugger.html by allocating a lot of RAM. Maybe unrelated, but worth mentioning https://github.com/devtools-html/debugger.html/issues/6094

**Comment by santiago-elustondo** [comment]
Hey guys, thanks for the info.
I can't say I've been able to reproduce this memory leak. (I'm on Chrome)

I've been using the following methods:

In the first instance, I am creating a large component tree all at once, taking heap snapshots before and after. As you can see, the memory allocation doubles. (Here Augury is disabled)
<img width="757" alt="screen shot 2018-05-04 at 2 23 10 pm" src="https://user-images.githubusercontent.com/10526720/39646764-801f9082-4faa-11e8-8014-6a368440bcb4.png">

Then here's the same, but with Augury enabled. The size of memory is only very slightly larger in the application's execution context, and in Augury's front end context (dev tools tab) it is 25MB and grows modestly with the added component tree.

In a second test I set a timeout to update the component tree (albeit a smaller one) multiple times per second (sending many messages per second to the front end). Here again I see an increase over time, but nothing radical. I suppose that if left to continue for long enough, it could possibly grow quite large.
<img width="1107" alt="screen shot 2018-05-04 at 2 34 10 pm" src="https://user-images.githubusercontent.com/10526720/39647177-e01e2a9c-4fab-11e8-84d7-c97c9732993c.png">

Do you think I'm on the right track here?

**Comment by andreicristianpetcu** [comment]
Not sure if it's the right path. I was unable to fix our app on Chrome. I will comment here if our app breaks Augury on Chrome or not.

Did you do a similar test in Firefox also where the bug was originally reported?

**Comment by santiago-elustondo** [comment]
@digitarald, where do you see the frequency of messaging?

**Comment by santiago-elustondo** [comment]
@digitarald, where are you seeing the frequency of messaging and the computational load attached to each message? Also, where do you see the GC problem?

**Comment by andreicristianpetcu** [comment]
@andrewthauer can I help you in any way to reproduce the issue?

**Comment by santiago-elustondo** [comment]
@andreicristianpetcu, that would be great.
To be honest, I'm not sure I understand the issue as described.
What are you reading from the `perf.html` log?
Any idea how we might reproduce this?

**Comment by santiago-elustondo** [comment]
To offer some context, we are aware that certain component dependencies (notably `Router`) will cause Augury to produce very large serialized messages representing that component's state when that component is selected for inspection. Even then, however, I do not experience significant lag on my end. Do you think this might be related?

**Comment by andrewthauer** [comment]
@andreicristianpetcu - By any chance is your app using `ngrx` or `redux` and do you have the Redux DevTools installed in FF?

**Comment by andreicristianpetcu** [comment]
ngrx + Redux DevTools

**Comment by andrewthauer** [comment]
@andreicristianpetcu - We have a working theory that somehow the combination of the Augury + Redux DevTools seems to exhibit this behaviour in both Chrome & Firefox (although it's more obvious in FF). In my case, if I disable the Redux DevTools the problem goes away. It could be related to how  both add-ons post messages and some sort of conflict with zone.js. Further investigation will be required.

**Comment by andreicristianpetcu** [comment]
@santiago-elustondo I looked today before leaving work at some memory snapshots (I don't have the source code at home). I did not want to make any statement until I understood the cause completely but I also saw some big memory objects related to zone.js.

I will try to disable Redux DevTools on Monday to see how that goes.

Thank you so much for persisting in trying to understand this issue. I really appreciate it.

**Comment by santiago-elustondo** [comment]
@andreicristianpetcu, can you try the latest [Canary Build](https://chrome.google.com/webstore/detail/leechohfifidanmkioncamdcibhmmcji) (version 1.17.2) ?

**Comment by andreicristianpetcu** [comment]
@santiago-elustondo I will test it tomorrow. I guess you want me to test the cannary build on Firefox, right?

**Comment by santiago-elustondo** [comment]
Yeah, you could just build the `dev` branch for Firefox (Canary is always up to date with the `dev` branch).

**Comment by santiago-elustondo** [comment]
Hey, @andreicristianpetcu 

Official 1.18.0 has been released to FireFox add-on store, bringing it up to date with the Chrome canary.
Can you tell me if the problem persists?

**Comment by santiago-elustondo** [comment]
FYI, the Firefox add-on is still not fully working (does not update properly or show component states), because of a CSP issue we are currently working through. 

The slowness (and freezing) problem due to messaging short-circuiting seems resolved on my end, however.

**Comment by andreicristianpetcu** [comment]
@santiago-elustondo  sorry I did not have time to re-test :( I was really busy at work. I will re-test a week from now since I have a week off. If it still happens I will try to provide more info, if not.... well... yay :D Hope the fix worked for our app.

**Comment by santiago-elustondo** [comment]
Assuming fixed for everyone.
Please reopen if this issue persists.

**Comment by andreicristianpetcu** [comment]
Sorry for the radio silence. It is indeed closed. Thank you!
