### ISSUE TITLE
Augury repeatedly calling function on non-Angular page

### ISSUE THREAD

**Issue by sethjensenbrown** [rangle/augury#1293]
Augury version (required): 1.16
Angular version (required): N/A
Date: 2/24/18
OS: OSX 10.13

Description of issue:

I have a line of code like this `<a href="javascript:postMessage()"><img src="image.gif" alt="Apply" border=0></a>` in a non-Angular page on my company's website, and the Augury extension was causing it to repeatedly get called multiple times per second. I disabled the extension and that extension only and it caused the problem to stop. Just wanted to let y'all know in case it is happening on other websites.

**Comment by guillaumegarcia13** [comment]
Got a similar beahviour on: https://www.club-acheteurs.com/

**Comment by santiago-elustondo** [comment]
Issue confirmed. Will provide more updates shortly.

**Comment by santiago-elustondo** [comment]
This is an interesting edge case. 

You have redefined the global `window.postMessage()` function, which is a built-in browser API.

Augury uses it to communicate with the developer tools.
<img width="449" alt="screen shot 2018-05-04 at 10 47 41 am" src="https://user-images.githubusercontent.com/10526720/39634616-44b8eae6-4f89-11e8-95d7-6db5111fdc54.png">

Wappalyzer uses this API as well.
<img width="351" alt="screen shot 2018-05-04 at 10 53 01 am" src="https://user-images.githubusercontent.com/10526720/39634649-5ab8889c-4f89-11e8-8657-dc56aeac4f88.png">

**Comment by guillaumegarcia13** [comment]
@santiago-elustondo 
Thank you very much for your quick response and analysis of this problem.
And sorry for this "edge case"... going to have a talk with the developer. 😅
