### ISSUE TITLE
Can't remove Augury

### ISSUE THREAD

**Issue by apallen** [rangle/augury#1294]
I wan't remove Augury from Chrome on my Mac. 

I literally just installed this yesterday. I played with it. Don't want to use it.  I removed it from Chrome yet it still appears!!!!

I did not install it in Firefox but some how this Chrome Extension even appears in FireFox!!

I just installed this yesterday on my Mac.  How do I get rid of this thing!!

**Comment by santiago-elustondo** [comment]
go to `chrome://extensions/`
