### ISSUE TITLE
I havn't component states

### ISSUE THREAD

**Issue by Franklinmagic** [rangle/augury#1300]
Augury: 1.16.0
Date: Fri, 11 May 2018 00:43:47 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.
![image](https://user-images.githubusercontent.com/8379841/39900931-7187c290-54c5-11e8-85b5-3e7e6d2118ab.png)

Angular version (required): 4.4.6

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by clabough** [comment]
I'm still having the same issue that was in #1253 

Augury 1.16.0
Angular 6.0.1

It displays the component dependencies correctly, but no properties. Note: this is not for every component in the project, just some.

I've turned on "Usage Data" to try and help.

**Comment by santiago-elustondo** [comment]
@clabough, thanks for the issue submission.
Any idea what might be different about the components that have this problem?

**Comment by Franklinmagic** [comment]
i have this problem of all components of all angular's projects.
I make new project for testing but i have same problem.

**Comment by rekna1** [comment]
Same here, angular 5.2.9 augury 1.1.16.
Only very simple components show state, such as a loading indicator. None of the components loaded in router outlet show any state. Some previous version of augury did not have this problem, but I can't remember when it started to go wrong

**Comment by santiago-elustondo** [comment]
Can you try the latest [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji), and tell me if the issue persists there?

**Comment by clabough** [comment]
Issue still persists in Canary build.

**Comment by santiago-elustondo** [comment]
@clabough, can you confirm you're using `v1.16.1` of the Canary Build ?

**Comment by Franklinmagic** [comment]
Thank for this soluce which resolve my problem

**Comment by clabough** [comment]
@santiago-elustondo Yes. 1.16.1. What's really weird is that it will show states for simple components within the more complex component that it doesn't show states.  If I can find time, I will try to make a stripped down version that exhibits the issue.

**Comment by santiago-elustondo** [comment]
@clabough, what does the complex component take as constructor parameters?

**Comment by clabough** [comment]
@santiago-elustondo Various constructors. I tried making a side project with only part of my main application that wasn't showing states in some components, but it worked there, so it must not be the complexity of one set of components, but the complexity (or number of ) components within the application. I'll let you know when I have a repo that you can view.

**Comment by rekna1** [comment]
for me the canary build has fixed the issue

**Comment by santiago-elustondo** [comment]
Thanks a lot, @clabough. Keep me posted.
Please create a new issue, and I'll be happy to get it resolved when we have a replicable case.
