### ISSUE TITLE
[bug] "dark mode" color scheme breaks readability of selected component 

### ISSUE THREAD

**Issue by walrus95** [rangle/augury#1303]
Augury version (required): 1.16.1 (canary on Chrome)
Angular version (required): 4.4.3
Date: 5/16/18
OS: Windows 10

Description of issue:
I love the "dark mode" color scheme. However, the choice of colors obscures the view of the name of a component when it's selected such that it can't be read:

![dark_mode](https://user-images.githubusercontent.com/32824014/40137045-7d838826-5917-11e8-98df-bc950abc6ed5.PNG)

To workaround this issue, it's necessary to hover over the name of the component. The "light mode" doesn't suffer from this issue:

![light_mode](https://user-images.githubusercontent.com/32824014/40137053-823bd79c-5917-11e8-9592-b82818213358.PNG)

I would like to request a slightly different color scheme for dark mode such that this text can be read without the need to hover, because the "light mode" doesn't need to hover.

Thank you!

Steps to reproduce:
1. Switch to "dark mode" and select a component from the component tree. You will not be able to read the selected text without hovering over it.

**Comment by santiago-elustondo** [comment]
Corrected in version 1.17.4 of the [Canary Build](https://chrome.google.com/webstore/detail/leechohfifidanmkioncamdcibhmmcji), soon to be official version 1.18.

**Comment by walrus95** [comment]
Looks great, thank you!
