### ISSUE TITLE
[feature request] Component Tree properties loading spinner and "no properties found" message

### ISSUE THREAD

**Issue by walrus95** [rangle/augury#1304]
Augury version (required): 1.16.1 (canary on Chrome)
Angular version (required): 4.4.3
Date: 5/16/18
OS: Windows 10

Description of issue:
I have noticed that there is sometimes a pause in time between clicking on the name of a component in the Component Tree and the properties for that component showing up for view. It would make for a better user experience if there was a spinner that would show during the pause between when a component is clicked and its properties showing up for view. Once the properties show, the spinner can go away.

Sometimes components have no properties. In the case where there are no properties, the user can get the impression that it's taking forever to load. It would make for a better user experience if there was a message saying "this component has no properties" or "no properties found" that would show in such cases.

Thank you!

**Comment by santiago-elustondo** [comment]
Hey @walrus95,

Thanks again for your great input, we appreciate it.
The spinner / "no props" message are being added today, as per your request. :)

**Comment by santiago-elustondo** [comment]
Feature added to [Canary Build](https://chrome.google.com/webstore/detail/leechohfifidanmkioncamdcibhmmcji) (version 1.17.3)

**Comment by santiago-elustondo** [comment]
Canary build merged into official release 1.18
