### ISSUE TITLE
Component Tree doesn't load with @Inject/Factory providers

### ISSUE THREAD

**Issue by vincentjames501** [rangle/augury#1311]
Augury version (required): 1.18.0
Angular version (required): 5.2.11
Date: 5/31/18
OS: MacOS

Demo test application:
Feel free to message me directly in Slack (vincentjames501) and I can send a link to test a site against (our hybrid app isn't live yet and repo isn't public)

Description of issue:
The component tree is empty on initial view.

Steps to reproduce:

1. Load Augury

Additional details:

We have a AngularJS/Angular Hybrid application that has a few dependencies injected like so:

```typescript
@NgModule({
  providers: [
    {provide: '$angularJSService', useFactory: i => i.get('$angularJSService'), deps: ['$injector']}
  ]
})
class AppModule {}
```

```typescript
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  constructor(@Inject('$angularJSService') private $angularJSService: any) { }
}
```

Augury appears to be blowing up silently in `transformers.ts` in `getDependencies`. `paramType` in this case is a string of `'$angularJSService'` and `Reflect.getMetadata` is throwing an uncaught exception. I don't understand the code well enough but this gets it to at least render out the component tree:

```typescript
return normalizedParamTypes.map((paramType, i) => ({
    id: typeof paramType === 'string' ? i : Reflect.getMetadata(AUGURY_TOKEN_ID_METADATA_KEY, paramType),
    name: typeof paramType === 'string' ? paramType : (functionName(paramType) || paramType.toString()),
    decorators: parameterDecorators[i] ? parameterDecorators[i].map(d => d.toString()) : [],
  }));
```

I noticed a few other issues that I haven't had a chance to investigate yet. While the above does get it to render out, I still never see the component state (I just see `Loading component state...`). Eventually my Chrome tab locks up and stops responding and I can't quite get a performance capture before it does so :). Also, while it's likely related to the lock up, the change detection always shows `Default` despite most of my components being `OnPush` and clicking `(View Source)` doesn't seem to work (all of these work in the demo application).

**Comment by santiago-elustondo** [comment]
Hey, @vincentjames501.
Thanks a lot for your detailed explanation of the issue, I'd love to have a look at your example app, I'll follow up with you on angular-augury.slack.com :)
We're in the process of hunting down reported bugs, so your help is much appreciated. 

We haven't tested on many hybrid applications, I'm sure it will create some interesting cases.

The component state bug you mentioned seems to be resolved in the latest [Canary Build ](https://chrome.google.com/webstore/detail/leechohfifidanmkioncamdcibhmmcji) (1.18.2). If it persists for you, please let us know in [the issue](https://github.com/rangle/augury/issues/1114#issuecomment-391277098).

I was not aware of the change detection issue you mentioned, and will have a look.

**Comment by vincentjames501** [comment]
Getting closer! I'm now getting this in the logs: 

```
Unhandled Promise rejection: $compile is not an object! ; Zone: <root> ; Task: Promise.then ; Value: TypeError: $compile is not an object!
    at webpackJsonp../node_modules/core-js/modules/_an-object.js.module.exports (_an-object.js:3)
    at Object.getMetadata (es7.reflect.get-metadata.js:16)
    at backend.js:31
    at Array.map (<anonymous>)
    at d (backend.js:31)
    at Object.e.transform (backend.js:31)
    at Object.e.transformToTree (backend.js:31)
    at backend.js:31
    at Array.map (<anonymous>)
    at Object.e.createTreeFromElements (backend.js:31) TypeError: $compile is not an object!
```

I sent you a link in slack you can use to do some debugging. Let me know if there is anything else I can help you debug.

**Comment by santiago-elustondo** [comment]
This issue has been resolved in this case. (conversation ensued on slack)
If anyone is still experiencing this issue, or a related issue, please reopen.
