### ISSUE TITLE
StaticInjectorError(s)[e -> r]: 

### ISSUE THREAD

**Issue by khanakifalam002** [rangle/augury#1312]
Augury: 1.18.0
Date: Fri, 01 Jun 2018 12:28:16 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by santiago-elustondo** [comment]
Please provide a description
