### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("

### ISSUE THREAD

**Issue by rezagale** [rangle/augury#1315]
Augury: 1.19.0
Date: Wed, 06 Jun 2018 20:28:12 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by santiago-elustondo** [comment]
Hey, thanks for the bug report. 
Can you tell us what action triggered this error?

**Comment by andrewthauer** [comment]
Closing due to insufficient information
