### ISSUE TITLE
Uncaught Error: Unexpected value 'DecoratorFactory' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by rezagale** [rangle/augury#1316]
Augury: 1.19.1
Date: Thu, 07 Jun 2018 21:01:28 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by keneasson** [comment]
Hi thanks for the report. We're about to push a few bugfixes as a Canary release. Please review your issue using this release, and if this problem continues, please create a new issue including steps to reproduce and some details about your environment. 

Thank you,
Ken
