### ISSUE TITLE
Memory usage in chrome exceeds 1GB

### ISSUE THREAD

**Issue by NickvdMeij** [rangle/augury#1317]
Augury version (required): latest (version on 11-6-2018)
Angular version (required): latest (verson on 11-6-2018)
Date: 11-6-2018
OS: Windows 10 pro

Description of issue:
For the past few months, I've been using Augury to improve my Angular2 workflow. However, today i noticed an unexpected sideeffect. Augury uses (even when you have no angular app running in the browser) 700-1000MB memory in idle! Tbh, for an extension doing absolutely nothing (since there is no angular app that it can inspect) this is way, WAY too much. Why is this? 

Steps to reproduce:

1. Install augury
2. go to a non-angular website
3. Open the windows taskmanager and look at the memory usage of chrome. Collapse the processes and kill the highest memory consuming process. You will notice that crhome gives you an error that "Augury unexpectedly closed"

**Comment by santiago-elustondo** [comment]
Hey @NickvdMeij, thanks for contributing.

While inspecting an actual Angular page, with the augury tab open, I do not see the heap space allocation you are reporting.

Augury runs in 3 different contexts (background, devtools, and within the inspected application). Here are some snapshots of the total heap space in each context (note that, for example, in the inspected application context, this includes the memory usage of the inspected application + augury).

The application being inspected here is a small demo app. 

<img width="618" alt="screen shot 2018-06-11 at 10 46 12 am" src="https://user-images.githubusercontent.com/10526720/41238952-42609876-6d65-11e8-81d4-2d945b015737.png">

**Comment by santiago-elustondo** [comment]
Can you take some memory snapshots?

**Comment by NickvdMeij** [comment]
@santiago-elustondo Hi, like I stated previously, I'll look into it later if you don't mind. Currently not on near the PC where the problem occurred but when I'm at that PC, ill see what I can find.
Furthermore, I didn't look in chrome dev tools but in the windows task manager. There I noticed Chrome taking up 4GB memory with +- 20 running processes. The highest one was 812MB and I killed it, and that's when I noticed it was augury I killed. At this time, I didn't have any angular application open in any of the tabs within Chrome.

**Comment by viluon** [comment]
@santiago-elustondo I doubt the heap snapshot counts the memory used by Chrome extensions. IMO it only displays memory statistics for the website you're viewing...

That said, opening Augury made my Chromium instance eat RAM like pancakes.

**Comment by santiago-elustondo** [comment]
Thanks for the info. 
We're currently doing some structural rework that aims to fix this problem. Stay tuned.

**Comment by maroy1986** [comment]
FYI, I had the same issue yesterday, the extension was taking 2.5gb of ram and 100% CPU Usage in his chrome.exe process. I don't have any screenshot, sorry, I'm just reporting that I'm experiencing the same issues has described above.

**Comment by petermikitsh** [comment]
I tried using Augury on Mac OS in Chrome 71 and it brought my browser to a crashing halt if I had Developer Tools open on a page with Angular. Uninstalling Augury seemed to fix the problem.

**Comment by andrewthauer** [comment]
Closing in favour of #1320
