### ISSUE TITLE
Cannot read property 'ngInjectableDef' of null

### ISSUE THREAD

**Issue by swimmadude66** [rangle/augury#1319]
Augury version (required): 1.19.0
Angular version (required): 6.0.3
Date: 06/13/2018
OS: Windows 10

Git Repo:
https://github.com/TetuSecurity/Lockbox/tree/dev

Description of issue:
When I try to open the augury tab, this error is echo'd 3 times in the console. The stack trace points to the "providedIn" token resolver, but all my services are `providedIn: 'root'`. 

Steps to reproduce:

1. `npm install`
2. `npm run dev`
3. open console and click on augury tab

Additional details:
Just started a week ago

**Comment by keneasson** [comment]
Thanks for reporting this issue. I believe this is a duplicate of #1322

**Comment by keneasson** [comment]
Hi @swimmadude66 and @chandesh07 
We have update the Canary Build with a fix for this issue. Can you please try the 1.19.2 version Augury Canary Build and let us know if this resolves the issue your experiencing.

Thank you

**Comment by andrewthauer** [comment]
Closing with assumption this has been resolved on v1.20.0

**Comment by bellons91** [comment]
The issue is here again.
![image](https://user-images.githubusercontent.com/6106586/48400999-3f35d200-e728-11e8-9233-0e29cbbfe9db.png)

With Angular v6.1.10 and Augury v1.21.0
