### ISSUE TITLE
You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.

### ISSUE THREAD

**Issue by gangadharravula** [rangle/augury#1321]
Augury: 1.19.1
Date: Thu, 28 Jun 2018 18:57:50 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by biyahutashish** [comment]
Try npm link. It solved the issue for me.

**Comment by andrewthauer** [comment]
Assuming this is solved. If not, please re-open with additional details.

**Comment by victorcodex** [comment]
cd to your project root. 
Run npm link
Then ng serve

**Comment by ram-bib** [comment]
> cd to your project root.
> Run npm link
> Then ng serve
Thank your for the above solution, which fixed the following error as "You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.". And i could able to compile my project successfully.

**Comment by satishvanaparthi** [comment]
this is my error.
C:\jk>ng serve
You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.
ths is my email.id  :vanaparthisatishsatish@gmail.com

**Comment by ssabat** [comment]
I had same error. I  created new directory for app. I ran
- npm link
- ng build
- ng serve

Then, it all worked fine. The app came up at localhost:4200.

**Comment by maheshmanchala92** [comment]
Thank you very much. npm link solved the issue.

**Comment by maheshmanchala92** [comment]
Thank you very much. `npm link` solved the issue.

**Comment by EliCDavis** [comment]
Did not solve the issue for me

**Comment by minhkhai1992** [comment]
it wasn't solve my issue either. I don't know what happen to project ?
