### ISSUE TITLE
responsive web disign is better

### ISSUE THREAD

**Issue by daocreate** [rangle/augury#1329]
Augury: 1.19.1
Date: Tue, 07 Aug 2018 15:56:32 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by keneasson** [comment]
Hi Daocreate,

we agree with you. if there is something specific you would like to see implemented in Augury please create a new issue with complete details. 
thanks.
