### ISSUE TITLE
https://www.apexbpm.com/technologies/decisions

### ISSUE THREAD

**Issue by shawn-tsl** [rangle/augury#1330]
Augury: 1.19.1
Date: Wed, 08 Aug 2018 18:28:55 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by keneasson** [comment]
no issue included in this report.
