### ISSUE TITLE
Add Firefox extension to augury.angular.io

### ISSUE THREAD

**Issue by digitarald** [rangle/augury#1332]
Not sure if it still actively maintained, but it would probably be useful to link to the Firefox extension page from: https://augury.angular.io/ .

**Comment by andrewthauer** [comment]
@digitarald - Sadly the site hasn't been updated in quite a while (https://github.com/rangle/augury.angular.io). I'm going to be following up on this soon to figure out what we want to do with the site moving forward. Thanks for pointing that out and reminding us!

**Comment by andrewthauer** [comment]
We've updated the official site to indicate Firefox support now. The site (https://augury.angular.io) now also redirects to https://augury.rangle.io.
