### ISSUE TITLE
Wrong url on website

### ISSUE THREAD

**Issue by KirillOFF** [rangle/augury#1337]
Augury: 1.19.1
Date: Sat, 25 Aug 2018 22:51:11 GMT
OS: Win32

Description of issue:
Official website of Augury (https://augury.angular.io/) has wronl link to Angular website (anchor is "Learn Angular")

Steps to reproduce:

1. Visit https://augury.angular.io/
2. Scroll down to the bottom of the page
3. Click the link "Learn Angular"

**Comment by andrewthauer** [comment]
@KirillOFF - Thanks. That has been fixed in the augury.angular.io repo. We are currently looking into migrating the site hosting so the actual deployment of the update won't be live for a little while.

**Comment by andrewthauer** [comment]
The incorrect link has been fixed.
