### ISSUE TITLE
not highlighting big file

### ISSUE THREAD

**Issue by softmarshmallow** [rangle/augury#1338]
Augury: 1.19.1
Date: Wed, 29 Aug 2018 21:22:38 GMT
OS: MAC

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1. open json file larger than 10mb
2. cannot highlight file

Additional details:

this is critical for bigdata, ML developers, need big file support!

**Comment by andrewthauer** [comment]
@softmarshmallow - Can you be a bit more specific about the problem your having?

**Comment by softmarshmallow** [comment]
Oh.. so sorry for that. My mistake.
