### ISSUE TITLE
can't find

### ISSUE THREAD

**Issue by j606888** [rangle/augury#1339]
Augury: 1.19.1
Date: Sun, 09 Sep 2018 06:13:35 GMT
OS: MacIntel

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by andrewthauer** [comment]
Closing due to insufficient details.
