### ISSUE TITLE
Component Tree is blank on Chrome

### ISSUE THREAD

**Issue by hoangtho799** [rangle/augury#1347]
Augury version (required): 1.19.1
Angular version (required): 5.2.11
Date: 17-Oct-2018
OS: Windows
Browser: Chrome 69.0.3497.100

Description of issue:
- Component Tree is blank
![untitled](https://user-images.githubusercontent.com/6185201/47069025-1d742880-d218-11e8-9b73-e8b4fd18e0be.png)

Steps to reproduce:

1. Launch website using Angular version 5.2.11
2. Open DevTools, navigate to Augury tab
3. See the Component Tree

**Comment by andrewthauer** [comment]
@hoangtho799 - Can you provide any more details about your application? Or better yet, a sample that replicates this issue?

**Comment by andrewthauer** [comment]
Closing due to lack of information.
