### ISSUE TITLE
Cannot scroll in router tree window

### ISSUE THREAD

**Issue by smlombardi** [rangle/augury#1361]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): 1.22.0
Angular version (required): 7.1
Date: 1/9/19
OS: Mojave
Chrome Version 73.0.3667.0 (Official Build) canary (64-bit)

Description of issue:
Cannot scroll the router tree view.  

Steps to reproduce:

1. open dev tools
2. click augury, choose router tree
3. tree displays correctly, but our app has many routes that don't fit in the dev tools window
4. try to scroll to see rest of tree but cannot

Console error when trying to scroll:
```
content-script.js:24 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    at Object.t.messageJumpContext (chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/content-script.js:24:9921)
    at chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/content-script.js:24:8583
t.messageJumpContext @ content-script.js:24
(anonymous) @ content-script.js:24
```

**Comment by protekshen** [comment]
Please help us, I have the same problem https://github.com/rangle/augury/issues/1363

**Comment by jcubic** [comment]
I have the same error, wasn't sure if this is from Augury and not sure how to reproduce.

**Comment by ketsune** [comment]
I have the same error.

**Comment by jeserkin** [comment]
For me it is present in `Component Tree` view. If property list too long and doesn't fit vertically, then I can't use it to full extent, because for some reason there is no scroll. I assume it might be connected somehow to recent Chrome update, but I am not sure.

**Comment by protekshen** [comment]
I don't understand, why we don't get feedback from developers???? this ticket start from 10 Jan, my ticket start from 24 Jan https://github.com/rangle/augury/issues/1363

Any news??? pls help us

**Comment by jeserkin** [comment]
I do hope, that statement "Making things that matter." is still valid.

**Comment by jeserkin** [comment]
Just for history purposes.

![image](https://user-images.githubusercontent.com/183512/55464482-e053f500-5603-11e9-9850-7e371ca13fd5.png)

**Comment by GuoqiangOu** [comment]
I am still experiencing this issue for augury version 1.23.0 on mac.

**Comment by Nilomiranda** [comment]
I'm still having the same issue

**Comment by Spri85** [comment]
> am still experiencing this issue for augury version 1.23 on mac

I have the same issue on windows
