### ISSUE TITLE
Error: Failed to read message queue: Error: Code evaluation failed frontend.js:786:27812

### ISSUE THREAD

**Issue by cesco69** [rangle/augury#1372]
Augury version (required): 1.22.0
Angular version (required): 7.0.0
Date: 01/02/2019
OS: Windows 7

Description of issue:

Augury tab show this error

> Error: Uncaught (in promise): Error: Failed to read message queue: Error: Code evaluation failed
>     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:786:27812
>     at callbackWrapper (<anonymous>:52:1)
>     at ExtensionServerClient._onCallback (<anonymous>:70:653)
>     at ExtensionServerClient._onMessage (<anonymous>:71:9)
> Error: Failed to read message queue: Error: Code evaluation failed
>     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:786:27812
>     at callbackWrapper (<anonymous>:52:1)
>     at ExtensionServerClient._onCallback (<anonymous>:70:653)
>     at ExtensionServerClient._onMessage (<anonymous>:71:9)
>     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:786:27580
>     at t.invoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:7005)
>     at Object.onInvoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:137:1932)
>     at t.invoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:6945)
>     at e.run (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:2169)
>     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:809:2158
>     at t.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:7689)
>     at Object.onInvokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:137:1844)
>     at t.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:7610)
>     at e.runTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:2863)
>     at S (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:809:1633)
>     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:809:2189
>     at t.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:7689)
>     at Object.onInvokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:137:1844)
>     at t.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:7610)
>     at e.runTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:2863)
>     at y (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:801:10050)

**Comment by AryanJ-NYC** [comment]
Dupe of https://github.com/rangle/augury/issues/1368#issuecomment-466452771

**Comment by wtho** [comment]
See #1351
