### ISSUE TITLE
PRTG System Administrator not working when Augury is active in Firefox

### ISSUE THREAD

**Issue by Malro** [rangle/augury#1375]
Augury: 1.21.0
Date: Fri, 08 Mar 2019 06:35:57 GMT
OS: Win10 1809 64
Browser: Firefox 65.0.2

Demo test application:
-- Firefox 65.0.2
-- Augury 1.21.0
-- PRTG System Administrator 19.1.48
-- e.g. Devices View

Description of issue:
-- PRTG System Administrator not working probably with Firefox when Augury is active. E.g. Devices View is loading infinite. Disabling Augury and PRTG is working fine.

Angular version (required): No Angular involved

Steps to reproduce:

1. start Firefox with Augury enabled
2. go to your PRTG Administrator Webinterface
3. e.g. open Devices View

Additional details:
Yes, this issue is not in context of angular. And i dont know if PRTG or Augruy or Firefox is causing the issue. A Solution could be, to partial allow to disable Augury on some sites or to allow Augury for some sites like localhost:4200 ...

**Comment by andrewthauer** [comment]
This is most likely related to #1320
