### ISSUE TITLE
Augury not detecting modal components

### ISSUE THREAD

**Issue by jalberto-ghub** [rangle/augury#1377]
Augury: 1.22.0
Date: Wed, 20 Mar 2019 13:42:40 GMT
OS: Win32

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): 7

Steps to reproduce:

1. Write a test app that imports NgbModal from @ng-bootstrap/ng-bootstrap 
2. Create a modal component for NgbModal
3. While on Auguri open your modal dialogue.

Additional details:
The Auguri window cannot see the new component at all you cannot click on it, select it or track at all. Notice that a reference to the new component is not required to be stored on a class variable.

**Comment by andrewthauer** [comment]
Duplicate, related to #1190, #1217, & #1271
