### ISSUE TITLE
No Scrollbars in Properties panel

### ISSUE THREAD

**Issue by carlsonaaron** [rangle/augury#1379]
Augury: 1.22.0
Date: Thu, 28 Mar 2019 20:48:42 GMT
OS: Win32

Description of issue:
Had this issue on Firefox in the past, but now I'm also having it in Chrome.  
Seems to have just started a couple days ago

I'm also getting a "DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned." error in my console window.  Not sure if it's related

Angular version (required): 4.3

Steps to reproduce:

1.  Open dev tools
2.  Navigate to Augury 
3.  No scroll bar

Additional details:
- Tried uninstalling/reinstalling Augury extension, but no luck...
- Completely closed and reopened Chrome... no luck
- Restarted PC... no luck

![image](https://user-images.githubusercontent.com/9780297/55192123-c7fe5900-5171-11e9-9203-31007957cd54.png)

Same issue when closing console.... 
![image](https://user-images.githubusercontent.com/9780297/55192170-e2383700-5171-11e9-8d98-ac788a032901.png)

**Comment by jcletousey** [comment]
Same issue that [this one](https://github.com/rangle/augury/issues/1346).
Look in the comments for workarounds.

**Comment by carlsonaaron** [comment]
> Same issue that [this one](https://github.com/rangle/augury/issues/1346).
> Look in the comments for workarounds.

Thank you!
