### ISSUE TITLE
[State] area displays"No state to show"

### ISSUE THREAD

**Issue by 65min** [rangle/augury#1389]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): 1.23.0
Angular version (required): 7.2.13
Date: May 14, 2019
OS: Windows 10

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Steps to reproduce:

1.In [component Tree] View, Click the target Component
2.the [State] area displays"No state to show"
3.console show message "TypeError: toISOString is not a function"

Additional details:

**Comment by 65min** [comment]
![11111](https://user-images.githubusercontent.com/11242340/57680369-08516200-7660-11e9-83d7-757f5a781160.png)
![22222222](https://user-images.githubusercontent.com/11242340/57680371-08e9f880-7660-11e9-8fad-9ef7a9c0e26a.png)

**Comment by 65min** [comment]
when I add annotation "ViewChild", the component state cannot display normally. 
```
export class BizGoodsDetailComponent implements OnInit {
 
  ......

  @ViewChild('brand')
  public brand: AppMultipleChoiceComponent;

  ......
}

```

But when I remove annotation "ViewChild", the component state can display normally.

**Comment by AryanJ-NYC** [comment]
Dupe of https://github.com/rangle/augury/issues/1368

**Comment by 65min** [comment]
commenting out import "core-js/es6/date"; in polyfills.ts fixed it
