### ISSUE TITLE
Documentation for "no-name-route"

### ISSUE THREAD

**Issue by tcoz** [rangle/augury#1392]
Was very surprised that a number of searches did not turn up any clarity on what a "no-name-route" is about. I looked through a number of "debugging with..." articles, many of them show examples with "no-name-route" but nobody explains it (leading me to believe, the knowledge is scarce). 

There's even one in the augury rangle doc/demo, but no explanation for it at all:

https://augury.rangle.io/pages/guides/routes.html

![routes-lazy](https://user-images.githubusercontent.com/1213203/58327512-c8c40c00-7dfd-11e9-8208-db0dbed6767b.gif)

If you can, please post the explanation as a response (so I can explain it to my team, which is interested in the tool), and perhaps update the docs/demos to clarify. I've semi-surmised why it might appear, but from-the-source explanation would be valuable. 

Great tool, been using it myself for a while, thanks for the work here folks.

**Comment by feeloor** [comment]
Hi @tcoz,

Thanks for using Augury and thank you for suggesting this improvement.
One reason for this might be if you have a `redirectTo` route. I just created PRs to improve this and support a more clear text when it's a `redirectTo` route. 
I also created a PR to add some documentation around this in general. 

The PRs are referenced in this issue.

Thanks.
