### ISSUE TITLE
no diagram are displayed on my chrome browser

### ISSUE THREAD

**Issue by utisgroup** [rangle/augury#1394]
Augury: 1.23.0
Date: Sat, 15 Jun 2019 11:33:12 GMT
OS: Linux x86_64

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by GurpreetSingh5** [comment]
Facing the same. Any updates ?

**Comment by feeloor** [comment]
Hi @utisgroup @GurpreetSingh5,

Could you provide a bit more information to help us investigate this issue?
- What Angular version are you using?
- Could you provide screenshots?
- Could you provide steps to reproduce the issue?
- Could you provide an example repo or demo we can try?

Thanks.

**Comment by sumitarora** [comment]
Please provide more info and reopen the issue.
