### ISSUE TITLE
No State to Show - Augury doesn't track state

### ISSUE THREAD

**Issue by nick-beers** [rangle/augury#1395]
Augury: 1.23.0
Date: Tue, 02 Jul 2019 18:15:54 GMT
OS: Win32

Description of issue:
When attempting to run an angular app locally using ng serve from the base cli project startup, state is not showing in the panel for any selected components. If I close and reopen dev-tools I receive  an error only when Augury is installed.

```Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.```

I think these 2 issues may be connected, but either way Augury is unusable. A separate but possibly related note is that when attempting to select different components it causes chrome to slow down drastically and hang for roughly 5 seconds on larger component loads that it didn't used to do in the past.

Angular version (required): 7.2.15

**Comment by WhitWaldo** [comment]
Experiencing this in Angular version 8.1.1 as well.
