### ISSUE TITLE
Not showing with root component

### ISSUE THREAD

**Issue by yash2701** [rangle/augury#1403]
Augury: 1.23.0
Date: Sun, 15 Sep 2019 23:22:30 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by feeloor** [comment]
Hello @yash2701,
Do you mind providing a bit more information to help us investigate this:
- What version of Angular are you using?
- Do you have a repository or a demo app you can show us?
- Could you provide us steps how to reproduce this?
- Any screenshots?

Thanks.
