### ISSUE TITLE
Router tree not scrollable

### ISSUE THREAD

**Issue by gnowland** [rangle/augury#1405]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): Augury (1.23.0)
Angular version (required): Angular Version: 8.2.8
Date: 10/8/2019
OS: MacOS Mojave 10.14.6 Chrome Version 77.0.3865.90

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Router tree is not scrollable

Steps to reproduce:

1. Make app with many routes
2. Open routing tree Augury tab
3. Try to scroll to see overflowing routes

Additional details:
Inline CSS: `svg {max-height: 100%; }` being imported from basscss is preventing scroll.
Setting `bt-router-tree svg { max-height: none !important; }` enables scroll.

**Comment by yallen011** [comment]
@gnowland can you share the link to the github repo used to test the fix?

**Comment by gnowland** [comment]
Unfortunately it's a private repo - possibly this youtube video can suffice to demonstrate the fix?
https://youtu.be/TpwaXdEWOis

**Comment by gnowland** [comment]
re-built from latest master and router tree scrolls correctly - closing issue and PR!
