### ISSUE TITLE
zed plus naat studio ck

### ISSUE THREAD

**Issue by zedplusnaatsudio** [rangle/augury#1407]
Augury: 1.23.0
Date: Wed, 16 Oct 2019 16:17:21 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by sumitarora** [comment]
@zedplusnaatsudio Please provide more info on the issue.
