### ISSUE TITLE
ncaught (in promise): Error: Can't resolve all parameters for Addoffer2Page: ([object Object], [object Object], ?). Error: Can't resolve all parameters for Addoffer2Page: ([object Object], [object Object], ?).

### ISSUE THREAD

**Issue by esraariad** [rangle/augury#1408]
Augury: 1.23.0
Date: Sat, 19 Oct 2019 14:03:24 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by sumitarora** [comment]
@esraariad Please provide more info on the issue.
