### ISSUE TITLE
no component selected

### ISSUE THREAD

**Issue by VADDEPALLIPRAVEENKUMAR** [rangle/augury#1414]
Augury: 1.23.0
Date: Wed, 13 Nov 2019 06:27:38 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by feeloor** [comment]
@VADDEPALLIPRAVEENKUMAR Do you mind providing a bit more information to your issue? 
- Is there a repository we can reference? 
- Can you provided steps to reproduce the issue?
- Any screenshots?

Thank you!
