### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Neculaiovici** [rangle/augury#1419]
Augury: 1.23.0
Date: Sun, 17 Nov 2019 22:45:50 GMT
OS: Linux x86_64

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): 8.3.19

Steps to reproduce:

1.ng s

This application is running in production mode and therefore cannot be inspected using Augury.

If this is an Angular application, please rebuild your application in debug mode or remove the call to enableProdMode().

Additional details:

**Comment by yallen011** [comment]
Hi @Neculaiovici can you please provide more information about the issue your are experiencing by filling out the sections above that have the `--` in front of them as best you can. Also, can you please change the issue title to be a bit more descriptive. Unfortunately the title "Bug" is not very give much context. 

Thank you for taking the time to report and issue.

**Comment by sumitarora** [comment]
@Neculaiovici Please reopen the issue after providing more details.
