### ISSUE TITLE
chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js

### ISSUE THREAD

**Issue by alfbrizz** [rangle/augury#1427]
Augury: 1.23.0
Date: Sat, 30 Nov 2019 05:21:43 GMT
OS: MacIntel

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by feeloor** [comment]
Hey @alfbrizz,

In order for us to be able to properly investigate this issue, could you provide us with some extra information:

- What is the issue you are experiencing?
- What Angular version are you using? Are you running AOT or Ivy?
- Are you able to provide some screenshots?
- Can you provide details on how to reproduce the issue? Or a demo repo with example code to reproduce?

Thanks.

**Comment by feeloor** [comment]
Closing this issue for now. 
@alfbrizz please feel free to reopen this issue after providing more information.
