### ISSUE TITLE
Augury plugin not working at the Demo project ?!

### ISSUE THREAD

**Issue by D50000** [rangle/augury#1429]
Augury: 1.23.0
Date: Wed, 04 Dec 2019 07:08:03 GMT
OS: Win10 professional 64 bit

Demo test application:
https://augury.rangle.io/pages/guides/io-demo.html
>>> https://augury.rangle.io/examples/#/input-output

Description of issue:
I just start to study Angular and install Augury from official website. And i am step by step testing the plugin feature according to the guide. And i found out every online demo can't load the Augury correctly. 

Steps to reproduce:
https://augury.rangle.io/examples/#/input-output
https://augury.rangle.io/examples/#/dependency-injection
https://augury.rangle.io/examples/#/routes/home
https://augury.rangle.io/examples/#/modules
1. Launch any URL above and press F12 (dev mode). 
2. Click the "Augury" tag.
3. And the error message is out.
![image](https://user-images.githubusercontent.com/24785761/70122847-52596e00-16ac-11ea-946d-586a8b9a1406.png)

ps:
Additionally i test the angular official quick start project and it's fine.
![image](https://user-images.githubusercontent.com/24785761/70123251-37d3c480-16ad-11ea-9a65-acc3a6373d5e.png)
Not really sure what's going on. I think it is similar to issue #1426, but not exactly the same. Sorry, Hope these help.

**Comment by feeloor** [comment]
Hi @D50000,

This is because the examples have AOT enabled, we are doing a release to fix this. 

Thanks.

**Comment by feeloor** [comment]
@D50000 This should now be released and fixed. Feel free to reopen if you still experience issues.

**Comment by D50000** [comment]
Thanks @feeloor , it works perfectly now. Tricky AOT !

**Comment by janosAtZoneFox** [comment]
It works with the [demo project](https://augury.rangle.io/examples/#/input-output) but not with ours (Angular 7.1.4, no Ivy, AOT).
