### ISSUE TITLE
Please share your Ivy support and Augury v2 plans!

### ISSUE THREAD

**Issue by nickbullock** [rangle/augury#1459]
Hi!
Thanks for your your work and Augury.
Can you please share your plans about Augury+Ivy? I think community can help here with Ivy support.
Is it OK to open PR, will you take a look on it?

**Comment by sumitarora** [comment]
@nickbullock Ivy is supported in Augury version 1.25.0 we are working on improving it further.

**Comment by nickbullock** [comment]
@sumitarora thank you for quick reply, glad to hear.
