### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by andrewdamelio** [rangle/augury#21]
I suppose a logo is required first, but afterwards, maybe something aligned with this [spec](https://github.com/terinjokes/StickerConstructorSpec)?

**Comment by bertrandk** [comment]
Related to #28

**Comment by sumitarora** [comment]
Stickers yay!!!!!!!!! 
![20160509_081850](https://cloud.githubusercontent.com/assets/198247/15112877/036966d4-15bf-11e6-87b3-5f374806a58d.jpg)
