### ISSUE TITLE
tabs overflow

### ISSUE THREAD

**Issue by vanessayuenn** [rangle/augury#235]
Currently the tab labels wrap ![image](https://cloud.githubusercontent.com/assets/6842965/14091224/fb80e546-f50c-11e5-89aa-464243117a64.png)

Solution: implement the same behaviour as the native chrome devtool
![image](https://cloud.githubusercontent.com/assets/6842965/14091265/338c4caa-f50d-11e5-9a7a-733d6c6643af.png)

**Comment by aciccarello** [comment]
Do you think the names should also be shortened? I'm not sure how to keep the meaning clear though.

**Comment by vanessayuenn** [comment]
@aciccarello this is no longer a pressing issue since we have redesigned the UI :)

**Comment by igor-ka** [comment]
As per the planning meeting today, instead of the text wrapping and the containing row expanding in height to accommodate the wrap, we will keep the height and just add `...` for the part of the text that does not fit.
