### ISSUE TITLE
getAllAngularRootElements is not defined

### ISSUE THREAD

**Issue by inoabrian** [rangle/augury#245]
I downloaded the chrome extension and when I run batarangle I get an Uncaught ReferenceError : getAllAngularRootElements is not defined.

`Uncaught ReferenceError: getAllAngularRootElements is not defined`

```
Angular2Adapter._findRoot @ angular2.ts:144
Angular2Adapter.setup @ angular2.ts:57
(anonymous function) @ backend.ts:20
__webpack_require__ @ bootstrap 3d1b073…?314f:19
(anonymous function) @ bootstrap 3d1b073…?314f:39
__webpack_require__ @ bootstrap 3d1b073…?314f:19
(anonymous function) @ bootstrap 3d1b073…?314f:39
(anonymous function) @ bootstrap 3d1b073
```

**Comment by sumitarora** [comment]
@inoabrian which version of Angular2 you are using `getAllAngularRootElements` will work with Angular2 version beta.8 and greater.

**Comment by inoabrian** [comment]
@sumitarora I updated to beta.8 and now I am getting ng.probe is not a function.

**Comment by sumitarora** [comment]
@inoabrian Can you try with the latest version beta.12?

**Comment by inoabrian** [comment]
I have updated to beta.12 and am still getting the ng.probe is not a function error.

**Comment by sumitarora** [comment]
Can you make sure you are running angular 2 application in dev mode? If you type `window.ng.probe` in the console in dev tools you should see something. Try reinstalling the extension also.

**Comment by inoabrian** [comment]
@sumitarora  I can see the ng object.
and it has the following properties. 

```
Object.keys(window.ng)
["profiler"]
```

**Comment by sumitarora** [comment]
@inoabrian It should have following properties if you are running in dev mode with latest angular 2
```js
Object.keys(window.ng)
["probe", "coreTokens"]
```

**Comment by sumitarora** [comment]
@inoabrian Are you still getting this issue?

**Comment by inoabrian** [comment]
I have not used it since.
I will be trying again soon.

**Comment by sumitarora** [comment]
@inoabrian Are you still getting this issue else can you close the issue?

**Comment by inoabrian** [comment]
Sorry @sumitarora  for getting to your question late.
I'm not getting the error anymore I cleared it up. I was having an issue with chrome rejecting the extension so I uninstalled and followed the steps very closely.
