### ISSUE TITLE
Chrome disabling batarangle understanding this is an unsafe extension.

### ISSUE THREAD

**Issue by asadsahi** [rangle/augury#292]
After installing the extension by drag and drop into chrome extensions, it works. But after some time if you reopen the browser or restart the PC and then open chrome a popup opens after disabling this extension and we cannot enable it any more. We can remove and drag and drop extension again, but chrome permanently disables it saying this extension isn't in the chrome store and is unsafe.

Is there a way to make this extension persistent?

Thanks

**Comment by sumitarora** [comment]
@asadsahi we are working on putting it on chrome store soon that should resolve this issue

**Comment by asadsahi** [comment]
Ok, Thanks :)

**Comment by sumitarora** [comment]
@asadsahi Augury is now available on Chrome Store https://chrome.google.com/webstore/detail/augury/elgalmkoelokbchhkhacckoklkejnhcd you can install and this should resolve the issue.

**Comment by asadsahi** [comment]
Thanks @sumitarora . Have started using it. :+1:
