### ISSUE TITLE
Router tree visual bug

### ISSUE THREAD

**Issue by mobinni** [rangle/augury#296]
In the most recent build the lines of the router tree have a weird visual.  I don't know if this was a required change, but the lines fade over the names of the components.
![](http://i.imgur.com/1raOm1s.png)

**Comment by frederikschubert** [comment]
There is already an [pr](https://github.com/rangle/batarangle/pull/294) for it I think.

**Comment by mobinni** [comment]
Oh nice!

**Comment by vanessayuenn** [comment]
Closed by PR #294
