### ISSUE TITLE
Page refresh makes Batarangle to loose track

### ISSUE THREAD

**Issue by ivanatora** [rangle/augury#305]
Angular2 tab in Chrome Developer Tools stops tracking the app after one or few page refreshes. Its just showing the last opened windows/properties and stops refreshing. I get empty left panel and whatever was shown last in the right panel but I can't expand/collapse any items there.
![shot-2016-04-12-095214](https://cloud.githubusercontent.com/assets/1290560/14458161/0d11b7e8-00b8-11e6-8726-1858467dd67c.jpg)

If I close the whole browser tab and open it again, Batarangle works fine again, until a page refresh. If I close the Developer Tools before refreshing, Batarangle works fine again.

I'm using batarangle-484.crx with beta14

**Comment by ivanatora** [comment]
Just to drop a line that the issue is still persistent in the augury-590.crx release.

**Comment by sumitarora** [comment]
@ivanatora We are working on it should be merged soon in master

**Comment by ivanatora** [comment]
Hi, guys. Is it already in master? Is the Chrome store build the latest version? That issue is still reproducible there.

Can I cooperate you in any way in order to resolve this issue? I'm on Ubuntu 16.04, Version 50.0.2661.86 (64-bit)
