### ISSUE TITLE
npm ERR! Failed at the batarangle@0.0.2 pack script './crxmake.sh'.

### ISSUE THREAD

**Issue by pearljamik** [rangle/augury#306]
> ./crxmake.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gwk736\\AppData\\Roaming\\npm\\node_
modules\\npm\\bin\\npm-cli.js" "run" "pack"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! batarangle@0.0.2 pack: `./crxmake.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the batarangle@0.0.2 pack script './crxmake.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the batarangle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./crxmake.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs batarangle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls batarangle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Inform\bat\augury\npm-debug.log

**Comment by sumitarora** [comment]
@pearljamik you would need [cygwin](http://www.cygwin.com/) on windows to build the project and run the shell scripts

**Comment by pearljamik** [comment]
using cygwin, bash-4.1 I get the same error
[npm-debug.txt](https://github.com/rangle/augury/files/215134/npm-debug.txt)

**Comment by sumitarora** [comment]
@pearljamik Can you try running it manually `sh crxmake.sh` just figuring out which command works on windows?

**Comment by pearljamik** [comment]
$ sh crxmake.sh
crxmake.sh: line 6: $'\r': command not found
C:\Program Files\nodejs\node.exe: bad option: -v

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, faq,
    get, help, help-search, i, init, install, install-test, it,
    link, list, ln, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\kulisek\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.3 C:\Program Files\nodejs\node_modules\npm
crxmake.sh: line 9: $'\r': command not found
crxmake.sh: line 14: $'\r': command not found
: invalid signal specificationT
crxmake.sh: line 20: $'\r': command not found
cp: target 'temp'$'\r''/'$'\r' is not a directory
crxmake.sh: line 25: $'\r': command not found
crxmake.sh: line 34: syntax error near unexpected token `$'\r''
'rxmake.sh: line 34: `(cd "$dir" && zip -qr -9 -X "$cwd/$zip" .)

**Comment by pearljamik** [comment]
Hi, I partially reduced a problem by running dos2unix on the file, but there is still an error:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gwk736\\AppData\\Roaming\\npm\\node_
modules\\npm\\bin\\npm-cli.js" "run" "pack"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! batarangle@0.0.2 pack: `./crxmake.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the batarangle@0.0.2 pack script './crxmake.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the batarangle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./crxmake.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs batarangle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls batarangle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Inform\bat\augury\npm-debug.log

**Comment by pearljamik** [comment]
sh crxmake.sh:

v5.10.1
3.8.6
key.pem doesn't exist.
Loading 'screen' into random state - done
Generating RSA private key, 1024 bit long modulus
.++++++
.........++++++
e is 65537 (0x10001)
crxmake.sh: line 34: zip: command not found
crxmake.sh: line 37: batarangle.zip: No such file or directory
crxmake.sh: line 49: printf: Users: invalid number
ls: cannot access batarangle.sig: No such file or directory
cat: batarangle.sig: No such file or directory
cat: batarangle.zip: No such file or directory
Wrote batarangle-.crx
Wrote file
Fin.

**Comment by pearljamik** [comment]
I was missing zip package. Almost there:
gwk736@GWK736-02 /cygdrive/c/Inform/bat/augury
$ ./crxmake.sh
v5.10.1
3.8.6
./crxmake.sh: line 49: printf: Users: invalid number
./crxmake.sh: line 50: printf: Users: invalid number
Wrote batarangle-.crx
Wrote file
Fin.

**Comment by sumitarora** [comment]
@pearljamik Is it working for you now if yes Can you close the issue.

**Comment by sumitarora** [comment]
@pearljamik going to close the issue seems to be working fine
