### ISSUE TITLE
Empty Angular 2 tab on Developer Tools tab in Chrome

### ISSUE THREAD

**Issue by ixsander** [rangle/augury#308]
Not 100% sure if this is a bug. I installed the latest build from http://rangle.github.io/batarangle-io/ (0.0.2) and tried it on a simple hello world Angular 2 app. All I am getting is an empty window as below.
![screen shot 2016-04-13 at 5 48 41 pm](https://cloud.githubusercontent.com/assets/4730252/14512866/1a765f2c-01a0-11e6-87df-03e32f66f8cd.png)

I have Angular Beta.14 + webpack in development mode. Am I missing anything here?
I reloaded my app after Batarangle installation. I also noticed that the Extension's icon from Chrome is greyed out.

Thanks,

**Comment by sumitarora** [comment]
@ixsander There were some issues with build generated using CI if you download the latest one which is from http://batarangle.io/download.html?new which is `batarangle-494.crx` and install that you should be good.

**Comment by ixsander** [comment]
ya. That fixed my problem. Should I just use your link going forward for new builds?

Thanks!
