### ISSUE TITLE
Please publish Augury to Chrome Web Store

### ISSUE THREAD

**Issue by Hongbo-Miao** [rangle/augury#314]
Thanks for this great app. Please publish Augury to Chrome Web Store.

![screenshot](https://cloud.githubusercontent.com/assets/3375461/14594889/ad6fbc2c-0508-11e6-9c2a-d9130d85d581.png)

Right now, Chrome always disable this extension automatically, then it cannot be enabled again.
I have to uninstall and install again to use it.

**Comment by vanessayuenn** [comment]
@Hongbo-Miao: we're still working on making this available via chrome store, but this should happen very very soon now. Stay tuned!

**Comment by sumitarora** [comment]
Already being tracked: https://github.com/rangle/augury/issues/297

**Comment by Hongbo-Miao** [comment]
thanks for letting me know!!
