### ISSUE TITLE
Batarangle not initializing properly

### ISSUE THREAD

**Issue by OClement** [rangle/augury#358]
I've had this problem hapening quite frequently before, then it seemed to have been fixed with one of the build/chrome canary combo (I don't recall which build sorry)

Now I'm having this issue again, all of a sudden; No errors shown anywhere
I updated to the latest build just now and the issue persists (augury-622)

![batarangle](https://cloud.githubusercontent.com/assets/814862/14895893/12be75a8-0d49-11e6-8ce0-ebb1cde75a85.png)

The component/router trees stay empty no matter what I try ( I tried all that would be dictated by common sense, yes :P)

**Comment by sumitarora** [comment]
@OClement which version of angular you are using?

**Comment by OClement** [comment]
I'll need to check to be sure
Should beta 13

I'll update to beta 17 tomorrow 

O.

**Comment by sumitarora** [comment]
@OClement we currently support beta.15 right now so try it. We will soon be updating to beta.17.

**Comment by OClement** [comment]
Ok will keep you posted

Interesting fact:
Before today, it was working fine; no changes at all in stack, nor did I updated Batarangle

Also, it's not impossible which version is currently installed; it *might* be 15; will confirm tomorrow 

O.

**Comment by OClement** [comment]
So, Version Previously Installed (that Batarangle was working with until yesterday), was Beta 12

Updated to Angular 2 Beta 17 just now; While a few breaking changes crash my app, Batarangle/Augury (what's with that name?) seems to work now

Closing

**Comment by OClement** [comment]
My bad, issue is definitely still present under Beta 17 / Augury 266
Will wait until you officially support beta 17 and see if this helps; if not, I'll re-open this issue

**Comment by sumitarora** [comment]
@OClement We haven't updated yet to support beta.17 we are working on that still.

**Comment by OClement** [comment]
Yes I figured that much; That's why I said I'll wait before opening the issue again, if needed :)
