### ISSUE TITLE
"Cannot read property 'root' of undefined" console error when viewing router tree

### ISSUE THREAD

**Issue by sstorie** [rangle/augury#376]
Are there specific requirements for having the router tree work (like the rc release)? I am using it with beta.17, but when I view the router tree tab I just get a blank window and see this error in the console:

`Cannot read property 'root' of undefined`

Am I missing something obvious?

**Comment by sumitarora** [comment]
@sstorie It works if you are running Angular 2 app in dev mode. We currently support beta.15. It should work with beta.17.

**Comment by sstorie** [comment]
Hrm...I'm running it in dev mode but still see the issue. Is there any way I can dig out and provide more details? Like some sort of extension inspector or anything?

**Comment by sumitarora** [comment]
you can check in the chrome inspector `window.ng` it should exist for applications in Angular 2 and should print this.
> Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
window.ng
Object {coreTokens: Object}

**Comment by sstorie** [comment]
Yeah, that's what I see:

![2016-05-04_16-58-26](https://cloud.githubusercontent.com/assets/3630784/15030771/eee1478e-1219-11e6-8862-ec89f43ef4ce.png)

But if I switch to the router tree I get the error I mentioned:

![2016-05-04_16-58-47](https://cloud.githubusercontent.com/assets/3630784/15030792/05fa2d1e-121a-11e6-9f4f-02d7fe759291.png)

**Comment by sumitarora** [comment]
ohh for router there is one configuration you need to do in the app we are working on removing that. My bad didn't read properly in your main app component if you just declare router variable as below you should be able to see the router. We are working on fixing it though. Similar to this: https://github.com/rangle/augury/blob/dev/example-apps/kitchen-sink-example/source/containers/kitchen-sink.ts#L102 after that just close augury reload app and reopen augury you should see it.

`constructor(private router: Router) {`

**Comment by sstorie** [comment]
Awesome, thanks! That was the issue.

**Comment by sumitarora** [comment]
Thanks we will soon be updating so it works without configuration 😄

**Comment by djohnston08** [comment]
@sumitarora Did this ever get added?  I am still seeing this using rc4

**Comment by sumitarora** [comment]
@djohnston08 It was not the issue its just configuration you need to make in your application to make router tree work in Augury.

**Comment by djohnston08** [comment]
I get that.  I meant your comment about making it work without the configuration.  Is that still going to happen?

**Comment by sumitarora** [comment]
yes our aim is to make it work there are changes being made in the new router once all is done we will target on extracting information out.

**Comment by djohnston08** [comment]
Ok, sounds great.  Just wanted to check.  I completely understand the wait on the router.

**Comment by jameskleeh** [comment]
I was getting this in a unit test because I replaced Router with a mock. I removed the mock and instead injected the router into the test and called `spyOn(router, 'navigateByUrl')`

**Comment by ishwaryaPaderborn** [comment]
@jameskleeh Could you please let me know how you made it work?

**Comment by hallya** [comment]
Same situation than @jameskleeh , working for me like this
```
  let router: Router;
  [...]
  imports: [ RouterTestingModule ],
  [...]
  router = TestBed.get(Router);
  [...]
  spyOn(router, 'navigate');

  component.someFunction();

  expect(router.navigate).toHaveBeenCalled();
```
