### ISSUE TITLE
How to Run Angular 2 function in chrome debug console???

### ISSUE THREAD

**Issue by bluejaye** [rangle/augury#402]
Dear 

I met a problem, need to use JS to run function inside Angular 2. In angular debug mode, I know that I can call ng.probe() to return angular component instance.   but ng.probe() is unavailable in production mode. 

Do you know any other way to access angular 2 function please?

Cheers
Jay

**Comment by vanessayuenn** [comment]
Hey @bluejaye, you can use `$a` in console to get a particular debug element once you have Augury open and running. However, this is also only available when your Angular 2 app is running on dev mode.

**Comment by bluejaye** [comment]
Hi Vanessa

Thank you for replying. My purpose is to access angular 2 function without
any tools help.

It seems that there is no easy way to do it.

On Saturday, 21 May 2016, Vanessa Yuen <notifications@github.com> wrote:

> Hey @bluejaye <https://github.com/bluejaye>, you can use $a in console to
> get a particular debug element once you have Augury open and running.
> However, this is also only available when your Angular 2 app is running on
> dev mode.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rangle/augury/issues/402#issuecomment-220643511>
>


-- 

Best Regards,

Jay
