### ISSUE TITLE
If using ngrx/router router tree is not available.

### ISSUE THREAD

**Issue by Anshdesire** [rangle/augury#406]
If using ngrx/router for routing.
Extension is not able to show **router tree** .

**Comment by sumitarora** [comment]
@Anshdesire Is there a prototype that I can check for configurations?

**Comment by Anshdesire** [comment]
If this is new feature and not implemented yet. I'd like to contribute in this feature.

**Comment by sumitarora** [comment]
@Anshdesire Can you inject the `router` as a dependency to your main component similar to this https://github.com/rangle/augury/blob/dev/example-apps/kitchen-sink-example/source/containers/kitchen-sink.ts#L102 and check if it shows the router graph.

**Comment by Anshdesire** [comment]
Tried @sumitarora. Nothing happens

**Comment by xorgy** [comment]
Support for third-party routers is not a priority at the moment. Though perhaps in the future.
