### ISSUE TITLE
Wanted feature: retry/refresh to get angular2 components

### ISSUE THREAD

**Issue by pjordaan** [rangle/augury#413]
On my page I have a script loader to load my angular 2 component. Because of that if I have the web inpsector open before the script loader loaded my angular 2 component, there is no information shown.

I seem to miss a refresh icon/button, so I can see my component in Augury if for whatever reason my angular 2 component is not loaded yet.

**Comment by sumitarora** [comment]
@pjordaan Is there an example that you can provide?

**Comment by pjordaan** [comment]
my apology for not responding earlier. Since we integrate angular2 components in our existing app we are forced to load it with the head.js loader and it's loaded after domReady.  If the augury tab is open when I refresh the page I see no angular2 component at all.
I could imagine you can't handle all ways of loading angular2, unless you are constantly polling so a refresh or 'find angular2 components' button seems like an easy fix...

I could see if I can make a small app where it goes wrong. I work on proprietary code, so can't show the actual code atm.

**Comment by xorgy** [comment]
@pjordaan This may work with the latest release (as of today 1.1.3).

Do verify that this is fixed and get back to us. :- )

**Comment by igor-ka** [comment]
@pjordaan can you confirm if this is still happening with the latest version of Augury (1.2.3 as of today)?

**Comment by pjordaan** [comment]
sorry for my lack of response. I have not had any issues anymore.
