### ISSUE TITLE
Augury:----Does not render a component under component tree when i refresh the page. 

### ISSUE THREAD

**Issue by priyathorwat** [rangle/augury#415]
Everytime I need to do "ng-serve" and run the app then the component will be displayed in a component tree. But  Once I refresh the page, component tree is blank.The angular cli version that i am using is--- 1.0.0-beta.5.

**Comment by sumitarora** [comment]
@priyathorwat Which version of Augury are you using? This happens with all the apps or the once using angular cli only?

**Comment by priyathorwat** [comment]
yes it is the same behavior with all the apps. I have tested with sublime,brackets ,visual studio code with  angular-cli...how can i solve it?

**Comment by sumitarora** [comment]
@priyathorwat Are you getting the same behaviour here https://augury.angular.io/demo/ Are you using the latest version `1.0.1` of Augury?

**Comment by priyathorwat** [comment]
No  this link https://augury.angular.io/demo/ works fine. yes i am using the current version of augury
