### ISSUE TITLE
Augury only detects 1st Angular app

### ISSUE THREAD

**Issue by nexus-uw** [rangle/augury#418]
Hello,

I have a page with 3 independent Angular apps on it. When I open the Augury tab, I only have access to app that was bootstrapped first.

Is this something that Augury will plan on supporting?

Thanks,
Simon

**Comment by vanessayuenn** [comment]
@nexus-uw Yup this is definitely something we're working on supporting in near future.

**Comment by clbond** [comment]
Support for multiple applications on the same page was added in https://github.com/rangle/augury/commit/dfa410b6545f24e3cef87af775b4e9651ffad13f

**Comment by xorgy** [comment]
According to @nexus-uw this issue is manifesting again.

**Comment by clbond** [comment]
Resolved by https://github.com/rangle/augury/pull/769. This was just a CSS styling problem
