### ISSUE TITLE
Augury should save the dark theme settings

### ISSUE THREAD

**Issue by sumitarora** [rangle/augury#423]
**This is an issue especially good for first-timers!**

#### 🐞 The Problem

This issue is related to #420.
We would like the user to be able to persist their theme setting for Augury.
The relevant code snippet from [`src/frontend/frontend.ts`](https://github.com/rangle/augury/blob/dev/src/frontend/frontend.ts#L162)
```
  themeChanged(newTheme) {
    this.theme = newTheme;
    // TODO: do stuff here to persist the theme selection
  }
```

#### 📖 What you need to know

Angular 2, typescript. Probably relevant resources:
 - [Chrome Storage](https://developer.chrome.com/extensions/storage)
 - [Events in Angular 2](https://toddmotto.com/component-events-event-emitter-output-angular-2)

#### 🔂 Steps to contribute
- [x] ~~claim this issue: (assign yourself or comment below)~~ claimed by @JayKan 👏  
- [x] mentor: @vanessayuenn
- [ ] [Setup & run Augury locally](https://github.com/rangle/augury#building--installing-locally)
- [ ] Implement the fix
- [ ] Write the tests for the solution
- [ ] Start a Pull Request. Mention this issue in the description (e.g. `resolves #423`).

#### 💖 Thank you!
Thanks so much for wanting to contribute! This issue is especially perfect for first time contributor. Please contact us on [Slack](https://augury-slack.herokuapp.com/) if you have any questions. :)

**Comment by JayKan** [comment]
I would like to tackle this issue :)

**Comment by vanessayuenn** [comment]
@JayKan all yours! check off the boxes as you go :)
