### ISSUE TITLE
Augury stops working after adding a workspace folder in chrome dev tools

### ISSUE THREAD

**Issue by martenbiehl** [rangle/augury#424]
Hi!
Thank you a lot for this great tool!

I found the following issue: Augury does not display any information after a workspace folder has been added to chrome dev tools.

To reproduce:
Go to Augury tab in dev tools and see that it works.
Go to sources tab, right click on your page, choose "add folder to workspace" and select the local project folder.
Reload the page and go to augury tab in dev tools. See that it is now empty.

Best regards
Marten

**Comment by clbond** [comment]
Marten, unfortunately I cannot reproduce this issue. Is there any chance that you could provide some additional information? What application were you debugging? Would you be able to give me access to the source so that I could reproduce your experience exactly?

**Comment by sumitarora** [comment]
@clbond I believe it was due to Augury not listening to the dom updates which was fixed in my PR Can you try to replicate it on the released version or on the master branch.

**Comment by clbond** [comment]
Sumit, thank you for the note. I was not able to repro on the released
version nor on the dev branch. I think I need more info from the user about
what they were doing. Actually probably the most helpful thing would be to
get the project source in its entirety if that's a possibility. I was
trying to repro on the Augury demo project.

**Comment by martenbiehl** [comment]
Hi Chris,

thanks for your reply. It was while I was doing the angular tour. And I can reproduce it with the public version from John Papa: https://github.com/johnpapa/angular2-tour-of-heroes
If not let me know what more information you need. I'd be curious to find the cause of this.

Best
Marten

**Comment by sumitarora** [comment]
@martenbiehl I have tried it with https://github.com/johnpapa/angular2-tour-of-heroes it seems to be working fine I am not able to reproduce it, I added the whole folder in sources. Do you remember the exact flow what were you trying to implement it.

**Comment by martenbiehl** [comment]
Sorry guys, I was able to reproduce this a few times but now everything works. Sorry to waste your time. This works beautifully now. Thanks a lot for the extension.
