### ISSUE TITLE
Choose which providers to hide, instead of which providers to show in the Providers accordion.

### ISSUE THREAD

**Issue by clbond** [rangle/augury#427]
I have spoken with Igor and he has mentioned several times that he wishes to implement a change in the way that we load properties and data from Angular. Right now we are hardcoding the names of the properties we are interested in, which means that when properties get added or removed by the Angular team, we do not display them until one of our devs has a chance to update our static list.

**Comment by igor-ka** [comment]
As per my investigation with @sumitarora, this issue will be addressed by #662 instead and is not relevant anymore.
