### ISSUE TITLE
settings menu should close when click outside of it

### ISSUE THREAD

**Issue by vanessayuenn** [rangle/augury#436]
![image](https://cloud.githubusercontent.com/assets/6842965/16135784/e0f4c7c6-33f3-11e6-8166-ff5a433bb119.png)

TODO: write more details here

**Comment by clbond** [comment]
This is not fixed, reopening

**Comment by ericjim** [comment]
I'll look into it.

**Comment by ericjim** [comment]
#477 only address this issue partially. There are two edge cases that need to be addressed:
* Clicking on the `augury-header` does not hide the menu when the menu is revealed.
* Clicking on the scroll bars does not hide the menu when the menu is revealed.
