### ISSUE TITLE
Color Settings popup should be consistent with theme

### ISSUE THREAD

**Issue by sumitarora** [rangle/augury#459]
![screen shot 2016-06-23 at 4 19 27 pm](https://cloud.githubusercontent.com/assets/198247/16383514/62775b12-3c53-11e6-8965-48dd0e471e5c.png)

**Comment by ericjim** [comment]
Will something like this work? Note, I have scrollbars always present on my machine, so you'll see white stripes where overflow is present.
<img width="1437" alt="screen shot 2016-06-27 at 11 55 31 am" src="https://cloud.githubusercontent.com/assets/1329167/16386280/229ee7e8-3c5e-11e6-972b-4a7f95aeb778.png">

**Comment by igor-ka** [comment]
@ericjim @sumitarora the white stripes do not work. I'd rather keep it the way it is for now if it means having white stripes in there

**Comment by ericjim** [comment]
@igor-ka I will clarify. The whitestripes have always been there, they are only very visible as a result of a setting that I've enabled on macOS. This should not stop us from merging in this PR. @danielschifano can you comment on what things we can do to prevent the bars from appearing. My theory is that CSS is using `overflow` in some mode.

<img width="645" alt="screen shot 2016-06-27 at 4 38 27 pm" src="https://cloud.githubusercontent.com/assets/1329167/16394935/996e60e8-3c85-11e6-99f4-4f6eaa88b48a.png">

**Comment by sumitarora** [comment]
@igor-ka As @ericjim mentioned they are the default scrolls in Mac on browser. I don't have them enabled which is default behavior I believe. If we need to fix the scrollbars we should create another issue specific to that.

**Comment by igor-ka** [comment]
@sumitarora @ericjim I thought that the scrollbars are "side effects" of this code. Otherwise yes, another issue makes total sense. In which case, :shipit:

**Comment by sumitarora** [comment]
Closing issue PR already merged: https://github.com/rangle/augury/pull/463
