### ISSUE TITLE
Does not work for Chrome Extension built using Angular2

### ISSUE THREAD

**Issue by golear91** [rangle/augury#497]
I have a chrome extension built with Angular2 (RC4) and the augury tab in developer tools shows nothing when I open it for my popup page (built with Angular2) 
![image](https://cloud.githubusercontent.com/assets/16123225/17043374/d9244926-4f6a-11e6-9c77-6ef46f4733c4.png)

**Comment by sumitarora** [comment]
@golear91 Is there a way I can install the extension and check?

**Comment by peterblazejewicz** [comment]
I have the same problem: regular Chrome (Version 51.0.2704.103) and Chrome Canary:
- Augury 1.0.4

**Comment by golear91** [comment]
@sumitarora sorry for the late response.
you can install it here: https://chrome.google.com/webstore/detail/personal-shopping-assista/dhelmjcpoddajfaldodimlaehbalhgag

**Comment by andrewlo** [comment]
I think the root cause is that [Content-scripts](https://developer.chrome.com/extensions/content_scripts) do not seem to get run on the popup.html of Chrome extensions. Augury uses a content-script to read the component tree information of the page it's inspecting.

**Comment by xorgy** [comment]
Given that Chrome does not run content scripts in content owned by other extensions, I see no way that this can be fixed.

Perhaps we should mark this wontfix.
