### ISSUE TITLE
Performance view prototype

### ISSUE THREAD

**Issue by bertrandk** [rangle/augury#50]
**Feature goal**: The user should be able to assess the impact of change detection on each component at-a-glance.

@abmohan – we're probably looking to prototype the best way of doing this.

/cc @winkerVSbecks

**Comment by mobinni** [comment]
I think it would be cool to incorporate useful data:

- Total heap size
- Heap usage
- Total components counted
- Render performance
- # of observables (subscriptions)

**Comment by sumitarora** [comment]
Few other suggestions that came up in the discussions were:-
* Rendering time of each of the components would be great
* How long a route takes for render as well as the resolutions time

**Comment by bertrandk** [comment]
Do we know if any of this stuff is already available through WTF?

**Comment by sumitarora** [comment]
Not yet I am just exploring options for these

**Comment by xorgy** [comment]
This feature is no longer planned, though we may reopen it at a later date.
