### ISSUE TITLE
As an Augury user I want to provide my feedback on the application so that I can vocalize my thoughts as they occur​

### ISSUE THREAD

**Issue by amitafr** [rangle/augury#506]
Create a fixed call to action in Augury for users to provide feedback from within the application.
- Fixed CTA at bottom of Augury with a feedback icon + title displaying "Feedback"
- Upon clicking a text box with an action to, "Tell us your thoughts"
- Submit button to send response 
- Feedback to user, "Thank you for your feedback" once response is submitted

**Comment by JinSY** [comment]
After discussing:
- add feedback button to top bar 
- add a button to submit a bug
- look into best way of collecting feedback (public google form api?)
