### ISSUE TITLE
Get rid of 'HTML like' display of component tree

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#551]
As part of the recent change, the rendering of component tree was changed to be displayed in a more 'HTML like' fashion. Specifically, using the triangular brackets and having both the opening an closing tags.

Need to remove the triangular brackets as well as the closing tags from the component tree for a more concise display of the structure.

**Comment by clbond** [comment]
The closing tags are removed by https://github.com/rangle/augury/pull/561/. But I am not sure about removing the brackets. It is going to look weird just having "a text='foo' url='bar'" isn't it? Instead of <a text="foo" url="bar"> ?

**Comment by igor-ka** [comment]
@clbond in 1.0.5 and prio we have it in the following way `a (text="foo" url="bar")`

**Comment by xorgy** [comment]
This is resolved now.
