### ISSUE TITLE
Components of the same type are collapsed/expanded together

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#553]
Component of the same type on the component tree get collapse and expanded together, if they are all on the same level within the tree. The problem manifests itself when the component is expanded or collapsed. 

Also, the state accordion shows the state for the first component of the type in the same level of the tree, no matter which component of the type is selected.

**Comment by clbond** [comment]
@igor-ka I think this may fix it: https://github.com/rangle/augury/pull/560. Not absolutely sure since I haven't been able to reproduce it though (but I saw it happen on your machine)

**Comment by clbond** [comment]
Can you try https://github.com/rangle/augury/pull/561/ and see if it fixes this issue? If it doesn't fix the problem, if you could find another app that reproduces the issue that would be awesome

**Comment by clbond** [comment]
This has long since been fixed
