### ISSUE TITLE
Component tree should be expanded to 3 levels deep by default

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#558]
By default the component tree should be expanded only 3 levels deep. Currently, all the nodes of the component tree are expanded fully.

**Comment by clbond** [comment]
Resolved by commit https://github.com/rangle/augury/pull/597/commits/7241597cbbf4fa9b8ef9159d2eca287e71ab875a

**Comment by xorgy** [comment]
Confirmed resolved by #597.
