### ISSUE TITLE
Support RC6

### ISSUE THREAD

**Issue by xorgy** [rangle/augury#563]

**Comment by xorgy** [comment]
[RC6 has now been released](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc6-2016-08-31)

**Comment by michael34** [comment]
angular2.ts:71 Uncaught TypeError: rootNgProbe.inject is not a function

**Comment by xorgy** [comment]
@michael34 Thanks, we have a tracking branch for the current work. If you have an idea as to why the Component Tree is rendering blank, that'd be a real help. :- )

**Comment by michael34** [comment]
@xorgy Component Tree isn't blank for me. It just does not update. Is this what you are talking about?

**Comment by clbond** [comment]
@michael34 `inject()` has been removed from DebugElement in recent Angular 2 builds. Augury 1.0.5 depends on this function. However we have done a lot of refactoring recently and this issue has been fixed in the latest code & therefore will be addressed in the next release.
