### ISSUE TITLE
Dependency arrow in Injector Graph does not start at the center of the dependent node.

### ISSUE THREAD

**Issue by xorgy** [rangle/augury#622]

**Comment by stevenkampen** [comment]
<img width="366" alt="screen shot 2016-11-28 at 4 20 21 pm" src="https://cloud.githubusercontent.com/assets/898763/20676139/a7bb3944-b586-11e6-9564-73ae1891f8f9.png">

**Comment by stevenkampen** [comment]
No longer an issue.
