### ISSUE TITLE
ionic 2

### ISSUE THREAD

**Issue by realappie** [rangle/augury#625]
Does augury support ionic 2, because I tried inspecting my ionic 2 application that uses angular 2 & typescript and it didn't work.

**Comment by sumitarora** [comment]
@realappie Which version of angular you are working on? If you run ionic in dev mode using `ionic serve` it should work.

**Comment by xorgy** [comment]
@realappie In theory, this should work if the application is run in dev mode. We have seen it work with some simple Ionic 2 use cases and would be interested to see why it fails for you.

**Comment by vandna-thakkar** [comment]
for me its also same. augury works with my angular 2 application but not ionic2 application

**Comment by Olgagr** [comment]
I have the same issue. I'm using ionic-angular version 2.0.0-beta.10 (Angular 2.0.0-rc.3)

**Comment by xorgy** [comment]
@Olgagr We do not support Angular 2.0.0-rc.3 officially, only the final release.

**Comment by realappie** [comment]
@xorgy What do you mean 'only the final release'? Im confused, is RC3 not considered the 'final release'?

**Comment by pierre-H** [comment]
I tried with : 

>  ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.3.0
Xcode version: Not installed

and it doesn't work : I've got this error `Cannot read property 'name' of undefined`.

**Comment by rocco** [comment]
any news on this for anyone here? does not seem with ionic@2.1.18. thanks!

**Comment by ryanki1** [comment]
Having upgraded to the following configuration:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 1.0.0
OS: Windows 7 SP1
Node Version: v6.9.5

Augury doesn't appear to be mirroring correctly the status of my page stack as I click through the app :-(

**Comment by realappie** [comment]
This is not the case anymore @sumitarora, you can close this.

**Comment by rajinder-yadav** [comment]
@realappie Thanks for reporting the problem is gone for you.

@pierre-H @vandna-thakkar can you please let us know how things are on your end? If you're are seeing an issue, please provide a demo app to help us investigate this issue.
