### ISSUE TITLE
Augury "cache" problem

### ISSUE THREAD

**Issue by jmachnik** [rangle/augury#626]
Having Augury on, gives me 

> ORIGINAL EXCEPTION: TypeError: _.mapObject is not a function
> ORIGINAL STACKTRACE:
> TypeError: _.mapObject is not a function

It's an underscore function, and when I debug my ng2 app in IDE I don't get that error. Also application runs successfully on Firefox,Safari and any other browser + in Chrome private browsing. Clearing browser data / cache doesn't help. Does Augary keep some app data somewhere and affect debugged app?

**Comment by NoTra** [comment]
Same problem here ! Augury seems to load lodash and overwrite our underscorejs functions ("_")

**Comment by clbond** [comment]
This is addressed by this PR: https://github.com/rangle/augury/pull/630
