### ISSUE TITLE
Router Tree is stripped to root only, loadChildren does not update

### ISSUE THREAD

**Issue by Delagen** [rangle/augury#628]
I have dynamic parts of routing, but route tree is stripped and contains no-name-route only
![untitled](https://cloud.githubusercontent.com/assets/783335/18392778/b759cd98-76bb-11e6-890e-0e0b7e6bc826.png)

**Comment by sumitarora** [comment]
@Delagen Is there an example we can look at or can you create one?

**Comment by Delagen** [comment]
Sad but project is private, and I don't know how implement it in plunker. I think any example with loadChilder angular router feature should be suitable

**Comment by xorgy** [comment]
@Delagen We have a test case where we see this issue, and are looking into it.

Thanks for the report.

**Comment by Delagen** [comment]
@xorgy Thanks to you. You are doing our work easier.

**Comment by stevenkampen** [comment]
@Delagen What would you like/expect to happen here? Is it just that you want to see the module name that will be loaded (easy)? or are you expecting that we specifically preload the complete route tree (including these lazy loaded modules)?

@xorgy Any thoughts?

**Comment by Delagen** [comment]
@stevenkampen Can you update RouterTree to actual state and display it on loadChildren event?

**Comment by stevenkampen** [comment]
@Delagen So you're saying show full details of lazy loaded routes *that have been loaded*, and just the stub info (module name) when they are not yet loaded? That seems like a good compromise to me. @xorgy @igor-ka, Any thoughts?

**Comment by Delagen** [comment]
@stevenkampen Yes. I think we must display actual state of tree. Loading full tree at start will be bad idea, cause it will make some actions which developer doesn't wait to happen.

**Comment by stevenkampen** [comment]
@Delagen No worries. I'm working on this solution now.

**Comment by stevenkampen** [comment]
This was resolved by #738
