### ISSUE TITLE
Expand/Collapse Icon do not work

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#640]
Steps to reproduce:

1) Go to the demo kitchen sink app
2) Pick a component with State and collapse/expand it
3) Select Counter component in the InputOutput section
4) Go back to the component selected in step 2 above, note that State expansion/collapsing does not respond.

This happens in the latests dev branch.

**Comment by clbond** [comment]
I can't reproduce this. Can you stop by my desk and show me

**Comment by clbond** [comment]
If you open the nested Dev Tools (to debug Augury itself) is there an exception in the console? If so does it say something about highlighting?

**Comment by igor-ka** [comment]
The issue is addressed for me
