### ISSUE TITLE
Enhancement to Augury Popup

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#650]
1. Add Usability Survey instead of Contributing button in Augury (https://rangleio.typeform.com/to/GrdAGu)
2. Get rid of extra white space currently present in the pop-up.
3. Explore if possible to get the version of Augury out of `manifest.json` programatically.

**Comment by xorgy** [comment]
There is an API (described at https://developer.chrome.com/extensions/runtime#method-getManifest) which can be used to query the manifest, which contains the version number which can then be inserted into the DOM where the version number is.

Inline JavaScript is disallowed in extensions, so you will need to put it in a separate file.
