### ISSUE TITLE
Property edits in the state editor sometimes don't apply.

### ISSUE THREAD

**Issue by MrCroft** [rangle/augury#657]
Can't edit component property.

Steps to reproduce:

1. `ng new myapp`
2. `cd myapp`
3. `ng serve`
4. Open Chrome developer tools and go to the Augury tab. In the component tree, click the AppComponent.
5. In the properties on the right, notice the "title" property with the "app works!" value
6. Click either on the property name ("title") or it's value, and the field becomes editable (thus suggesting it is editable).
7. Change it to anything and press enter. Notice it reverts to the initial value once you press enter.

I've also set up a local server and build the app with "ng build" and served my app through apache, instead of `ng serve`, but it makes no difference.

```
Augury: 1.1.3
angular-cli: tried with 1.0.0-beta.11-webpack.8 or 1.0.0-beta.11-webpack.9-4
Angular: either 2.0.0-rc.6 or rc.7 (haven't tested on rc.5 or lower)
Google Chrome: 53.0.2785.113 m (64-bit)
OS: Windows 10 Pro
```

**Comment by xorgy** [comment]
Thanks for the report, currently we have an issue with editing state in OnPush components. Check where it says "Change Detection: " in the info panel right below your component name, if that says "OnPush" then this is a known issue. If it says "Default" then it seems we might have a new one.

**Comment by MrCroft** [comment]
@xorgy 
Unfortunately, it is "Default".

**Comment by xorgy** [comment]
I don't see this issue on some test applications but I'll take a look at what you suggest.

Thanks.

**Comment by xorgy** [comment]
@MrCroft So I am indeed seeing an issue. It's not that you can't edit the property, but it seems that it only succeeds about half the time. I'm going to update the title of this issue to match that. This is going to be fun to debug.

**Comment by xorgy** [comment]
As a nuance, it only seems to fail when the value you enter is the same as the original value, I think I know why this would manifest.
https://drive.google.com/a/rangle.io/file/d/0BwfHP4-tCgx-azMxZGRlNXB4dG8/view

**Comment by MrCroft** [comment]
Weird thing: If I set ChangeDetectionStrategy to be OnPush, Augury still says "Default" (but this is ONLY happening with rc.7 - so I don't think it's relevant here. It does say "OnPush" if I use rc.6).

Further more, back to the "Default" change detection strategy, if I change the "title" property in a later event/method, it surely gets updated in the view, but it doesn't get updated in Augury:

```
export class AppComponent {
    title = 'app works!';

    // Placed a button in my template
    // <button (click)="changeTitle()">CHANGE TITLE</button>
    changeTitle() {
        this.title = "does not get updated in Augury"; // < the value of the title property doesn't get updated in Augury
    }
}
```

I've just tried the above code while simply "ng serve" with latest angular-cli (1.0.0-beta.11-webpack.9-4) and latest 2 versions of Angular 2 (rc.6 and rc.7). It behaves the same with both rc.6 and rc.7 (removed node_modules folder and ran `npm cache clean` between changing versions, so I would be sure).

Hope this helps, I can't think of anything else that might actually help you to narrow it down.
Just an Angular 2 newb here :) learning

**Comment by xorgy** [comment]
That seems like a separate issue, it's possible that they've changed the reflect metadata between rc.6 and rc.7. 😞

**Comment by xorgy** [comment]
This is a build of the extension from the state of our development branch.
https://1253-41743300-gh.circle-artifacts.com/0//tmp/circle-artifacts.o49SEp7/augury-1253.crx

If you remove Augury, download this file, then drag the file directly into a window at chrome://extensions then try the issue again, we will be on the same page. We should do a release today if the issue is partially resolved.

**Comment by MrCroft** [comment]
Sorry for the delay, I was having trouble installing the build you gave me. Chrome issues.

So... with the above build (and the "Default" change detection strategy) for both rc.6 and rc.7:
    - changing property value in Augury works and value instantly gets updated in the view (which this issue was about)
    - changing the property value in my changeTitle() method, doesn't update the value in Augury while having the Developer Tools open. If I close it and open it again, then I see the new title. But this would be another issue I think.

**Comment by xorgy** [comment]
@MrCroft RE-PS: Basically it doesn't update the application when you enter the original value of the field after editing it. So for example if it started with 'app works!' and you changed it to 'app works!!', then tried to change it back to 'app works!' it would still show 'app works!!' after you submit.

Anyway, this seems like a separate issue. And no, this release will sadly not address the inability to edit OnPush components. There is a separate issue logged for that.

Anyway, I'm going to consider this closed, since your original bug no longer seems to appear. I'll see if we can push out a proper release in the mean time to address this.

**Comment by MrCroft** [comment]
I tell too long stories :) 
Definitely, the bug I've actually opened this issue for is fixed by that build.

Thank you!

**Comment by MrCroft** [comment]
Sorry to come back on this, I should have been more careful the first time.
At that moment I was only careful enough to check what I initially observed: that the value didn't get updated in the component, once I changed it in Augury.
And then said it's all good, without also checking what @xorgy noticed: that it doesn't get updated when you change the value back to what it was initially.
It seems that's still happening (Default change detection strategy).

Unless this is already mentioned again in some other open issue, would you reopen this or should I open a new issue?

You can notice this in the same repo I gave as an example for another issue I've just opened: https://github.com/MrCroft/lazy (see HomeComponent)

```
Augury: 1.2.1
Angular: 2.0.1
os: win32 x64
Google Chrome: 53.0.2785.116 m (64-bit)
```

And I feel the need to add: Thank you for Augury! 😃
