### ISSUE TITLE
Clicking on the view source button for component clears augury

### ISSUE THREAD

**Issue by sumitarora** [rangle/augury#666]
Steps to reproduct:
1. Open augury.angular.io/demo
2. Open Augury in devtools
3. Select any angular component
4. Click `viewsource` link to view component source
5. Come back to augury tab nothing is shown until you refresh.

![image](https://cloud.githubusercontent.com/assets/198247/18538357/208fe6a8-7adb-11e6-8b31-f8560ef3f1d2.png)

**Comment by leocaseiro** [comment]
Hi,
I'm having the same issue. 
Will 1.1.4 be published on chrome webstore soon?

Thanks

**Comment by sumitarora** [comment]
@leocaseiro Yes Once we have finished upgrading to Angular 2.0.0 we will release new version to chrome webstore. Meanwhile If you want you can use dev build `https://1265-41743300-gh.circle-artifacts.com/0//tmp/circle-artifacts.binP9hN/augury-1265.crx`

**Comment by leocaseiro** [comment]
Hi @sumitarora, I've just seen that the version 1.2.0 was realised and I still can't see data on Augury.

Could you please assist me how to fix that? Do I need to clear some kind of deep cache? Thanks
