### ISSUE TITLE
Support for angular-upgrade

### ISSUE THREAD

**Issue by jtomaszewski** [rangle/augury#680]
Simple question: does it work with angular-upgrade (that means: with angular 2 apps that are being run with `@angular/upgrade` [UpgradeAdapter](https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html) ?

Doesn't work for me at this moment, but I don't know if it's a fault on my side, or it's just not supported?

**Comment by igor-ka** [comment]
@jtomaszewski at this moment we just didn't look into supporting this use case. However, we will probably end-up looking into supporting UpgradeAdapter in the near future. 

Let's keep this issue open and I will keep you in the loop here once we have something more concrete.

**Comment by jtomaszewski** [comment]
Yeah, I'd be happy to help. At this moment I can't even access my components from the browser's console (f.e. by `ng.probe($0).components`). 

I wonder if is it the case for all the angular-upgrade apps, or just my problem?

**Comment by igor-ka** [comment]
hey @jtomaszewski it would be definitely possible for you to help. I would love to accept a PR against a clearly defined github issue on this. 

You can start by reading [this](https://github.com/rangle/augury/blob/dev/CONTRIBUTING.md), after that if you need help to get started with the code and how to debug Auguryt, you can reach to me on Augury slack and I can put you in touch with one of our devs to get you up to speed on all of that.

We are in the process of updating the documentation this and next week, but it's a but out of date currently.

**Comment by guojenman** [comment]
@jtomaszewski ng.probe works for me on individual component root nodes but like you, augury does not.

**Comment by jtomaszewski** [comment]
Yeah, I discovered recently it works if you target a ng2 component and then use `ng.probe($0).componentInstance` or `ng.probe($0).context` if it's a child.

So it's not that bad, we would just need to find a way to "grab all existing ng2 components" and put them in Augury.

**Comment by igor-ka** [comment]
@jtomaszewski i've changed the title of this issue to reflect this as a feature that we will be working on. Let us know if you still want to pick it up yourself.

**Comment by mgol** [comment]
Note that Angular `2.2.0-rc.0` now includes a new static version of `@angular/upgrade` which will be a preferred version. The old one stays in the library as-is but since it doesn't work with AOT and the static one works both with JIT & AOT modes, people should generally prefer the latter.

**Comment by rajinder-yadav** [comment]
Tested with Angular 2.2.0 using a Angular 1.5 app using UpgradeAdaptor, variable ng is not available. Opened a upstream ticket on Angular: https://github.com/angular/angular/issues/12873

**Comment by mgol** [comment]
It seems Augury works fine if you use the new static upgrade adapter. See [the upgrade guide](https://angular.io/docs/ts/latest/guide/upgrade.html) for more info.

**Comment by mobinni** [comment]
Waiting for issue to be resolved by Google for AOT mode.

**Comment by rajinder-yadav** [comment]
We can use this app: https://github.com/vsavkin/ng1ng2router

**Comment by mattwilson1024** [comment]
Is there any update on this? Augury doesn't seem to work for me even with the static upgrade adapter. My bootstrap code is:

`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UpgradeModule } from '@angular/upgrade/static';
import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.body, ['myapp'], {strictDi: true});
});
`

**Comment by stevenkampen** [comment]
@mattwilson1024 Can you share an example of your project so I can look at your case specifically?

My first reaction is that this might prove too sticky for Augury to help with, but it's hard to tell what people would like, or are expecting, to work. If you can share a repo with me I will use it as the model and validate a potential solution.

**Comment by mattwilson1024** [comment]
@stevenkampen I've created an example hybrid app which demonstrates my setup here: [https://github.com/mattwilson1024/angular-hybrid](https://github.com/mattwilson1024/angular-hybrid)

This is a hybrid app consisting of an AngularJS page with downgraded Angular components used within. There is a little information about the components in [README.md](https://github.com/mattwilson1024/angular-hybrid/blob/master/README.md)

See [screenshot 1](https://github.com/mattwilson1024/angular-hybrid/blob/master/augury/augury-1.png), [screenshot 2](https://github.com/mattwilson1024/angular-hybrid/blob/master/augury/augury-2.png) and [description of the Augury issue](https://github.com/mattwilson1024/angular-hybrid/blob/master/augury/augury.txt)

It would be great to be able to use Augury to inspect any Angular 4 components on the page (e.g. view their inputs and outputs). In this example, that would be `CharacterListComponent` and `CharacterDetailComponent`.

Thanks and I hope this helps

**Comment by stevenkampen** [comment]
@mattwilson1024 My thinking is that that use case would be a little far from Augury's purview. At least I think our support for Angular Upgrade should start with supporting Angular (2+) applications that contain upgraded AngularJS components (that's my main concern right now).

@igor-ka @sumitarora What are your thoughts on this? I'm thinking we'd have no way to parse the application to resolve Angular 2+ components (or building something would mean essentially adding support for AngularJS). Maybe you guys have more insight because of your experience with Batarangle.

**Comment by SanderElias** [comment]
@stevenkampen I think the @mattwilson1024 use case is quite common. A lot of projects are already built in AngularJS, and adding downgraded Angular components is a common way to extend the app with new functionality. 

In a number of cases, it's the first step to migration, but also, there might be some apps that will never be completely migrated, but extended with Angular. 
It would be nice when augury would be usable in those cases.

**Comment by th0r** [comment]
So as I understand there is no plan to support @mattwilson1024's use case?

**Comment by mattwilson1024** [comment]
It's a shame this isn't being supported - as @SanderElias said I imagine this approach for migrating is fairly common especially for large apps like the one I am working on where migration is likely to be quite a long process.

I'd be interested to hear if anybody comes up with any workarounds or finds alternative tools that can be used in this scenario.

**Comment by igor-ka** [comment]
@mattwilson1024 and @th0r supporting this use case would mean essentially supporting AngularJS in addition to Angular. This would be a relatively large effort to achieve as it would mean that Augury would have to support both (quite different) frameworks, and add a lot of complexity to the codebase as a result. 

At this point in time, we would like to focus our resources on making Augury a great tool to use with Angular 2+. 

We might revisit this later and in the meantime, if the solution to this is simpler than we think, we would be more than happy to accept PRs and collaborate with anyone in the community to implement this functionality.

**Comment by leff** [comment]
> At this point in time, we would like to focus our resources on making Augury a great tool to use with Angular 2+.

While that makes sense for you and other contributors to augury @igor-ka, it does undermine the larger Angular project's contention that "there is an upgrade path from angularjs to angular." I mean, upgrading an angularjs app to angular is the obvious use case for the upgrade module.  Upgrading is hard enough; doing it without tools is a terrible experience. 

So I humbly request that you and your fellow contributors run this decision past the folks in the larger angular project. If the decision is still "no", please talk to them about changing the messaging around upgrades. It should change from "You can upgrade angularJS apps" to "Avoid upgrading angularJS apps."

thanks

**Comment by knaos** [comment]
Plus one on this
