### ISSUE TITLE
Improve Kitchen Sink Demo Application

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#683]
As of now the following has been discussed to be implemented under this issue.

1) Make kitchen sink a multi-root application
2) Find and remove functionality that was deprecated in Angular 2.0.0 released
3) Think of better examples (at least better named), to be fully defined as we go.

**Comment by rajinder-yadav** [comment]
Milestone created, Epic currently has 3 stories as issues. We can change things around as we move forward.

https://github.com/rangle/augury/milestone/14

**Comment by rajinder-yadav** [comment]
Closing, we we're taking this with milestone, "Kitchen Sink code update with new guide"
