### ISSUE TITLE
$a console command sometimes throws an error

### ISSUE THREAD

**Issue by hilaryhacksel** [rangle/augury#684]
Steps to reproduce:
1. Open a new tab and make sure your developers tools window is closed.
2. Navigate to your angular app (or https://augury.angular.io/demo/#/).
3. Open your developers tools and pick the Augury tab.
5. Click on some Angular component.
6. Type $a into the console and press enter
-> produces the error: Uncaught ReferenceError: $a is not defined(…)

However, $a is defined if your developer tools is open before navigating to the angular app.

**Comment by xorgy** [comment]
Interesting.

**Comment by orizens** [comment]
hi @hilaryhacksel 
I investigated this issue.
It seems like the 'window' referenced within the [consoleReference function](https://github.com/rangle/augury/blob/dev/src/backend/backend.ts#L279) is not the actual window of the relevant tab. 
This is caused of a limitation with content scripts as [described here](https://developer.chrome.com/extensions/content_scripts) 
It seems like the proper solution would be to use postMessage to interact with the Tab's window object and set the '$a' property there.

**Comment by stevenkampen** [comment]
Ok, I am able to reproduce this reliably now, and to do that I had to include the following steps:
1. Make sure you are signed OUT of Chrome.
2. Open the dev tools with "Inspect Element", rather than CMD + Shift + J.

A cache refresh was not required but the quitting chrome and opening again is.

**Comment by stevenkampen** [comment]
@orizens I think I've found at least the superficial cause of this error. At least it worked for me and for @hilaryhacksel. It might make you laugh but in the end it was just that the incorrect console "context" is selected. It should be "top" as in the screenshot below, but I found that mine. Please confirm if this is describes your situation also.

<img width="639" alt="screen shot 2016-10-07 at 4 09 09 pm" src="https://cloud.githubusercontent.com/assets/898763/19195508/d89e54f2-8ca9-11e6-99eb-ee833c73093b.png">

I'm thinking now about how to mitigate this annoyance with some proactive hinting in the console.
