### ISSUE TITLE
postmessage events causing high cpu usage

### ISSUE THREAD

**Issue by bmayen** [rangle/augury#694]
I have an app that communicates with an iframe via postmessage events. My event listener is getting flooded with "AUGURY_INSPECTED_APPLICATION" messages. CPU at 100% due to this.

**Comment by igor-ka** [comment]
@bmayen we will look into this. Would you be able to provide us with an isolated repo/site where this is reproducible?

**Comment by mobinni** [comment]
@bmayen Is this issue still occurring?

**Comment by bmayen** [comment]
Sorry, was on a tight schedule and had to simply disable Augury for that project. Am no longer active on that. If the issue comes up again, I will update.

**Comment by mobinni** [comment]
Okay, for now I will close to issue as it has not been reported any other time. If it comes up again we'll investigate further.

**Comment by sergkr** [comment]
I'm getting this whenever I open developer tools on any page, even if it is not using Angular.

**Comment by tal-abziz** [comment]
steps to reproduce:
- create an angular app
- add this HostListener to app.component.ts
```typescript
@HostListener('window:message', ['$event'])
onFrameMessage(event: MessageEvent) {
  console.log({event});
}
```
- open augury from dev tools
- enjoy 250% cpu

stackblitz example: https://stackblitz.com/edit/angular-fjstb9
augury version used: 1.23.0

**Comment by hmicn** [comment]
I can still experience the same issue in 2019.
The steps to reproduce are exactly the ones described by tal-abziz

**Comment by sumitarora** [comment]
@hmicn Which version of Augury you are on? We just release new version yesterday. Can you check on that. Thanks

**Comment by hmicn** [comment]
Hi @sumitarora thanks for the reply. I currently use Augury 1.24.0. I'll check on the new version and I'll get back to you

**Comment by shenjo** [comment]
same issue. disabled the chrome extension will be ok

**Comment by mdilshan** [comment]
Still I experience the same issue. Using postMessage. I'm listening to the message and send a network request to the API. It worked perfectly on localhost. Then I run the prod build on GCP compute instance, it start to run infinite amount of time. 

when the callback of the listener execute for the first time, it receive the message that I sent from postMessage, after that it just receive an object with a property,
`{messageSource : "AUGURY_INSPECTED_APPLICATION, ...'}`. This triggers the callback and sending infinite amount of network request with that object. 

When I disable the Augury, it works without any problem.
