### ISSUE TITLE
Augury freezes chrome periodically.

### ISSUE THREAD

**Issue by j2jensen** [rangle/augury#727]
I have a small application, and one page of the application seems to freeze up every 30 seconds or so. There's no real pattern to the amount of time it takes in between freezing, nor the length of time that it remains frozen, but typically after 5-15 seconds the UI becomes responsive again. When I don't have Augury enabled, this does not happen, and a CPU profile during one of these freezes shows that most of the time is being spent inside of Augury's `backend.js` file.

![image](https://cloud.githubusercontent.com/assets/453495/19205751/93b93346-8ca1-11e6-8eda-a0d520dda325.png)

![image](https://cloud.githubusercontent.com/assets/453495/19205787/c8cd88fc-8ca1-11e6-84d0-0eda23e3572f.png)

**Comment by sumitarora** [comment]
Might be related to this one: https://github.com/rangle/augury/issues/694

**Comment by igor-ka** [comment]
@j2jensen thanks for bringing this up. I was wondering if you could provide a link to a repo with reduced case for this? Alternatively, we can have a remote session with you and debug this issue together.

Let us know which one works bets. We will be more that happy to work together to resolve this issue.

**Comment by j2jensen** [comment]
Unfortunately, this repository has proprietary code and is not publicly
available. I would be willing to try to debug this with you over screen
share. Can you email me at j2jensen@gmail.com to work out the logistics?

Cheers,

James

**Comment by clbond** [comment]
@j2jensen I believe this has been fixed by this PR: https://github.com/rangle/augury/pull/748. I've attached a crx to this message. I would love to hear whether this solves the performance issue you observed! Thank you very much.

Package with the fix: [augury-1412.zip](https://github.com/rangle/augury/files/544636/augury-1412.zip)

**Comment by j2jensen** [comment]
I can't reproduce the issue with the .crx file you provided, so I'm guessing that means you fixed it. Thanks!

**Comment by igor-ka** [comment]
@j2jensen thank you for your help. I am closing this issue as it has been resolved by PR #748
