### ISSUE TITLE
Integrate with Angular Batscanner (or build equivalent)

### ISSUE THREAD

**Issue by frederikschubert** [rangle/augury#762]
[This](https://github.com/douglasduteil/angular-batscanner) tool gives some great insights into the performance of angular applications. It might be worth considering to integrate some of them into augury?

**Comment by stevenkampen** [comment]
Need to investigate if it's possible & wise to implement batscanner, or just the same functionality.

**Comment by igor-ka** [comment]
relates to #998

**Comment by andrewthauer** [comment]
This sort of feature(s) is covered by https://github.com/rangle/augury-labs.
