### ISSUE TITLE
Guide is outdated... says 2.0.0-rc.4 is latest supported

### ISSUE THREAD

**Issue by baloodevil** [rangle/augury#774]
The [Augury Guide](https://augury.angular.io/guides/) says the latest Angular version supported is 2.0.0-rc.4 instead of 2.0.0 (or something more recent).  If this issue needs to be posted on the Angular documentation site instead, since the url of the docs is angular.io, please let me know.

**Comment by igor-ka** [comment]
@baloodevil thanks for pointing this out. We will be consolidating and updating the documentation shortly.

**Comment by mobinni** [comment]
Blocked, not able to put out a clean build

**Comment by mobinni** [comment]
@ericjim Posted a question on the Harp github, waiting for response.
