### ISSUE TITLE
Be able to see a count of all available scopes/components in play at a given time

### ISSUE THREAD

**Issue by concertcoder** [rangle/augury#79]
Being able to see a count of all the different components being used at a given time would be awesome.  So example: 1 root-component, 1 header-component, 1 body-component, 5 collapsible-component, 2 item-component, 1 footer-component, etc.

This would be good for seeing what components are used the most for performance sake and if there's and fishy business happening in larger applications.

@igor-ka as we talked about

**Comment by bertrandk** [comment]
Some of these issues might be addressed by #84.

**Comment by sumitarora** [comment]
@vanessayuenn @igor-ka @bertrandk We can have the Count of components of each type. What is the reasoning to display the count? Do we still need it?

**Comment by bertrandk** [comment]
@sumitarora Maybe not. This might be something WTF does already.

**Comment by rajinder-yadav** [comment]
Same as 872

**Comment by andrewthauer** [comment]
This sort of feature / usecase is best covered by https://github.com/rangle/augury-labs.
