### ISSUE TITLE
Using Immutable breaks Augury

### ISSUE THREAD

**Issue by Rebolon** [rangle/augury#812]
One property of my component is Immutable from immutableJs library.
Augury try to access the property and its own properties but it crash because it's impossible and then it display the following error : 

    zone.js:158 Uncaught TypeError: Cannot read property 'name' of undefined(…)

without Immutable Augury can access person.age 
    
    this.person =  {age: 1}

but with Immutable Agury cannot, because it should do : person.get('age')

Maybe it could test if it's Map object per example, and then retreive keys with this : story.keySeq().toArray() to be able to use the getter

**Comment by mobinni** [comment]
Hi there,

Could you possibly provide an example repo to test this on?
This would help us a lot in debugging and fixing the issue.

Thank you for reporting this issue.

Regards
Mo

**Comment by Rebolon** [comment]
I don't have the code here but this could help you : 

import * as Immutable from 'immutable';
...
export class MyComponent {
   public story = Immutable.Map({age: 12, name: "me"});
}

Just use your component in your app-root

**Comment by mobinni** [comment]
@Rebolon Hey, I'll look into this today! Thanks for reporting it

**Comment by rajinder-yadav** [comment]
@Rebolon I've followed your instruction and see no issues. In fact I am able to view the immutable property in Augury. Can you please test with the latest version of Augury.

FYI: 
I simply create a angular-cli app.

![screen shot 2017-02-27 at 1 49 30 pm](https://cloud.githubusercontent.com/assets/439226/23374739/956b3834-fcf3-11e6-93d7-e28bd76351e9.png)
