### ISSUE TITLE
Enhancement: Show message when no routes exist.

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#817]
We should show a message rather than a blank tab page under 'Router Tree' when no routes exist.

Something like, "The Application have no routes defined."

**Comment by stevenkampen** [comment]
This message could cover the case where no routes exist, and also the case where the router was not injected as per the readme (by having an extra note that reminds the user that prior to v2.3.0, the router must be injected into the route component, as per the readme).

**Comment by rajinder-yadav** [comment]
Some initial image for light and dark mode, text is shown using light grey.

Just need to craft a message, add link to more readme info.

![no-routes](https://cloud.githubusercontent.com/assets/439226/23237196/49c07c0e-f92a-11e6-88fe-84f70ee97078.png)

![no-routes-dark](https://cloud.githubusercontent.com/assets/439226/23237199/4dc8ae3e-f92a-11e6-9e7c-ca90a6ddeab6.png)

**Comment by rajinder-yadav** [comment]
Here is the current implementation, I added a link to the readme for older version.

![no-routes](https://cloud.githubusercontent.com/assets/439226/23272113/04cd432c-f9c8-11e6-848e-c9ac468872c8.gif)
