### ISSUE TITLE
Support router registration a la https://github.com/angular/angular/pull/12696

### ISSUE THREAD

**Issue by stevenkampen** [rangle/augury#829]
As of angular version 2.3.0-beta.0, the router should be registered on `ng.coreTokens`, so we can take advantage of that and not require the router injection into the root component.

**Comment by mobinni** [comment]
Like the provider tokens, angular now supports getting the router component from the coreTokens injector. If it's there you will get a component reference, otherwise it will return "Null?". Provide support for this feature, with fallback for pre-2.3 router.
