### ISSUE TITLE
Error messages are black in dark mode

### ISSUE THREAD

**Issue by mgol** [rangle/augury#833]
If you enable Chrome DevTools dark mode and try Augury on an app with production mode enabled, you'll see an error message in black text over a dark background; not very readable.

<img width="362" alt="screen shot 2016-11-28 at 18 38 34" src="https://cloud.githubusercontent.com/assets/1758366/20679151/075fe56c-b59a-11e6-8408-6aa52ed80d57.png">

**Comment by mobinni** [comment]
@mgol Thanks for the bug report, will look into it!
