### ISSUE TITLE
Track whether app / component is stable

### ISSUE THREAD

**Issue by studds** [rangle/augury#873]
Is there a way view whether a given component is stable (ie. `ngZone.isStable === true`)? This would be a real boon when debugging apps.

**Comment by rajinder-yadav** [comment]
Hi @studds, can you elaborate with practical examples of when this would be helpful to you? Thanks!

**Comment by studds** [comment]
Mostly for when I'm trying to work out why I have to run protractor tests with `ignoreSynchronization = true` (https://github.com/angular/protractor/issues/3349). I understand how to fix the problem, but I can only guess where it is.

**Comment by stevenkampen** [comment]
@studds Out of interest, what usually is the issue when you find it? Just a bug in the logic? I'd love to see a contrived example so we can understand your use case. It sounds useful, but I'd like to make sure we're solving your problem properly.

**Comment by andrewthauer** [comment]
This seems like an old issue.You could check out https://github.com/rangle/augury-labs to see if that covers the required use case.
