### ISSUE TITLE
Injector graph on hover

### ISSUE THREAD

**Issue by mobinni** [rangle/augury#877]
Currently the injector graph has injection points with the names below the bubbles.
It would be nice to set cut-off points for text, because if the name of a class/service/... is too long it could potentially lead to unreadable UI. 

When text reaches the cut-off point it will initiate an on-hover pop-over that will contain the full name. 

Potential addition: angle the text at 45 degrees.

**Comment by igor-ka** [comment]
@stevenkampen @mobinni i think we don't need the diagonal labels (those can overlap as well) after all.

Let's just add a `...` at the end of an injectable that is too long, and show the full name when hovering over the corresponding circle.

what do you think?

**Comment by mobinni** [comment]
Sounds good!

**Comment by stevenkampen** [comment]
@igor-ka Yeah, ellipsis make sense there.

**Comment by stevenkampen** [comment]
We have simple ellipses now, but still require some hover menu to show the full text and also other context (NgModule origin, etc).

**Comment by stevenkampen** [comment]
This is solved now by #899
