### ISSUE TITLE
Augury shows 2 NgForm when there is 1

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#883]
<img width="427" alt="screen shot 2016-12-14 at 2 30 39 pm" src="https://cloud.githubusercontent.com/assets/439226/21197630/211227b4-c20a-11e6-8497-42e5caef79c6.png">

**Comment by rajinder-yadav** [comment]
Also happen with elements, we see multiple NgModel and Array when there is only one per element.
![screen shot 2016-12-16 at 11 36 55 am](https://cloud.githubusercontent.com/assets/439226/21270337/3479791c-c384-11e6-9edd-f310bd7bf685.png)

**Comment by tyllrb** [comment]
Can't seem to re-produce this issue. From the screenshots it looks like you're testing this with the sample demo app for forms on the augury.io website? I used the same application and only one `NgForm` appears in the instance providers list. Same with `NgModel`, and `Array` on the inputs, only one appears now.

**Comment by stevenkampen** [comment]
This does look like it went away somehow. Will reopen if we see it again.
