### ISSUE TITLE
We should rename 'State' under Properties, it's a class 'member'.

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#888]
Is classical Object Oriented languages, a class variable is called a `member` and a class function is called a `method`. 

JS mixes this up with calling them either a `property` or a `field`, likewise TypeScript does an even poorer job of naming anything in a class, a member.

I recommend we rename `State` to `Members`. It is strange to call something a State which has a emit button. A state is associated with a value.

<img width="668" alt="screen shot 2016-12-16 at 4 00 37 pm" src="https://cloud.githubusercontent.com/assets/439226/21278714/be82bb66-c3aa-11e6-9d93-7df7d3e4efb8.png">

**Comment by rajinder-yadav** [comment]
This should actually be turned into a general UI scrub to use consistent names we can all agree upon based on Angular and Javascript.

**Comment by stevenkampen** [comment]
We're going to talk to the core guys about this and other names.

**Comment by rajinder-yadav** [comment]
Let's compile a list of things we'd like to correct with our suggestions and go over with Igor Minar.
