### ISSUE TITLE
Delete kitchen sink project

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#896]
Kitchen sink project was moved to the augury-examples repo, this issues serves as a reminder to remove dead code from the augury repo.

**Comment by rajinder-yadav** [comment]
After discussing with Steven, he would like to keep kitchen sink around for his use, we don't need to make it public through the website that's all.

I also will copy over the Augury linting rule that not also need to be pulling in.

**Comment by rajinder-yadav** [comment]
Added default linting rule generated by tslint and removed rule for quote style. This fix all the error Steven reported he was seeing in the new repo.

**Comment by stevenkampen** [comment]
:shipit:
