### ISSUE TITLE
Dynamically loaded components do not get displayed

### ISSUE THREAD

**Issue by amb-it-ion** [rangle/augury#90]
Components loaded with [DynamicComponentLoader.loadNextToLocation](https://angular.io/docs/ts/latest/api/core/DynamicComponentLoader-class.html) are currently not getting included into batarangle.

Great work otherwise!

**Comment by vanessayuenn** [comment]
@amb-it-ion dynamically loaded components, with the exception for loadAsRoot components, should work fine with batarangle now with the latest update.

**Comment by xorgy** [comment]
@amb-it-ion Do you think that this issue has been addressed?

**Comment by clbond** [comment]
This was fixed a long time ago

**Comment by QuentinFchx** [comment]
@clbond are you sure ?
For instance, I can't see dialogs created through @angular/material in the Augury inspector

**Comment by jh-code** [comment]
This is not working again, due to Angular deprecating the DynamicComponentLoader. They now use the ComponentFactoryResolver.

**Comment by jh-code** [comment]
This does not work anymore. Angular doesn't use DynamicComponentLoader anymore either, they use the ComponentFactoryResolver.

**Comment by Draccoz** [comment]
Hello lads. Sorry to disappoint you but Augury does **not** show `MdDialog`s. In the screenshot below I have an `MdDialog` with `SessionsForm` component. Wanted to debug it (displays incorrectly) but nope, not happening.
![image](https://user-images.githubusercontent.com/4731061/27469724-3caadee4-57f1-11e7-8aa1-c04b9b1195b1.png)

**Comment by bryanrideshark** [comment]
I am also experiencing this.

![image](https://user-images.githubusercontent.com/6453594/27801984-a4571df8-5fe6-11e7-9315-9ccddea37c74.png)
