### ISSUE TITLE
Router Tree broken in angular 2.4.1

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#900]
Router tree is not working for my routes demo app, nothing shows up.
It still works for the kitchen sink app.

**Comment by stevenkampen** [comment]
@rajinder-yadav Can you provide the source of this app you're testing with? Do you inject the router into the route component?

**Comment by rajinder-yadav** [comment]
It's just basic angular routing, nothing fancy. I've merged my demo app, you can pick it from:

https://github.com/rangle/augury-examples/

**Comment by stevenkampen** [comment]
@rajinder-yadav Until we complete #829, the router still needs to be injected into the root component and called `router`, for augury to be able to parse it. Any chance you want to make this work? ;)

**Comment by rajinder-yadav** [comment]
Talked with @stevenkampen, and looks like all we need to do is at code to do a simple check and then fallback if that fails.

I'll take a look at this issues.

**Comment by stevenkampen** [comment]
@rajinder-yadav I think we should close this and track the improvement on #829

**Comment by rajinder-yadav** [comment]
Closing as dup!
