### ISSUE TITLE
Injector Graph prevent tabs from switching

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#918]
1. Click on inject graph
2. Click on a component
3. Click on an injector not to make on status info at bottom display something
4. Click on the status info so it has focus
5. Click on a devtools tab

Result: you will not be able to switch between tabs. 

(*) Something the status info fails to show up.

![injector-graph](https://cloud.githubusercontent.com/assets/439226/21998612/e7477b24-dc03-11e6-81fa-e27977318f3a.gif)

**Comment by stevenkampen** [comment]
@rajinder-yadav It looks like the issue actually happens when displaying the extra info panel (you can see "NgModule:" is blank. Can you point me towards this repo code so I can see why that is?

**Comment by rajinder-yadav** [comment]
https://github.com/rajinder-yadav/augury-examples
Work off the branch task-14-demo-app-routes
