### ISSUE TITLE
Exception thrown on Microsoft Office online (and probably other sites, too)

### ISSUE THREAD

**Issue by renehamburger** [rangle/augury#920]
Logging into www.office.com fails, if the Augury extension is enabled, even when the Chrome developer tools are closed. An exception is thrown in [backend.ts#175](https://github.com/rangle/augury/blob/2ca189796ed821c9030fdd1a4c400e17b91f6d9b/src/backend/backend.ts#L175):
`Object.defineProperty(window, selectedComponentPropertyKey, { value: noSelectedComponentWarningText });` and the subsequent call of `_defineProperty()` in Zone.js. The error log is 'Uncaught TypeError: $a is not a function'.

The consequences of this exception is that the settings item in the top nav bar disappears and that none of the remaining items show context menus on click. There are probably other issues, too.

**Comment by renehamburger** [comment]
The cause seems to lie outside of the Augury extension. I close this for now.

**Comment by stevenkampen** [comment]
@renehamburger I've tried to recreate this but I am able to log in without issue. Is there anything special you're doing? At what point exactly do you see the error? If you could provide a screencast of the whole thing happening, that might be helpful.

<img width="957" alt="screen shot 2017-01-30 at 7 32 16 pm" src="https://cloud.githubusercontent.com/assets/898763/22447887/5e4a6ce8-e723-11e6-956e-33168cb34be3.png">

**Comment by rajinder-yadav** [comment]
I took a look at this and was also not able to reproduce this error.

**Comment by renehamburger** [comment]
Thanks, @rajinder-yadav. This seems to have been resolved in the past couple of weeks in Augury. There is no clash with `$a` anymore.
