### ISSUE TITLE
Show attributes for DOM input element

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#947]
We don't show the attributes for `input` fields in the component tree:

<img width="302" alt="screen shot 2017-01-31 at 11 35 30 am" src="https://cloud.githubusercontent.com/assets/439226/22474409/b180d52e-e7a9-11e6-9e8f-6440866a5b1e.png">

We should show their attributes, something like 

`input(name: running, type: checkbox, value: running)`

This info is currently available:

<img width="255" alt="screen shot 2017-01-31 at 11 36 05 am" src="https://cloud.githubusercontent.com/assets/439226/22474497/f2ccd8f2-e7a9-11e6-8cb8-0b72d3576959.png">

We should do this for all elements, it's helpful when inspecting a HTML/Angular Form.

**Comment by stevenkampen** [comment]
@rajinder-yadav We actually have an issue for this already (#647). The same issue actually applies to lots of different types of elements, so I want to do it all at once.
