### ISSUE TITLE
Update for angular 2.4.7

### ISSUE THREAD

**Issue by okngay** [rangle/augury#968]
Pleace update support for angular 2.4.7

**Comment by stevenkampen** [comment]
Need to investigate what doesn't work and what is required to fix that.

**Comment by rajinder-yadav** [comment]
I've confirmed, created a new app using ng-cli, and only the _Component Tree_ display the components, nothing else seems to be working. 

* The tabs don't function, no properties get shown
* There is a delay before Augury is shown
* Clicking on the components in the _Component Tree_ does nothing
* Unable to select a component

**Comment by stevenkampen** [comment]
@rajinder-yadav Can you review this one quickly please? I want to make the new release as soon as possible.
