### ISSUE TITLE
Add issue creation format section to readme

### ISSUE THREAD

**Issue by igor-ka** [rangle/augury#975]
Hey @rajinder-yadav I think it would make sense to explain the ideal issue format for this repository in this repot. What do you think?

**Comment by rajinder-yadav** [comment]
@igor-ka We have the steps defined in the issue that is created, I think they are self-explanatory. If you think we need to add more instructions to it, let me know.

I know when I open issues on other projects, I don't bother reading anything, I feel in a rush to get it out of the way and get back to what I was doing. I'm guess most people was the step to be quick and simple, that was one of the reason I decided to add this issue creation feature.
