### ISSUE TITLE
augury Angular-cli  When I installed the augury .Error is as follows

### ISSUE THREAD

**Issue by panglisen** [rangle/augury#982]
![image](https://cloud.githubusercontent.com/assets/7509205/22959796/0368a968-f374-11e6-9215-d147df677eda.png)

How to solve?

**Comment by panglisen** [comment]
![image](https://cloud.githubusercontent.com/assets/7509205/22959856/7875a59e-f374-11e6-8a9d-0ecd8a2d3acc.png)
There's nothing in it

**Comment by stevenkampen** [comment]
@panglisen Can you elaborate on how this error can be recreated? Are you running the version from the webstore? Are you building a new project with the CLI?

**Comment by panglisen** [comment]
@stevenkampen 
It is Augury version
![image](https://cloud.githubusercontent.com/assets/7509205/23003737/ae7f5d1a-f42d-11e6-9ed7-bcede2b4d421.png)

here is a new project build with CLI
![image](https://cloud.githubusercontent.com/assets/7509205/23004354/1a03539a-f431-11e6-93d4-995a9698f32b.png)

**Comment by paulwalker** [comment]
Experiencing the same issue. I did restart browser after plugin installation.

```
@angular/cli: 1.0.0-rc.1
node: 7.6.0
```

**Comment by igor-ka** [comment]
Hey @panglisen @paulwalker, is this issue still occurring? Both CLI and Augury have advanced several versions since this issue occurred.

**Comment by paulwalker** [comment]
It is no longer an issue with the most recent releases.
