### ISSUE TITLE
Support Angular 4.0

### ISSUE THREAD

**Issue by stevenkampen** [rangle/augury#997]

**Comment by stevenkampen** [comment]
Looks like something has changed and the global `ng`no longer exists, but I haven't looked into it more than that. Not sure if the "debug" flag is set differently now, but others have reported this issue on the angular repo (https://github.com/angular/angular/issues/14738).

I've reached out to someone in the angular core team, so hopefully we'll hear back soon.

**Comment by stevenkampen** [comment]
Looks good with v4.0.0-rc.2!

**Comment by szh** [comment]
Doesn't seem to work in Angular 4.0 final release...

**Comment by szh** [comment]
Here's the error I'm getting in the Chrome dev console:
![image](https://cloud.githubusercontent.com/assets/546965/24430081/885ac832-13da-11e7-82d2-c92e40d2ce39.png)
